ae.addLanguage("norwegian", {
	"GameTitle": "Estranged",
	"GameSubtitle": "Act I",
	"Language": "norwegian",
	"Close": "Lukk",
	"CreditsWithThanksTo": "Med takk til",
	"CreditsTeam": "Lag",
	"CreditsMainMenu": "Gå til hovedmeny",
	"CreditsCreator": "Skaper",
	"CreditsVoices": "Stemmer",
	"CreditsPreviousVoices": "Tidligere stemmer",
	"CreditsTranslators": "Oversettere",
	"CreditsTesters": "Testere",
	"CreditsMacOSBuild": "Mac OS-versjon",
	"CreditsDanishTranslator": "Dansk oversetter",
	"CreditsMapCompiler": "Kartkompilator",
	"CreditsTranslator": "Oversetter",
	"CreditsTester": "Tester",
	"CreditsPhotographer": "Fotograf",
	"CreditsGuitarSamples": "Gitarprøver",
	"CreditsProjectLead": "Prosjektleder",
	"CreditsLevelDesigner": "Nivådesigner",
	"CreditsProgrammer": "Programmerer",
	"CreditsStoryDesigner": "Historiedesigner",
	"CreditsTextureArtist": "Teksturartist",
	"CreditsModelArtist": "3D-artist",
	"CreditsVoiceOf": "Stemmen til",
	"CreditsLeadMusician": "Musikkleder",
	"CreditsShaderArtist": "Skyggeleggingsartist",
	"CreditsOmnicorpThug": "Arque-skurk",
	"CreditsOmnicorpBroadcaster": "Arque-oppleser",
	"CreditsMirrorHosting": "Vertskap for nedlastingsspeil",
	"CreditsAudioDesigner": "Lyddesigner",
	"CreditsOculusRift": "Donerte Oculus Rift",
	"CreditsDonors": "Prosjektdonorer",
	"CreditsSteamTranslation": "Steam Translation Server",
	"Workstation": "Arbeidsstasjon",
	"EndSession": "Ønsker du å avslutte økten din?",
	"OK": "OK",
	"Cancel": "Avbryt",
	"IconEmail": "E-post",
	"IconLogOff": "Logg av",
	"IconDoorUnlock": "Lås opp dør",
	"OnlyPrintIfNecessary": "Spar miljøet. Skriv ut denne e-posten kun hvis du må det.",
	"Incorrect": "Beklager, det var feil.",
	"SecretPetName": "alex",
	"DialogGenerator": "Generatorkonsoll",
	"DialogGeneratorOverHeat": "ADVARSEL: GENERATOR OVEROPPHETES",
	"DialogGeneratorDisconnect": "LOGG UT AV GENERATORKONSOLL",
	"YantoWardName": "Yanto Ward",
	"YantoWardAccount": "Yanto Ward < yanto.ward@arque.local >",
	"Pets_R_Us_Update": "Oppdatering fra Pets Are Us",
	"Pets_R_Us_UpdateSummary": "Mr. Ward, Alex er på bedringens vei...",
	"Pets_R_Us_From": "Pets Are Us < judy@petsrus.com >",
	"Pets_R_Us_Line1": "Mr. Ward,",
	"Pets_R_Us_Line2": "Hunden din, Alex, er på bedringens vei og har reagert svært bra på de legemidlene vi har gitt ham.",
	"Pets_R_Us_Line3": "Du kan komme og hente Alex på mandag.",
	"Pets_R_Us_Line4": "Takk,",
	"Pets_R_Us_Line5": "Judy Ferrand.",
	"WhatIsThatSmell": "HVA ER DEN LUKTEN",
	"Srsly": "seriøst",
	"NigelHeathcoat": "Nigel Heathcoat < nigel@arque.local >",
	"HaveYouSeenMyLunch": "Har du sett lunsjen min?",
	"HaveYouSeenMyLunchSummary": "Hei, har du sett...",
	"FrancisRobella": "Francis Robella < francis@arque.local >",
	"FrancisRobellaLine1": "Hei,",
	"FrancisRobellaLine2": "Har du sett lunsjen min? Jeg la den i kjøleskapet og nå er den borte. Hvis hun har stjålet det igjen så klikker jeg. Hun stjeler alltid tingene mine!",
	"FrancisRobellaLine3": "Francis",
	"PleaseEnterSecretAnswer": "Vennligst tast inn svaret på det hemmelige spørsmålet for å fortsette:",
	"NameOfPet": "Hva er navnet på kjæledyret ditt?",
	"UnlockAllDoorsPrompt": "Bruk knappen nedenfor for å låse opp alle dører på gul etasje.",
	"UnlockAllDoors": "Lås opp alle dører",
	"DoorsAreUnlocked": "Alle dører på gul etasje er for øyeblikket låst opp.",
	"Image1": "IMG_0270_104942.JPEG",
	"Image2": "IMG_0430_104912.JPEG",
	"Image3": "IMG_0430_104944.JPEG",
	"Image4": "IMG_0470_104454.JPEG",
	"Image5": "IMG_0437_104954.JPEG",
	"Image6": "IMG_0440_104964.JPEG",
	"Image7": "IMG_0437_104964.JPEG",
	"Image8": "IMG_034324_432432.MP4",
	"ChristianPlitheName": "Christian Plithe",
	"ChristianPlitheAccount": "Christian Plithe < christian.plithe@arque.local >",
	"LunchRoomTitle": "Lunsjrom",
	"LunchRoomSummary": "Christian, jeg kan ikke stoppe...",
	"LunchRoomLine1": "Christian, jeg kan ikke stoppe å tenke på deg. Fra det øyeblikket jeg først så deg i lunsjrommet forstod jeg at du var den rette. Ut i fra de fettete kyllingvingene som sakte gned over leppene dine ---------- du er en veldig mektig mann. Jeg håper å se deg der samme tid i morgen. Jeg vil holde øye med deg...",
	"AdmirerName": "Din beundrer",
	"AdmirerAccount": "Beundrer < anonymous@arque.local >",
	"WilliamShortAccount": "William Short < william.short@arque.local >",
	"WilliamShortSig": "William Short, linjeleder.",
	"WilliamShortTitle": "SV: Trakassering",
	"WilliamShortSummary": "Christian, jeg har rapportert dette...",
	"WilliamShortLine1": "Hei Christian,",
	"WilliamShortLine2": "Jeg har rapportert dette til personalavdelingen og intern støtte, de vil forsøke å spore opp denne \"beundreren\".",
	"WilliamShortLine3": "Du må innrømme at hele denne affæren er hysterisk morsom...",
	"ChrisLine1": "Hei Will,",
	"ChrisLine2": "Jeg får stadig disse særs merkelige e-postene fra noen som fremstår som min \"beundrer\", de kommer fra anonymous@arque.local også.",
	"ChrisLine3": "Her er et utdrag fra en:",
	"ChrisLine4": "Jeg vet at vi har hatt noen uoverensstemmelser i det siste, men jeg trenger hjelp med dette... til å begynne med var det rart, nå er det rett og slett skummelt. Kan dette telles som en offisiell klage?",
	"ChrisLine5": "Christian",
	"MeetMeTitle": "Hvorfor møtte du meg ikke?",
	"MeetMeSummary": "Jeg var mutters alene i...",
	"MeetMeLine1": "Jeg var mutters alene i lunsjrommet, jeg ville se deg spise men du kom ikke! Skremmer jeg deg?",
	"MeetMeLine2": "Jeg lover at jeg ikke er slik, men hei, vi kan prøve igjen i morgen. Jeg vil vente på deg.",
	"HandledTheManagerTitle": "Jeg så måten du behandlet sjefen på",
	"HandledTheManagerSummary": "Jeg likte virkelig...",
	"HandledTheManagerLine1": "Jeg likte virkelig måten du behandlet sjefen på i dag, du er et beist når du er sint. Jeg likte måten svetten trillet rett av den andre haken din... det ligger bare noe ved det.",
	"JonathanBillyName": "Jonathan Billy",
	"JonathanBillyAccount": "Jonathan Billy < jonathan.billy@arque.local >",
	"JonathanBillyLine1": "er du på skift på fredag",
	"JonathanBillyLine2": "dattern min har svømekonkurranse og kona sier jg må gå dit. kan du dekke skifte mitt",
	"JonathanBillyLine3": "takk",
	"JonathanBillyLine4": "fra jono",
	"DavidGravenName": "David Graven",
	"DavidGravenAccount": "David Graven < david.graven@arque.local >",
	"DavidGravenTitle1": "SV: fredag",
	"DavidGravenTitle2": "Bokser",
	"DavidGravenSummary1": "Den er grei, kos deg :)",
	"DavidGravenSummary2": "Kan vi flytte noen av boksene",
	"DavidGravenEmail1": "Jono,",
	"DavidGravenEmail2": "Kan vi flytte noen av boksene til varehuset på Arque East? De sier at det skal komme flere, men vi kan ikke få plass til så mange flere her inne - med tanke på de store kassene med forsyninger også. Jeg skal snakke med Jeff om saken... de skal visst flytte noen til overetasjen på et eller annet tidspunkt.",
	"DavidGravenSig": "Dave",
	"JonathanBillyTitle": "fredag",
	"JeffHerbandTitle": "Innkommende...",
	"JeffHerbandSummary": "Det er flere innkommende bokser",
	"JeffHerbandAccount": "Jeff Herband < jeff.herband@arque.local >",
	"JeffHerbandName": "Jeff Herband",
	"JeffHerbandSig": "Arque West, lagersjef",
	"JeffHerbandLine1": "Det er flere innkommende bokser. Bare husk å holde dem sikre, vi vil ikke at ting skal ødelegges.",
	"WentworthHeraldTitle": "Wentworth Herald",
	"WentworthHeraldTagline": "Førstevalget for nyheter, sladder, sport, showbiz, arbeidsliv og kryssord. Det er din avis, ditt liv.",
	"MoreOnPage7": "Mer på side 7",
	"MoreOnPage10": "Mer på side 10",
	"LighthouseDecomissionedTitle": "Fyrtårn tatt ut av drift",
	"LighthouseDecomissionedParagraph1": "Fyrtårnet på knausen i Redton vil bli tatt ut av drift av den lokale borgermesteren John Menn, etter en granskning foretatt av kystvakten.",
	"LighthouseDecomissionedParagraph2": "\"Vi er sikre på at dette ikke vil påvirke den passerende trafikken\", kommenterte Bill Hayak fra Instituttet for Maritim Trafikkgranskning. \"Selv om man en gang kunne se lasteskip like utenfor Redtons kyst er ikke dette lenger tilfellet siden fraktruter fra fastlandet har blitt endret\", la han til.",
	"LighthouseDecomissionedParagraph3": "Ved forespørsel så nektet borgermesteren å kommentere før han har utgitt en offisiell uttalelse angående stengingen av fyrtårnet.",
	"LighthouseDecomissionedParagraph4": "Lokale innbyggere er ikke glade for endringen, og en lokal innbygger var bekymret over hvilken effekt det vil ha på mindre handelsfartøy som fremdeles går i havn ved øya, og bemerker det som den siste spikeren i kista for øyas stille havn. \"Det stopper en hel del av øyas virksomhet\", sa han.",
	"LighthouseDecomissionedParagraph5": "Noen ganger er fyrtårnet det eneste som tillater mindre fartøy å komme for å handle med lokale bedrifter, det er noe vi alle er bekymret over - hva skjer når det ikke blir igjen noen importvirksomhet?",
	"LighthouseDecomissionedQuote": "\"For få\" skip til å være et sikkerhetsproblem, sier kystvakten",
	"LostTitle": "Savnet",
	"LostParagraph1": "To uker har gått siden den lokale Arcque-ansatte Christian Plithe mistet sin sorte katt, \"Lucky\". Han har oppfordret alle som måtte se katten om å kontakte ham umiddelbart.",
	"ScarecrowCompetitionTitle": "Lokal konkurranse er i gang",
	"ScarecrowCompetitionParagraph1": "En av de mest populære konkurransene Redton avholder er tilbake for sitt årlige arrangement.",
	"ScarecrowCompetitionParagraph2": "Samfunnet kommer sammen hvert år for å skape de mest skremmende og uhyggelige fugleskremslene de kan for å holde fuglene unna. Fjorårets vinner var den åtte år gamle skolegutten, Joshua Fentons, med hans representasjon av bestemoren sin som overbeviste dommerpanelet.",
	"ScarecrowCompetitionParagraph3": "I år vil vinneren av konkurransen motta en prydelig samling av kaker fra Julia Menn, borgermesterens kone, som nylig åpnet hennes egen kakebutikk på øya.",
	"ScarecrowCompetitionParagraph4": "Festlighetene stopper ikke med bare fugleskremslene som er til utstilling - hele uken finnes det boder og andre aktiviteter som finner sted over hele byen. Dersom du ikke har sett fugleskremslene ennå, dra ned til det årlige arrangementet for å se hva alt oppstyret handler om, og smake noe av det beste innen mat og drikke som Redton har å tilby.",
	"ScarecrowCompetitionParagraph5": "Dersom du ikke kan reise ned for å se på fugleskremslene, sjekk ut neste utgave hvor vi vil ha en fullstendig oversikt over bidragene.",
	"OmnicorpTitle": "Arque Corporation kjøper opp Phillips Pharmaceuticals",
	"OmnicorpParagraph1": "Tretti arbeidere ble gitt varsler tidlig forrige uke i det giganten Arque Corporation sluttførte sitt oppkjøp av den lokale farmasøytiske produsenten Phillips Pharmaceuticals. Oppkjøpet følger et veldig offentlig sammenbrudd av den tidligere eieren som resulterte i et søk etter investorer.",
});