ae.addLanguage("french", {
	"GameTitle": "Estranged",
	"GameSubtitle": "Act I",
	"Language": "french",
	"Close": "Fermer",
	"CreditsWithThanksTo": "Merci à",
	"CreditsTeam": "Équipe",
	"CreditsMainMenu": "Aller au menu principal",
	"CreditsCreator": "Créateur",
	"CreditsVoices": "Voix",
	"CreditsPreviousVoices": "Voix précédentes",
	"CreditsTranslators": "Traducteurs",
	"CreditsTesters": "Testeurs",
	"CreditsMacOSBuild": "Version Mac OS",
	"CreditsDanishTranslator": "Traducteur danois",
	"CreditsMapCompiler": "Compileur de cartes",
	"CreditsTranslator": "Traducteur",
	"CreditsTester": "Testeur",
	"CreditsPhotographer": "Photographe",
	"CreditsGuitarSamples": "Extraits de Guitare",
	"CreditsProjectLead": "Chef de Projet",
	"CreditsLevelDesigner": "Level Designer",
	"CreditsProgrammer": "Programmeur",
	"CreditsStoryDesigner": "Écriture du Scénario",
	"CreditsTextureArtist": "Artiste 2D",
	"CreditsModelArtist": "Artiste Modeleur 3D",
	"CreditsVoiceOf": "Voix de",
	"CreditsLeadMusician": "Musicien Principal",
	"CreditsShaderArtist": "Artiste Shaders",
	"CreditsOmnicorpThug": "Homme de main d'Arque",
	"CreditsOmnicorpBroadcaster": "Message radio d'Arque",
	"CreditsMirrorHosting": "Hébergement du Miroir de Téléchargement",
	"CreditsAudioDesigner": "Concepteur Audio",
	"CreditsOculusRift": "Donateur de l'Oculus Rift",
	"CreditsDonors": "Donateurs",
	"CreditsSteamTranslation": "Le Steam Translation Server",
	"Workstation": "Poste de travail",
	"EndSession": "Voulez-vous fermer la session ?",
	"OK": "OK",
	"Cancel": "Annuler",
	"IconEmail": "E-mail",
	"IconLogOff": "Se déconnecter",
	"IconDoorUnlock": "Déverrouillage de la porte",
	"OnlyPrintIfNecessary": "Protégez l'environnement. N'imprimez cet e-mail que si vous le devez.",
	"Incorrect": "Réponse incorrecte.",
	"SecretPetName": "alex",
	"DialogGenerator": "Console du générateur",
	"DialogGeneratorOverHeat": "ALERTE : GÉNÉRATEUR EN SURCHAUFFE",
	"DialogGeneratorDisconnect": "SE DÉCONNECTER DE LA CONSOLE DU GÉNÉRATEUR",
	"YantoWardName": "Yanto Ward",
	"YantoWardAccount": "Yanto Ward < yanto.ward@arque.local >",
	"Pets_R_Us_Update": "Résultat - Nos chers animaux",
	"Pets_R_Us_UpdateSummary": "M. Ward, Votre chien Alex...",
	"Pets_R_Us_From": "Nos chers animaux < judy@petsrus.com >",
	"Pets_R_Us_Line1": "M. Ward,",
	"Pets_R_Us_Line2": "Votre chien Alex récupère et a très bien répondu aux médicaments que nous lui avons donné.",
	"Pets_R_Us_Line3": "Vous pourrez récupérer Alex lundi.",
	"Pets_R_Us_Line4": "Merci,",
	"Pets_R_Us_Line5": "Judy Ferrand.",
	"WhatIsThatSmell": "C'EST QUOI CETTE ODEUR ?",
	"Srsly": "sérieusement...",
	"NigelHeathcoat": "Nigel Heathcoat < nigel@arque.local >",
	"HaveYouSeenMyLunch": "Tu as vu mon déjeuner ?",
	"HaveYouSeenMyLunchSummary": "Salut, Tu aurais pas vu mon...",
	"FrancisRobella": "Francis Robella < francis@arque.local >",
	"FrancisRobellaLine1": "Salut,",
	"FrancisRobellaLine2": "Tu aurais pas vu mon déjeuner ? Je l'avais laissé dans le réfrigérateur. Si c'est encore elle qui me l'a volé je vais craquer. Elle me vole tout le temps mes affaires !",
	"FrancisRobellaLine3": "Francis",
	"PleaseEnterSecretAnswer": "Veuillez entrer la réponse de la question secrète pour continuer :",
	"NameOfPet": "Quel est le nom de votre animal de compagnie ?",
	"UnlockAllDoorsPrompt": "Utilisez le bouton ci-dessous pour déverrouiller toutes les portes sur le sol jaune.",
	"UnlockAllDoors": "Déverrouiller toutes les portes",
	"DoorsAreUnlocked": "Toutes les portes sur le sol jaune sont actuellement déverrouillées.",
	"Image1": "IMG_0270_104942.JPEG",
	"Image2": "IMG_0430_104912.JPEG",
	"Image3": "IMG_0430_104944.JPEG",
	"Image4": "IMG_0470_104454.JPEG",
	"Image5": "IMG_0437_104954.JPEG",
	"Image6": "IMG_0440_104964.JPEG",
	"Image7": "IMG_0437_104964.JPEG",
	"Image8": "IMG_034324_432432.MP4",
	"ChristianPlitheName": "Christian Plithe",
	"ChristianPlitheAccount": "Christian Plithe < christian.plithe@arque.local >",
	"LunchRoomTitle": "Cafétéria",
	"LunchRoomSummary": "Christian, je ne peux pas...",
	"LunchRoomLine1": "Christian, je ne peux pas m'arrêter de penser à toi. Dès l'instant où je t'ai vu dans la cafétéria, je savais que c'était toi. Des ailes de poulets bien grasses frottants lentement tes lèvres......... Tu es si puissant. J'espère te revoir à la même heure demain. Je surveillerai...",
	"AdmirerName": "Ton admiratrice",
	"AdmirerAccount": "Admiratrice < anonymous@arque.local >",
	"WilliamShortAccount": "William Short < william.short@arque.local >",
	"WilliamShortSig": "William Short, Chef de gamme.",
	"WilliamShortTitle": "RE : Harcèlement",
	"WilliamShortSummary": "Salut Christian, J'ai signalé...",
	"WilliamShortLine1": "Salut Christian,",
	"WilliamShortLine2": "J'ai rapporté ceci au RH et au Service Informatique, ils vont essayer de traquer l'« admiratrice ».",
	"WilliamShortLine3": "Il faut quand même reconnaître que tout ça est assez hilarant...",
	"ChrisLine1": "Salut Will,",
	"ChrisLine2": "Je continue de recevoir ces e-mails très étranges de cette personne prétendant être mon « admirateur », ils viennent aussi de anonymous@arque.local.",
	"ChrisLine3": "Voici un extrait de l'un d'eux :",
	"ChrisLine4": "Je comprends qu'on ait eu des différents récemment, mais j'ai besoin d'aide avec cette... au début c'était bizarre, mais maintenant ça en devient carrément effrayant. Est-ce que ça peut compter comme une plainte officielle ?",
	"ChrisLine5": "Christian",
	"MeetMeTitle": "Pourquoi tu n'es pas venu me retrouver ?",
	"MeetMeSummary": "J'étais toute seule dans la...",
	"MeetMeLine1": "J'étais toute seule dans la cafétéria, je voulais te regarder manger mais tu n'es pas venu ! Je te fais peur ?",
	"MeetMeLine2": "Je te promets que je ne suis pas comme ça, on recommence demain ? Je t'attendrais.",
	"HandledTheManagerTitle": "J'ai vu la façon dont tu as traité le manager",
	"HandledTheManagerSummary": "J'ai vraiment aimé la manière...",
	"HandledTheManagerLine1": "J'ai vraiment aimé la manière dont tu as traité le manager aujourd'hui, tu es une vraie bête quand tu es en colère. J'ai aimé la façon dont la sueur est sortie de ton double menton... et c'est pas la seule chose que j'aime chez toi.",
	"JonathanBillyName": "Jonathan Billy",
	"JonathanBillyAccount": "Jonathan Billy < jonathan.billy@arque.local >",
	"JonathanBillyLine1": "é tu en déplacemen vendredi",
	"JonathanBillyLine2": "ma fill a 1 competition de natasion et ma femme veu que j aille. tu peu me renplacer?",
	"JonathanBillyLine3": "merci",
	"JonathanBillyLine4": "de jono",
	"DavidGravenName": "David Graven",
	"DavidGravenAccount": "David Graven < david.graven@arque.local >",
	"DavidGravenTitle1": "RE : vendredi",
	"DavidGravenTitle2": "Cartons",
	"DavidGravenSummary1": "Oui bien sûr, passe une bonne journée :)",
	"DavidGravenSummary2": "Peut-on déplacer une partie des...",
	"DavidGravenEmail1": "Jono,",
	"DavidGravenEmail2": "Peut-on déplacer une partie des cartons dans l'entrepôt Est ? Ils disent que d'autres arrivent, mais on a plus beaucoup de place ici : il y a trop de grandes caisses d'approvisionnement. Il faut que je parle de ça à Jeff... À un moment, elles sont destinées à monter l'étage.",
	"DavidGravenSig": "Dave",
	"JonathanBillyTitle": "Vendredi",
	"JeffHerbandTitle": "Nouvel arrivage...",
	"JeffHerbandSummary": "Un arrivage d'autres caisses est...",
	"JeffHerbandAccount": "Jeff Herband < jeff.herband@arque.local >",
	"JeffHerbandName": "Jeff Herband",
	"JeffHerbandSig": "Arque Ouest, Gestionnaire d'entrepôt",
	"JeffHerbandLine1": "Un arrivage d'autres caisses est en route. N'oubliez pas de les manipuler avec soin, nous ne voulons pas remplacer les objets cassés.",
	"WentworthHeraldTitle": "Wentworth Herald",
	"WentworthHeraldTagline": "Le premier pour les actus gossip, sport, showbiz, business et mots croisés. C'est votre journal, votre vie.",
	"MoreOnPage7": "Plus d'informations sur la page 7",
	"MoreOnPage10": "Plus d'informations sur la page 10",
	"LighthouseDecomissionedTitle": "Phare désaffecté",
	"LighthouseDecomissionedParagraph1": "Le phare situé sur les terres de Redton est prêt à être déclassé par le maire John Menn, à la suite d'une enquête menée par les garde-côtes.",
	"LighthouseDecomissionedParagraph2": "« Nous sommes convaincus qu'il n'y aura aucun impact sur trafic maritime de la zone » commenta Bill Hayak du département des enquêtes sur le trafic maritime. « À certains moments, on pouvait voir des navires cargo au large des côtes de Redton, maintenant ce n'est plus le cas depuis la modification des routes maritimes. » a t-il ajouté.",
	"LighthouseDecomissionedParagraph3": "Interrogé, le maire refuse tout commentaire jusqu'à ce qu'il y ait une déclaration officielle de la fermeture du phare.",
	"LighthouseDecomissionedParagraph4": "Les résidents locaux ne sont pas ravis du changement. Un résident local préoccupé par ses effets sur les petits navires commerciaux toujours présents sur le port de l'île, disait que c'est le dernier clou du cercueil pour mettre à mort la partie portuaire de l'île. « Beaucoup d'activités de l'île vont s'arrêter ».",
	"LighthouseDecomissionedParagraph5": "Parfois, le phare est la seule chose qui permet aux petits navires de venir commercer avec les entreprises locales, c'est quelque chose qui nous rend tous inquiets. Que va-t-il nous arriver lorsqu'il n'y aura plus aucune entreprise importatrice ici ?",
	"LighthouseDecomissionedQuote": "« Trop peu » de navires pour être une question de sécurité, nous ont confié les garde-côtes.",
	"LostTitle": "Perdu",
	"LostParagraph1": "Deux semaines se sont écoulées depuis qu'un employé local d'Arque, Christian Plithe, a perdu son chat noir « Lucky ». Il demande à tous ceux le voyant de le contacter immédiatement.",
	"ScarecrowCompetitionTitle": "Compétition locale d'épouvantails",
	"ScarecrowCompetitionParagraph1": "L'une des compétitions les plus populaires de Redton est de retour pour son événement annuel.",
	"ScarecrowCompetitionParagraph2": "La communauté se réunit tous les ans pour créer les plus terrifiants épouvantails afin d'éloigner les oiseaux. Le gagnant de l'année dernière, Joshua Fenton, était un garçon de huit ans de l'école locale qui a réussi à gagner le vote des juges grâce à la représentation de sa grand-mère.",
	"ScarecrowCompetitionParagraph3": "Cette année, le vainqueur de la compétition recevra une sélection raffinée de gâteaux de Julia Menn, la femme du maire qui a récemment ouvert son propre magasin de gâteaux sur l'île.",
	"ScarecrowCompetitionParagraph4": "Les festivités ne s'arrêtent pas qu'aux épouvantails qui sont exposés toute la semaine. Des tas d'autres activités ont lieu partout en ville. Si vous n'avez pas encore vu les épouvantails, faites un tour à cet événement pour voir de quoi il s'agit, en plus de pouvoir participer aux dégustations des meilleurs aliments et boissons que Redton peut vous offrir.",
	"ScarecrowCompetitionParagraph5": "Si vous ne pouvez pas allez voir les épouvantails, consultez le prochain numéro. Nous feront une pleine page sur les participants du concours.",
	"OmnicorpTitle": "Arque Corporation acquiert Phillips Pharmaceuticals",
	"OmnicorpParagraph1": "Trente employés ont remarqué en début de semaine dernière que le géant Arque Corporation a fait l'acquisition de Phillips Pharmaceuticals, le fabricant pharmaceutique local. Le rachat fait suite à la dépression nerveuse de son ancien propriétaire, résultant à une recherche d'investisseurs.",
});