ae.addLanguage("italian", {
	"GameTitle": "Estranged",
	"GameSubtitle": "Act I",
	"Language": "italian",
	"Close": "Chiudi",
	"CreditsWithThanksTo": "Con ringraziamenti a",
	"CreditsTeam": "Team",
	"CreditsMainMenu": "Torna al menu principale",
	"CreditsCreator": "Autore",
	"CreditsVoices": "Doppiatori",
	"CreditsPreviousVoices": "Doppiatori precedenti",
	"CreditsTranslators": "Traduttori",
	"CreditsTesters": "Tester",
	"CreditsMacOSBuild": "Versione per Mac OS",
	"CreditsDanishTranslator": "Traduttore danese",
	"CreditsMapCompiler": "Compilatore di mappe",
	"CreditsTranslator": "Traduttore",
	"CreditsTester": "Tester",
	"CreditsPhotographer": "Fotografo",
	"CreditsGuitarSamples": "Campioni di chitarra",
	"CreditsProjectLead": "Direttore del progetto",
	"CreditsLevelDesigner": "Progettista dei livelli",
	"CreditsProgrammer": "Programmatore",
	"CreditsStoryDesigner": "Ideatore della storia",
	"CreditsTextureArtist": "Artista delle texture",
	"CreditsModelArtist": "Artista dei modelli 3D",
	"CreditsVoiceOf": "Voce di",
	"CreditsLeadMusician": "Musicista capo",
	"CreditsShaderArtist": "Artista degli shader",
	"CreditsOmnicorpThug": "Scagnozzo di Arque",
	"CreditsOmnicorpBroadcaster": "Emittente di Arque",
	"CreditsMirrorHosting": "Host dei mirror di download",
	"CreditsAudioDesigner": "Progettista del suono",
	"CreditsOculusRift": "Donatore dell'Oculus Rift",
	"CreditsDonors": "Donatori del progetto",
	"CreditsSteamTranslation": "Lo Steam Translation Server",
	"Workstation": "Workstation",
	"EndSession": "Terminare la sessione?",
	"OK": "OK",
	"Cancel": "Annulla",
	"IconEmail": "Email",
	"IconLogOff": "Esci",
	"IconDoorUnlock": "Sblocco delle porte",
	"OnlyPrintIfNecessary": "Salva l'ambiente. Stampa questa email solo se necessario.",
	"Incorrect": "Siamo spiacenti, ma il valore inserito non era valido.",
	"SecretPetName": "alex",
	"DialogGenerator": "Console del generatore",
	"DialogGeneratorOverHeat": "ATTENZIONE: GENERATORE IN SURRISCALDAMENTO",
	"DialogGeneratorDisconnect": "DISCONNETTITI DALLA CONSOLE DEL GENERATORE",
	"YantoWardName": "Yanto Ward",
	"YantoWardAccount": "Yanto Ward <yanto.ward@arque.local>",
	"Pets_R_Us_Update": "Aggiornamento da Mondo Animale",
	"Pets_R_Us_UpdateSummary": "Signor Ward, Alex si è ripreso...",
	"Pets_R_Us_From": "Mondo Animale <judy@mondo-animale.com>",
	"Pets_R_Us_Line1": "Signor Ward,",
	"Pets_R_Us_Line2": "Il suo cane, Alex, si sta riprendendo ed ha risposto molto bene alle droghe che gli abbiamo somministrato.",
	"Pets_R_Us_Line3": "Potrà venirlo a prendere questo lunedì.",
	"Pets_R_Us_Line4": "Grazie,",
	"Pets_R_Us_Line5": "Judy Ferrand.",
	"WhatIsThatSmell": "COS'È QUELL'ODORE",
	"Srsly": "seriamente",
	"NigelHeathcoat": "Nigel Heathcoat <nigel@arque.local>",
	"HaveYouSeenMyLunch": "Hai visto il mio pranzo?",
	"HaveYouSeenMyLunchSummary": "Ehi, hai per caso visto il...",
	"FrancisRobella": "Francis Robella <francis@arque.local>",
	"FrancisRobellaLine1": "Ehi,",
	"FrancisRobellaLine2": "hai per caso visto il mio pranzo? L'ho lasciato nel frigo ed è sparito. Se è stata lei a fregarmelo di nuovo, andrò su tutte le furie. Continua a rubare le mie cose!",
	"FrancisRobellaLine3": "Francis",
	"PleaseEnterSecretAnswer": "Inserisci la risposta alla domanda segreta per procedere:",
	"NameOfPet": "Qual è il nome del tuo animale?",
	"UnlockAllDoorsPrompt": "Usa il pulsante sottostante per sbloccare tutte le porte del piano giallo.",
	"UnlockAllDoors": "Sblocca tutte le porte",
	"DoorsAreUnlocked": "Tutte le porte del piano giallo sono attualmente sbloccate.",
	"Image1": "DO_CHARM_URSA.JPEG",
	"Image2": "ARSA_DILSO.JPEG",
	"Image3": "THINK_TERA_DEPO_RARI.JPEG",
	"Image4": "ITCHY_GRAYS.JPEG",
	"Image5": "GR_CHRIST_YAY.JPEG",
	"Image6": "SHY_GRAY_TIC.JPEG",
	"Image7": "GIST_CAR_YHY.JPEG",
	"Image8": "MIO_GOLF_II.MP4",
	"ChristianPlitheName": "Antonio M. Buonadonna",
	"ChristianPlitheAccount": "Antonio M. Buonadonna <AMB@arque.local>",
	"LunchRoomTitle": "Mensa",
	"LunchRoomSummary": "Antonio, non riesco a smettere...",
	"LunchRoomLine1": "Antonio, non riesco a smettere di pensare a te. Da quando ti ho visto per la prima volta nella mensa, ho capito che eri l'uomo della mia vita. Da quelle ali di pollo oleose che strofinavano lentamente le tue labbra ---------- sei un uomo forte. Spero di rivederti alla stessa ora domani. Sarò lì a guardarti...",
	"AdmirerName": "La tua ammiratrice",
	"AdmirerAccount": "Ammiratrice <anonymous@arque.local>",
	"WilliamShortAccount": "William Short <william.short@arque.local>",
	"WilliamShortSig": "William Short, Manager di linea.",
	"WilliamShortTitle": "RE: Molestie",
	"WilliamShortSummary": "Antonio, ho segnalato la cosa alle Risorse umane...",
	"WilliamShortLine1": "Ciao Antonio,",
	"WilliamShortLine2": "ho segnalato la cosa alla sezione per le Risorse umane e all'Assistenza interna, cercheranno di rintracciare questa \"ammiratrice\".\"",
	"WilliamShortLine3": "Devi ammettere che tutta questa storia è piuttosto da ridere...",
	"ChrisLine1": "Ciao Will,",
	"ChrisLine2": "continuo a ricevere delle email stranissime da qualcuno che sostiene di essere la mia \"ammiratrice\", da anonymous@arque.local, tra l'altro.",
	"ChrisLine3": "Eccoti una parte di uno dei messaggi:",
	"ChrisLine4": "Apprezzo che abbiamo avuto le nostre divergenze di recente, ma mi serve davvero una mano con questa storia... all'inizio era solo strano, ora è decisamente spaventoso. È possibile far valere la cosa come lamentela ufficiale?",
	"ChrisLine5": "Antonio",
	"MeetMeTitle": "Perché non mi hai incontrata?",
	"MeetMeSummary": "Ero tutta sola nella...",
	"MeetMeLine1": "Ero tutta sola nella mensa, volevo guardarti mangiare ma non sei venuto! Ti sto spaventando?",
	"MeetMeLine2": "Prometto di non essere quel tipo di persona, guarda, possiamo riprovarci domani. Sarò lì ad aspettarti.",
	"HandledTheManagerTitle": "Ho visto come hai gestito il tuo manager",
	"HandledTheManagerSummary": "Ho davvero apprezzato...",
	"HandledTheManagerLine1": "Ho davvero apprezzato il modo in cui hai gestito il tuo manager oggi, sei davvero una bestia quando ti arrabbi. Mi è piaciuto quando il sudore stava colando dal tuo doppio mento... è qualcosa di veramente unico.",
	"JonathanBillyName": "Jonathan Billy",
	"JonathanBillyAccount": "Jonathan Billy <jonathan.billy@arque.local>",
	"JonathanBillyLine1": "6 tu D turno venerD",
	"JonathanBillyLine2": "mia figlia ha una gara d nuoto e mia moglie dice ke devo andare. puoi sostituirmi?",
	"JonathanBillyLine3": "grz",
	"JonathanBillyLine4": "da jono",
	"DavidGravenName": "David Graven",
	"DavidGravenAccount": "David Graven <david.graven@arque.local>",
	"DavidGravenTitle1": "RE: venerdì",
	"DavidGravenTitle2": "Casse",
	"DavidGravenSummary1": "Va benissimo, goditi la giornata :)",
	"DavidGravenSummary2": "Possiamo spostare alcune delle casse",
	"DavidGravenEmail1": "Jono,",
	"DavidGravenEmail2": "Possiamo spostare alcune delle casse al magazzino della Omnicorp Est? Dicono che ce ne sono altre in arrivo ma non possiamo tenerne molte di più qui, lo stesso dicasi per quelle grosse casse di rifornimenti. Ne parlerò a Jeff al riguardo... dovranno spostarne qualcuna di sopra ad un certo punto.",
	"DavidGravenSig": "Dave",
	"JonathanBillyTitle": "venerdì",
	"JeffHerbandTitle": "In arrivo...",
	"JeffHerbandSummary": "Ci sono altre casse in arrivo",
	"JeffHerbandAccount": "Jeff Herband <jeff.herband@arque.local>",
	"JeffHerbandName": "Jeff Herband",
	"JeffHerbandSig": "Arque ovest, Magazziniere capo",
	"JeffHerbandLine1": "Ci sono altre casse in arrivo. Ricordate solo di tenerle al sicuro, non vogliamo che si rompa qualcosa.",
	"WentworthHeraldTitle": "Wentworth Herald",
	"WentworthHeraldTagline": "Sempre in prima linea per le notizie, lo sport, lo spettacolo, gli affari, il gossip e i cruciverba.  Il tuo giornale, la tua vita.",
	"MoreOnPage7": "Continua a pagina 7",
	"MoreOnPage10": "Continua a pagina 10",
	"LighthouseDecomissionedTitle": "Faro chiuso",
	"LighthouseDecomissionedParagraph1": "Il faro che sporge dalla riva a Redton verrà chiuso ufficialmente dal sindaco locale, John Menn, in seguito a delle indagini portate avanti dalla guardia costiera.",
	"LighthouseDecomissionedParagraph2": "\"Siamo sicuri che la cosa non inciderà molto sul traffico marittimo\", ha commentato Bill Hayak, del Centro di ricerca del traffico costiero, \"se un tempo si potevano ancora scorgere le navi cargo al largo di Redton, ora è solo storia vecchia, da quando hanno cambiato le rotte dalla terraferma\", ha aggiunto.",
	"LighthouseDecomissionedParagraph3": "Nell'intervista, il sindaco si è rifiutato di esprimere commenti finché non avrà rilasciato una dichiarazione ufficiale in merito alla chiusura del faro.",
	"LighthouseDecomissionedParagraph4": "I residenti non sono rimasti molto felici del cambiamento. Uno di loro era preoccupato di come questo avrebbe potuto avere effetto sulle piccole imbarcazioni mercantili che fanno ancora scalo lì, sostenendo che hanno inflitto il colpo di grazia per il pacifico molo dell'isola.\"Così hanno bloccato un sacco di affari sull'isola\", ha detto.",
	"LighthouseDecomissionedParagraph5": "Talvolta il faro è l'unica cosa che permette ai piccoli mercantili di venire a negoziare con le imprese locali, è qualcosa di cui siamo tutti preoccupati. Che succederà quando qui spariranno tutte le imprese di importazione rimaste?",
	"LighthouseDecomissionedQuote": "\"Sono troppo pochi\" quelli che salpano qui per rappresentare un problema di sicurezza, sostiene la guardia costiera",
	"LostTitle": "Perduto",
	"LostParagraph1": "Sono passate due settimane da quando l'impiegato di Arque Antonio M. Buonadonna ha perduto il suo gatto nero “Kirthar”. Se qualcuno dovesse vederlo, è invitato a contattare il padrone immediatamente.",
	"ScarecrowCompetitionTitle": "Ha inizio la gara di spaventapasseri locale",
	"ScarecrowCompetitionParagraph1": "Una delle gare più popolari di Redton è tornata per l'appuntamento annuale.",
	"ScarecrowCompetitionParagraph2": "La comunità si riunisce ogni anno per realizzare gli spaventapasseri più spaventosi e mostruosi per tenere lontani gli uccelli. Il vincitore dell'anno scorso è stato un bambino di otto anni della scuola locale di nome Joshua Fenton, la cui rappresentazione di sua nonna ha conquistato il parere dei giudici.",
	"ScarecrowCompetitionParagraph3": "Quest'anno il vincitore della gara otterrà una succulenta scorta di torte di Julia Menn, la moglie del sindaco, che ha aperto recentemente la sua pasticceria sull'isola.",
	"ScarecrowCompetitionParagraph4": "I festeggiamenti non termineranno con gli spaventapasseri (che rimarranno esposti tutta la settimana), ci saranno bancarelle e altre attività sparse per tutto il paese. Se non avete ancora avuto la possibilità di ammirare i nostri spaventapasseri, partecipate all'evento annuale per goderveli appieno e provare alcune delle pietanze e delle bevande più gustose che Redton ha da offrire.",
	"ScarecrowCompetitionParagraph5": "Se non ce la doveste fare a vedere gli spaventapasseri, non perdetevi il prossimo numero, in cui vi mostreremo tutti quelli che hanno partecipato.",
	"OmnicorpTitle": "La Arque Corporation acquisisce la Phillips Pharmaceuticals",
	"OmnicorpParagraph1": "All'inizio della scorsa settimana, sono state consegnate trenta notifiche ad altrettanti lavoratori quando il gigante dell'industria Arque Corporation ha completato l'acquisizione dell'impresa farmaceutica locale Phillips Pharmaceuticals. L'acquisizione è avvenuta in seguito al pubblico collasso del proprietario precedente, seguito dalla ricerca di nuovi investitori.",
});