ae.addLanguage("japanese", {
	"GameTitle": "Estranged",
	"GameSubtitle": "Act I",
	"Language": "japanese",
	"Close": "閉じる",
	"CreditsWithThanksTo": "With thanks to",
	"CreditsTeam": "Team",
	"CreditsMainMenu": "メインメニューへ",
	"CreditsCreator": "Creator",
	"CreditsVoices": "Voices",
	"CreditsPreviousVoices": "Previous Voices",
	"CreditsTranslators": "Translators",
	"CreditsTesters": "Testers",
	"CreditsMacOSBuild": "Mac OS Version",
	"CreditsDanishTranslator": "Danish Translator",
	"CreditsMapCompiler": "Map Compiler",
	"CreditsTranslator": "Translator",
	"CreditsTester": "Tester",
	"CreditsPhotographer": "Photographer",
	"CreditsGuitarSamples": "Guitar Samples",
	"CreditsProjectLead": "Project Lead",
	"CreditsLevelDesigner": "Level Designer",
	"CreditsProgrammer": "Programmer",
	"CreditsStoryDesigner": "Story Designer",
	"CreditsTextureArtist": "Texture Artist",
	"CreditsModelArtist": "3D Model Artist",
	"CreditsVoiceOf": "Voice of",
	"CreditsLeadMusician": "Lead Musician",
	"CreditsShaderArtist": "Shader Artist",
	"CreditsOmnicorpThug": "Arque Thug",
	"CreditsOmnicorpBroadcaster": "Arque Broadcaster",
	"CreditsMirrorHosting": "Download Mirror Hosting",
	"CreditsAudioDesigner": "Audio Designer",
	"CreditsOculusRift": "Donated Oculus Rift",
	"CreditsDonors": "Project Donors",
	"CreditsSteamTranslation": "The Steam Translation Server",
	"Workstation": "ワークステーション",
	"EndSession": "セッションを終了しますか？",
	"OK": "OK",
	"Cancel": "キャンセル",
	"IconEmail": "メール",
	"IconLogOff": "ログオフ",
	"IconDoorUnlock": "ドアの解錠",
	"OnlyPrintIfNecessary": "自然を守ろう。このメールは必要なときだけ印刷してください。",
	"Incorrect": "申し訳ございませんが、誤りがあります。",
	"SecretPetName": "alex",
	"DialogGenerator": "発電機コンソール",
	"DialogGeneratorOverHeat": "警告: 発電機がオーバーヒートしています",
	"DialogGeneratorDisconnect": "発電機のコンソールからログアウトします",
	"YantoWardName": "イエント・ウォード",
	"YantoWardAccount": "イエント・ウォード < yanto.ward@arque.local >",
	"Pets_R_Us_Update": "Pets Are Us からのお知らせ",
	"Pets_R_Us_UpdateSummary": "ウォードさん、Alex は回復しました...",
	"Pets_R_Us_From": "Pets Are Us < judy@petsrus.com >",
	"Pets_R_Us_Line1": "ウォードさん、",
	"Pets_R_Us_Line2": "あなたの愛犬Alexは回復しつつあります。投与した薬にも良好な反応を見せました。",
	"Pets_R_Us_Line3": "月曜日にはAlexをつれて帰ることが出来るでしょう。",
	"Pets_R_Us_Line4": "では、",
	"Pets_R_Us_Line5": "ジュディ・フェラン。",
	"WhatIsThatSmell": "何の臭いだ",
	"Srsly": "まじめに",
	"NigelHeathcoat": "ナイジェル・ヒースコート < nigel@arque.local >",
	"HaveYouSeenMyLunch": "俺の昼食を見てないか？",
	"HaveYouSeenMyLunchSummary": "なあ 俺の昼食を...",
	"FrancisRobella": "フランシス・ロベッラ < francis@arque.local >",
	"FrancisRobellaLine1": "なぁ、",
	"FrancisRobellaLine2": "俺の昼食を見てないか？冷蔵庫に入れたはずなのに無くなってるんだ。もしあの女がまた盗んだってならきつく言ってやろう。あいつはいつも俺の物を盗むんだ！",
	"FrancisRobellaLine3": "フランシス",
	"PleaseEnterSecretAnswer": "続行するには秘密の質問に答えてください:",
	"NameOfPet": "あなたのペットの名前は何ですか？",
	"UnlockAllDoorsPrompt": "黄色いフロアのドアを全て解錠するには下のボタンを押してください。",
	"UnlockAllDoors": "全ドアのロックを解除",
	"DoorsAreUnlocked": "黄色のフロアのドアは現在全て解錠されています。",
	"Image1": "IMG_0270_104942.JPEG",
	"Image2": "IMG_0430_104912.JPEG",
	"Image3": "IMG_0430_104944.JPEG",
	"Image4": "IMG_0470_104454.JPEG",
	"Image5": "IMG_0437_104954.JPEG",
	"Image6": "IMG_0440_104964.JPEG",
	"Image7": "IMG_0437_104964.JPEG",
	"Image8": "IMG_034324_432432.MP4",
	"ChristianPlitheName": "クリスチャン プライズ",
	"ChristianPlitheAccount": "クリスチャン プライズ < christian.plithe@arque.local >",
	"LunchRoomTitle": "食堂",
	"LunchRoomSummary": "クリスティアン、やめられません...",
	"LunchRoomLine1": "クリスチャン、あなたの事しか考えられない。あなたを初めて食堂で見たとき、あなたしかいないと感じました。脂っこい手羽先をゆっくり唇にこすりつけ ---------- あなたはとてもたくましい人ですね。明日も同じ時間に会えることを期待しています。私は見つめていますから……",
	"AdmirerName": "あなたを慕う者",
	"AdmirerAccount": "慕う者 < anonymous@arque.local >",
	"WilliamShortAccount": "ウィリアム・ショート < william.short@arque.local >",
	"WilliamShortSig": "ウィリアム・ショート ライン管理者",
	"WilliamShortTitle": "RE: ハラスメント",
	"WilliamShortSummary": "クリスチャン、人事にこの件は報告した...",
	"WilliamShortLine1": "やあ、クリスチャン",
	"WilliamShortLine2": "このことは人事課とインターナルサポートに報告しておいた。彼らが\"求愛者\"を見つけ出そうとしてくれているよ。",
	"WilliamShortLine3": "なに、どうせ全てただの冗談だろうさ...",
	"ChrisLine1": "やあ ウィル",
	"ChrisLine2": "僕を\"慕ってる\"とかいう奴からかなり変なメールが立て続けに送られてくるんだ。どれも anonymous@arque.local からね。",
	"ChrisLine3": "一つ引用しておこうか。",
	"ChrisLine4": "最近君といざこざがあったことは承知してるが、今は助けが必要なんだ... 最初は何だか良く分からなかったが今は本当に恐ろしい気分だよ。このことは公的な問題ということで手を貸してくれないか？",
	"ChrisLine5": "クリスチャン",
	"MeetMeTitle": "どうして私の前に姿を見せないのですか？",
	"MeetMeSummary": "今日は食堂に私一人...",
	"MeetMeLine1": "今日は食堂に私一人っきりでした。あなたが食事するのを見たかったのにあなたは来なかった！私の事を気味悪がってるの？",
	"MeetMeLine2": "私は決してそういう者ではありませんよ。明日こそ会えませんか。待っています。",
	"HandledTheManagerTitle": "あなたが管理者を怒鳴るのを見ました",
	"HandledTheManagerSummary": "本当に気に入りました...",
	"HandledTheManagerLine1": "今日あなたが管理者を怒鳴っているのを見て、本当に気に入りました。怒ると獣のようになるのですね。汗が二重顎を滴り落ちるところも好きですよ... どこか堪らないのです。",
	"JonathanBillyName": "ジョナサン・ビリー",
	"JonathanBillyAccount": "ジョナサン・ビリー < jonathan.billy@arque.local >",
	"JonathanBillyLine1": "金曜にシフト入ってる？",
	"JonathanBillyLine2": "娘が水泳大会に出るんだが女房が俺に見に行けってうるさくてね。だから俺のシフト代わりに入ってくれないか",
	"JonathanBillyLine3": "よろしく",
	"JonathanBillyLine4": "ジョナより",
	"DavidGravenName": "デイビット・グレイブン",
	"DavidGravenAccount": "デイビッド・グレイブン < david.graven@arque.local >",
	"DavidGravenTitle1": "Re: 金曜日",
	"DavidGravenTitle2": "積荷",
	"DavidGravenSummary1": "ああ大丈夫だよ。楽しんできな :)",
	"DavidGravenSummary2": "あの積荷の一部を移動できないか",
	"DavidGravenEmail1": "ジョナ、",
	"DavidGravenEmail2": "あの積荷をいくつか西アークの倉庫へ移動できないかな？今度また送られてくるらしいんだが、供給品のでかい木箱やら何やらもあってこれ以上は置けないんだ。俺の方からジェフに相談しようと思う... いずれにせよ一部は上の階へ移すしかないと思うんだが。",
	"DavidGravenSig": "デイブ",
	"JonathanBillyTitle": "金曜日",
	"JeffHerbandTitle": "配送中...",
	"JeffHerbandSummary": "追加の箱が配送中です",
	"JeffHerbandAccount": "ジェフ・ハーバンド < jeff.herband@arque.local >",
	"JeffHerbandName": "ジェフ・ハーバンド",
	"JeffHerbandSig": "西アーク, 倉庫管理者",
	"JeffHerbandLine1": "箱が追加でそちらへ配送されています。箱の保管にだけは気を付けてください。決して中身を壊さないように。",
	"WentworthHeraldTitle": "ウェントワース・ヘラルド",
	"WentworthHeraldTagline": "ニュースにゴシップ、スポーツ、芸能、ビジネス、クロスワードを素早くお届け。これぞ新聞、そしてあなたの生活へ。",
	"MoreOnPage7": "7 ページに詳細",
	"MoreOnPage10": "10 ページに詳細",
	"LighthouseDecomissionedTitle": "灯台　廃灯へ",
	"LighthouseDecomissionedParagraph1": "沿岸警備隊による調査の結果、Redton の岬に建造された灯台は市長ジョン・メンの命により廃灯することが決定された。",
	"LighthouseDecomissionedParagraph2": "「この決定が付近の交通に影響を与えることは絶対にありません。」海運調査課のビル・ハイエクは言う。「かつては Redton 沿岸を発つ貨物船を見たものですが、本土からの航路が変更された今はそれも無いのです。」",
	"LighthouseDecomissionedParagraph3": "市長は、灯台の閉鎖について公式な声明を出すまではコメントを控えるとのことである。",
	"LighthouseDecomissionedParagraph4": "地元住民はこの変化を良く思っていない。1人の地元住民は、この島を今も行き来する小型の交易船に影響を与えることを懸念している。今回の決定が今ですら人けの少ない島の港に止めを刺した、とのことだ。「島のビジネスの多くが停滞するだろう」と彼は言う。",
	"LighthouseDecomissionedParagraph5": "そうした小型船はこの灯台だけを頼りにこの地の会社と交易へ来ていたと言っても過言でない。そして人々の不安はそこなのだ。すなわち輸入業が全て消滅した時一体どうなるのか、ということである。",
	"LighthouseDecomissionedQuote": "沿岸警備隊曰く、船の交通量は非常に少なく安全性を考慮するに至らない",
	"LostTitle": "迷子",
	"LostParagraph1": "アーク社員であるクリスチャン・プライスの黒猫「ラッキー」の失踪以来2週間が経過しました。猫を目撃した方は彼にすぐに連絡を入れてほしいとのことです。",
	"ScarecrowCompetitionTitle": "ご当地名物カカシ品評会　開催中",
	"ScarecrowCompetitionParagraph1": "毎年恒例、Redton で最も人気の品評会が再び開催される。",
	"ScarecrowCompetitionParagraph2": "最も恐ろしくおぞましい鳥除けのカカシを作るべく、毎年地域が一体となる。昨年度は地元の小学生である8歳のジョシュア・フェントンが、自身の祖母を表現したというカカシにより審査員の評価を勝ち取り優勝した。",
	"ScarecrowCompetitionParagraph3": "今年の勝者はジュリア・メンから厳選されたケーキを贈られる。彼女は市長の妻であり、最近島に自分のケーキ屋をオープンしたのだ。",
	"ScarecrowCompetitionParagraph4": "祭はカカシだけに留まらない。カカシなどいつでも見られるのだということで最近は失速気味で、他のイベントが町のあちこちで開催されるようになっている。だがまだカカシを見たことがないというなら、この毎年恒例のイベントで喧騒を見てみるのも良い。Redton が誇る最高の食べ物飲み物を試食するのもお忘れなく。",
	"ScarecrowCompetitionParagraph5": "もしカカシを見に行く暇がないなら、次号は要チェックだ。全参加者のカカシを特集する予定である。",
	"OmnicorpTitle": "アーク・コーポレーション　フィリップス製薬を買収",
	"OmnicorpParagraph1": "アーク・コーポレーションが地元の製薬会社フィリップス製薬を買収した結果、先週初め30人の労働者に解雇通知が渡されることとなった。この買収は以前の経営者が破産を公表した後、投資家の援助を求めたことによる。",
});