ae.addLanguage("finnish", {
	"GameTitle": "Estranged",
	"GameSubtitle": "Act I",
	"Language": "finnish",
	"Close": "Sulje",
	"CreditsWithThanksTo": "Kiitokset seuraaville henkilöille:",
	"CreditsTeam": "Tiimi",
	"CreditsMainMenu": "Palaa päävalikkoon",
	"CreditsCreator": "Kehittäjä",
	"CreditsVoices": "Ääninäyttely",
	"CreditsPreviousVoices": "Aiempi ääninäyttely",
	"CreditsTranslators": "Kääntäjät",
	"CreditsTesters": "Testaajat",
	"CreditsMacOSBuild": "Mac OS -versio",
	"CreditsDanishTranslator": "Tanskan kääntäjä",
	"CreditsMapCompiler": "Kartan muuntaja",
	"CreditsTranslator": "Kääntäjä",
	"CreditsTester": "Testaaja",
	"CreditsPhotographer": "Valokuvaaja",
	"CreditsGuitarSamples": "Kitararaidat",
	"CreditsProjectLead": "Projektin johtaja",
	"CreditsLevelDesigner": "Karttasuunnittelija",
	"CreditsProgrammer": "Ohjelmoija",
	"CreditsStoryDesigner": "Tarinankirjoittaja",
	"CreditsTextureArtist": "Tekstuuriartisti",
	"CreditsModelArtist": "3D-mallintaja",
	"CreditsVoiceOf": "Ääninäytteli hahmoa",
	"CreditsLeadMusician": "Johtava muusikko",
	"CreditsShaderArtist": "Shader-taiteilija",
	"CreditsOmnicorpThug": "Arquen roisto",
	"CreditsOmnicorpBroadcaster": "Arquen kuuluttaja",
	"CreditsMirrorHosting": "Vaihtoehtoisen lataussivun ylläpitäminen",
	"CreditsAudioDesigner": "Äänisuunnittelija",
	"CreditsOculusRift": "Lahjoitti Oculus Riftin",
	"CreditsDonors": "Lahjoittajat",
	"CreditsSteamTranslation": "The Steam Translation Server",
	"Workstation": "Työasema",
	"EndSession": "Päätä istunto?",
	"OK": "OK",
	"Cancel": "Peruuta",
	"IconEmail": "Sähköposti",
	"IconLogOff": "Kirjaudu ulos",
	"IconDoorUnlock": "Oven avaus",
	"OnlyPrintIfNecessary": "Säästä luontoa. Älä tulosta tätä sähköpostia turhaan.",
	"Incorrect": "Jokin meni pieleen.",
	"SecretPetName": "alex",
	"DialogGenerator": "Generaattorin konsoli",
	"DialogGeneratorOverHeat": "VAROITUS: GENERAATTORI YLIKUUMENEE",
	"DialogGeneratorDisconnect": "KIRJAUDU ULOS GENERAATTORIN KONSOLISTA",
	"YantoWardName": "Yanto Ward",
	"YantoWardAccount": "Yanto Ward < yanto.ward@arque.local >",
	"Pets_R_Us_Update": "Pets Are Us -päivitys",
	"Pets_R_Us_UpdateSummary": "Herra Ward, Alex on toipunut...",
	"Pets_R_Us_From": "Pets Are Us < judy@petsrus.com >",
	"Pets_R_Us_Line1": "Herra Ward,",
	"Pets_R_Us_Line2": "Koiranne Alex toipuu hyvin ja antamamme lääkkeet näyttävät tehoavan.",
	"Pets_R_Us_Line3": "Voitte hakea Alexin maanantaina.",
	"Pets_R_Us_Line4": "Terveisin",
	"Pets_R_Us_Line5": "Judy Ferrand.",
	"WhatIsThatSmell": "MIKÄ ON TUO HAJU",
	"Srsly": "siis oikeesti",
	"NigelHeathcoat": "Nigel Heathcoat < nigel@arque.local >",
	"HaveYouSeenMyLunch": "Oletko nähnyt lounastani?",
	"HaveYouSeenMyLunchSummary": "Hei, Oletko nähnyt...",
	"FrancisRobella": "Francis Robella < francis@arque.local >",
	"FrancisRobellaLine1": "Hei,",
	"FrancisRobellaLine2": "Oletko nähnyt lounastani? Jätin sen jääkaappiin ja nyt se on kadonnut. Kilahdan jos hän on taas varastanut sen. Hän vie aina omaisuuttani!",
	"FrancisRobellaLine3": "Francis",
	"PleaseEnterSecretAnswer": "Jatka vastaamalla turvakysymykseen:",
	"NameOfPet": "Mikä on lemmikkisi nimi?",
	"UnlockAllDoorsPrompt": "Käytä alla olevaa nappia avataksesi kaikki keltaisen kerroksen ovet.",
	"UnlockAllDoors": "Avaa kaikki ovet",
	"DoorsAreUnlocked": "Kaikki keltaisen kerroksen ovet ovat tällä hetkellä auki.",
	"Image1": "IMG_0270_104942.JPEG",
	"Image2": "IMG_0430_104912.JPEG",
	"Image3": "IMG_0430_104944.JPEG",
	"Image4": "IMG_0470_104454.JPEG",
	"Image5": "IMG_0437_104954.JPEG",
	"Image6": "IMG_0440_104964.JPEG",
	"Image7": "IMG_0437_104964.JPEG",
	"Image8": "IMG_034324_432432.MP4",
	"ChristianPlitheName": "Christian Plithe",
	"ChristianPlitheAccount": "Christian Plithe < christian.plithe@arque.local >",
	"LunchRoomTitle": "Ruokala",
	"LunchRoomSummary": "Christian, en malta...",
	"LunchRoomLine1": "Christian, en malta lakata ajattelemasta sinua. Siitä hetkestä, kun kohtasin sinut ruokasalissa, tiesin, että olet se oikea. Kun rasvaiset kanansiivet hankasivat hitaasti huuliasi vasten ---------- tajusin, että olet todella voimakas mies. Toivottavasti näen sinut taas samaan aikaan huomenna. Minä tarkkailen sinua...",
	"AdmirerName": "Ihailijasi",
	"AdmirerAccount": "Ihailija < anonymous@arque.local >",
	"WilliamShortAccount": "William Short < william.short@arque.local >",
	"WilliamShortSig": "William Short, tuotantopäällikkö.",
	"WilliamShortTitle": "RE: Häirintä",
	"WilliamShortSummary": "Christian, ilmoitin tästä henkilöstöosastolle...",
	"WilliamShortLine1": "Hei Christian,",
	"WilliamShortLine2": "ilmoitin tästä henkilöstöosastolle ja sisäiseen tukeen. He yrittävät parhaansa mukaan jäljittää tämän mysteerisen \"ihailijan\".",
	"WilliamShortLine3": "Täytyy myöntää, että tämä touhu on kyllä naurettavaa...",
	"ChrisLine1": "Hei Will,",
	"ChrisLine2": "saan yhä näitä outoja sähköposteja \"ihailijaltani\", jonka lähetysosoitteena toimii myös anonymous@arque.local",
	"ChrisLine3": "Tässä näyte yhdestä viestistä:",
	"ChrisLine4": "Ymmärrän, että meillä oli erimielisyytemme, mutta tarvitsen apua tämän kanssa... aluksi se oli outoa, mutta nyt se suorastaan pelottaa. Voisiko tämän luokitella virallisesti valitukseksi?",
	"ChrisLine5": "Christian",
	"MeetMeTitle": "Miksi et tullut tapaamaan minua?",
	"MeetMeSummary": "Olin aivan yksin...",
	"MeetMeLine1": "Olin aivan yksin ruokasalissa. Halusin katsoa syömistäsi, mutta et tullutkaan! Pelotinko minä sinut tiehesi?",
	"MeetMeLine2": "Lupaan, etten ole oikeasti sellainen. Yritetään huomenna uudelleen. Minä odotan.",
	"HandledTheManagerTitle": "Näin, kuinka käsittelit pomoasi",
	"HandledTheManagerSummary": "Minä todellakin pidin...",
	"HandledTheManagerLine1": "Minä todellakin pidin tavastasi, miten käsittelit pomoasi tänään. Olet oikea villipeto ollessasi vihainen. Se tapa, jolla hiki valui kaksoisleualtasi pois... se sai sukat jaloissani pyörimään.",
	"JonathanBillyName": "Jonathan Billy",
	"JonathanBillyAccount": "Jonathan Billy < jonathan.billy@arque.local >",
	"JonathanBillyLine1": "onks sul vuoroo perjantain",
	"JonathanBillyLine2": "mun tytöl on uimakilipailu ja akka käskee kattomaan. hoidatko mun vuoron",
	"JonathanBillyLine3": "kiitti",
	"JonathanBillyLine4": "jontulta",
	"DavidGravenName": "David Graven",
	"DavidGravenAccount": "David Graven < david.graven@arque.local >",
	"DavidGravenTitle1": "RE: perjantai",
	"DavidGravenTitle2": "Laatikot",
	"DavidGravenSummary1": "Sopii hyvin, nauti päivästäsi :)",
	"DavidGravenSummary2": "Voisiko joitain näistä laatikoista",
	"DavidGravenEmail1": "Jonttu,",
	"DavidGravenEmail2": "voisiko joitain näistä laatikoista siirtää Arque Eastin varastoon? Lisää olisi kuulemma vielä tulossa, mutta ei ne millään mahdu tänne - varsinkaan noiden isojen tarvikelaatikkojen kanssa. Puhun Jeffille asiasa... heidän olisi tarkoitus ottaa osa yläkertaan jossain vaiheessa.Can we shift some of the boxes to the warehouse at Arque East? They say there are more to come but we can't fit many more in here - what with the large supply crates too. I'll speak to Jeff about it... they're meant to be taking some upstairs at some point.",
	"DavidGravenSig": "Dave",
	"JonathanBillyTitle": "perjantai",
	"JeffHerbandTitle": "Tulossa...",
	"JeffHerbandSummary": "Laatikoita on tulossa lisää",
	"JeffHerbandAccount": "Jeff Herband < jeff.herband@arque.local >",
	"JeffHerbandName": "Jeff Herband",
	"JeffHerbandSig": "Arque West, varastonhoitaja",
	"JeffHerbandLine1": "Laatikoita on tulossa lisää. Pitäkää niistä huolta, emmehän halua näiden hajoavan.",
	"WentworthHeraldTitle": "Wentworthin vilinä",
	"WentworthHeraldTagline": "Uutisten, juorujen, urheilun, showmaailman, kaupan ja ristikoiden ykköslehti. Sinun lehtesi, sinun elämäsi.",
	"MoreOnPage7": "Lisää sivulla 7",
	"MoreOnPage10": "Lisää sivulla 10",
	"LighthouseDecomissionedTitle": "Majakka poistettu käytöstä",
	"LighthouseDecomissionedParagraph1": "Redtonin rajamailla sijaitseva majakka on määrätty purettavaksi pormestari John Mennin toimesta, josta seuraa merivartioston tutkinta.",
	"LighthouseDecomissionedParagraph2": "\"Olemme varmoja, että tämä ei tule vaikuttamaan ohimenevää liikennettä\", kommentoi Bill Hayak meriliikenteen tutkivalta osastolta. \"Ennen saattoi nähdä rahtilaivoja Redtonin tuntumassa, mutta nykyään kyseinen ei tule tapahtumaan sisämaan toimituslinjojen muutoksien vuoksi\", hän lisää.",
	"LighthouseDecomissionedParagraph3": "Kysyttäessä pormestari kieltäytyi kommentoimasta majakan sulkemisesta ennen virallisen lausuntonsa julkaisua.",
	"LighthouseDecomissionedParagraph4": "Alueen asukkaat eivät ole tyytyväisiä päätökseen; eräs haastateltu kyläläinen on huolissaan muutoksen vaikutuksista kauppalaivojen liikenteeseen, pistäen hiljaisen sataman pois toiminnasta. \"Se seisauttaa paljon saaren toiminnasta\", hän lisää.",
	"LighthouseDecomissionedParagraph5": "Joskus pienemmät laivat pääsevät pelkästään majakan avulla satamaan käymään kauppaa täkäläisten kanssa, joten se on jotain, josta me kaikki olemme huolissamme - mitä tapahtuu, kun tuontiliikente lakkaa?",
	"LighthouseDecomissionedQuote": "Ei turvallisuusriski näin \"vähäiselle liikenteelle\", sanoo merivartija",
	"LostTitle": "Kadonnut",
	"LostParagraph1": "Arquen työntekijän Christian Plithen kissa 'Onnenpekka' karkasi kaksi viikkoa sitten. Hän on pyytänyt ilmoittamaan, jos kukaan sattuu näkemään sitä.",
	"ScarecrowCompetitionTitle": "Paikkakunnan variksenpelätinkisa menossa",
	"ScarecrowCompetitionParagraph1": "Eräs suositummista Redtonissa pidettävistä kisoista on takaisin vuosittaisena ajankohtanaan.",
	"ScarecrowCompetitionParagraph2": "Yhteisö kokoontuu vuosittain luodakseen kaikkein kammottavimmat ja aavemaisimmat variksenpelättimet lintujen karkottamiseksi. Edellisen vuoden voittaja oli kahdeksanvuorias täkäläinen koulupoika Joshua Fenton, jonka tulkinta omasta isoäidistään voitti tuomariston puolelleen.",
	"ScarecrowCompetitionParagraph3": "Tänä vuonna voittaja palkitaan Julia Mennin, pormestarin vaimon, valmistamilla upeilla kakuilla. Hän avasi hiljattain saarella oman leipomonsa.",
	"ScarecrowCompetitionParagraph4": "Juhlinta ei kuitenkaan rajoitu näytillä oleviin variksenpelättimiin! Kaupunki on täynnä erilaisia kojuja ja monenlaista tekemistä. Jos et ole vielä nähnyt variksenpelättimiä, käy toki piipahtamassa ja maista samalla Redtonin parhaita ruokia ja juomia.",
	"ScarecrowCompetitionParagraph5": "Jos et pääse paikan päälle katsomaan variksenpelättimiä, osta seuraava numeromme josta löytyy koko tapahtuman kattava reportaasi.",
	"OmnicorpTitle": "Arque Corporation ostaa Phillips Pharmaceuticalin",
	"OmnicorpParagraph1": "Viime viikon alussa 30 työntekijälle ilmoitettiin, että Arque Corporation osti lääkevalmistaja Phillips Pharmaceuticalsin. Hankintaan johti edellisen omistajan hermoromahdus, jonka seurauksena yritykselle etsittiin sijoittajia.",
});