ae.addLanguage("czech", {
	"GameTitle": "Estranged",
	"GameSubtitle": "Act I",
	"Language": "czech",
	"Close": "Zavřít",
	"CreditsWithThanksTo": "Poděkování",
	"CreditsTeam": "Tým",
	"CreditsMainMenu": "Přejít do hlavní nabídky",
	"CreditsCreator": "Tvůrce",
	"CreditsVoices": "Dabing",
	"CreditsPreviousVoices": "Předchozí dabéři",
	"CreditsTranslators": "Překladatelé",
	"CreditsTesters": "Testeři",
	"CreditsMacOSBuild": "Verze pro Mac OS",
	"CreditsDanishTranslator": "Překladatel do dánštiny",
	"CreditsMapCompiler": "Kompilátor map",
	"CreditsTranslator": "Překladatel",
	"CreditsTester": "Tester",
	"CreditsPhotographer": "Fotograf",
	"CreditsGuitarSamples": "Kytarové melodie",
	"CreditsProjectLead": "Vedoucí projektu",
	"CreditsLevelDesigner": "Návrhář úrovní",
	"CreditsProgrammer": "Programátor",
	"CreditsStoryDesigner": "Autor příběhu",
	"CreditsTextureArtist": "Tvůrce textur",
	"CreditsModelArtist": "Tvůrce 3D modelů",
	"CreditsVoiceOf": "Hlas",
	"CreditsLeadMusician": "Hlavní skladatel",
	"CreditsShaderArtist": "Grafik shaderů",
	"CreditsOmnicorpThug": "Zločinec",
	"CreditsOmnicorpBroadcaster": "Hlasatelka",
	"CreditsMirrorHosting": "Hosting pro stahování",
	"CreditsAudioDesigner": "Návrhář zvuků",
	"CreditsOculusRift": "Poskytnul Oculus Rift",
	"CreditsDonors": "Přispěvatelé do projektu",
	"CreditsSteamTranslation": "Překladatelský server služby Steam",
	"Workstation": "Pracovní stanice",
	"EndSession": "Opravdu chcete ukončit tuto relaci?",
	"OK": "OK",
	"Cancel": "Zrušit",
	"IconEmail": "E-mail",
	"IconLogOff": "Odhlásit se",
	"IconDoorUnlock": "Odemčení dveří",
	"OnlyPrintIfNecessary": "Chraňte životní prostředí. Tento e-mail si vytiskněte pouze, pokud je to opravdu nezbytné.",
	"Incorrect": "Nesprávná odpověď",
	"SecretPetName": "alex",
	"DialogGenerator": "Ovládání generátoru",
	"DialogGeneratorOverHeat": "VAROVÁNÍ: GENERÁTOR SE PŘEHŘÍVÁ",
	"DialogGeneratorDisconnect": "ODHLÁSIT SE Z OVLÁDÁNÍ GENERÁTORU",
	"YantoWardName": "Yanto Ward",
	"YantoWardAccount": "Yanto Ward < yanto.ward@arque.local >",
	"Pets_R_Us_Update": "Zpráva ze Zvířecí pohotovosti",
	"Pets_R_Us_UpdateSummary": "Pane Warde, Alex se zotavuje…",
	"Pets_R_Us_From": "Zvířecí pohotovost < judy@petsrus.com >",
	"Pets_R_Us_Line1": "Pane Warde,",
	"Pets_R_Us_Line2": "Váš pes Alex se zotavuje a na podávanou léčbu reaguje velmi pozitivně.",
	"Pets_R_Us_Line3": "Budete si ho moci odvést v pondělí.",
	"Pets_R_Us_Line4": "Děkuji,",
	"Pets_R_Us_Line5": "Judy Ferrandová.",
	"WhatIsThatSmell": "CO TO TADY SMRDÍ",
	"Srsly": "jako vážně",
	"NigelHeathcoat": "Nigel Heathcoat < nigel@arque.local >",
	"HaveYouSeenMyLunch": "Neviděl jsi můj oběd?",
	"HaveYouSeenMyLunchSummary": "Ahoj, neviděl jsi můj…",
	"FrancisRobella": "Francis Robella < francis@arque.local >",
	"FrancisRobellaLine1": "Ahoj,",
	"FrancisRobellaLine2": "neviděl jsi můj oběd? Nechal jsem ho v lednici a je pryč. Jestli mi ho zase ukradla, tak už se naštvu. Pořád mi krade věci!",
	"FrancisRobellaLine3": "Francis",
	"PleaseEnterSecretAnswer": "Pro pokračování prosím odpovězte na tajnou otázku:",
	"NameOfPet": "Jak se jmenuje Váš domácí mazlíček?",
	"UnlockAllDoorsPrompt": "K odemčení všech dveří na žlutém podlaží použijte tlačítko níže.",
	"UnlockAllDoors": "Odemknout všechny dveře",
	"DoorsAreUnlocked": "Všechny dveře na žlutém podlaží jsou nyní odemčeny.",
	"Image1": "IMG_0270_104942.JPEG",
	"Image2": "IMG_0430_104912.JPEG",
	"Image3": "IMG_0430_104944.JPEG",
	"Image4": "IMG_0470_104454.JPEG",
	"Image5": "IMG_0437_104954.JPEG",
	"Image6": "IMG_0440_104964.JPEG",
	"Image7": "IMG_0437_104964.JPEG",
	"Image8": "IMG_034324_432432.MP4",
	"ChristianPlitheName": "Christian Plithe",
	"ChristianPlitheAccount": "Christian Plithe < christian.plithe@arque.local >",
	"LunchRoomTitle": "Jídelna",
	"LunchRoomSummary": "Christiane, nemůžu přestat…",
	"LunchRoomLine1": "Christiane, nemůžu na tebe přestat myslet. Od té chvíle, co jsem tě poprvé viděla v jídelně, mi bylo jasné, že ty jsi ten pravý. Když se ta mastná kuřecí křidélka dotýkala tvých rtů... jsi opravdu mocný muž. Doufám, že tě tam zítra zase potkám. Budu se dívat…",
	"AdmirerName": "Tvá ctitelka",
	"AdmirerAccount": "Ctitelka < anonymous@arque.local >",
	"WilliamShortAccount": "William Short < william.short@arque.local >",
	"WilliamShortSig": "William Short, manažer oddělení",
	"WilliamShortTitle": "RE: Obtěžování",
	"WilliamShortSummary": "Christiane, ohlásil jsem to na oddělení...",
	"WilliamShortLine1": "Ahoj Christiane,",
	"WilliamShortLine2": "ohlásil jsem to na oddělení lidských zdrojů a vnitřních záležitostí. Pokusí se tu tvou „ctitelku“ vystopovat.",
	"WilliamShortLine3": "Musíš ale uznat, že celá tahle věc je srandovní…",
	"ChrisLine1": "Ahoj Wille,",
	"ChrisLine2": "stále dostávám tyhle podivné e-maily z adresy anonymous@arque.local od někoho, kdo se nazývá mou „ctitelkou“.",
	"ChrisLine3": "Tady je příklad:",
	"ChrisLine4": "Vím, že jsme mezi sebou v poslední době měli nějaké neshody, ale s tímhle bych opravdu potřeboval pomoc… Ze začátku to bylo jen divné, ale teď už to začíná být i děsivé. Můžeš to prosím brát jako oficiální stížnost?",
	"ChrisLine5": "Christian",
	"MeetMeTitle": "Proč jsi nepřišel?",
	"MeetMeSummary": "Seděla jsem sama v...",
	"MeetMeLine1": "Seděla jsem sama v jídelně a těšila jsem se, jak tě budu sledovat při jezení. Ale ty jsi nepřišel! Děsím tě snad?",
	"MeetMeLine2": "Přísahám, že se nemáš čeho bát! Hele – co to zítra zkusit znovu? Budu čekat.",
	"HandledTheManagerTitle": "Viděla jsem, jak ses vypořádal s tím manažerem",
	"HandledTheManagerSummary": "Opravdu se mi líbilo...",
	"HandledTheManagerLine1": "Opravdu se mi líbilo, jak ses dnes vypořádal s tím manažerem. Jak ses dokázal naštvat a jak se z tebe stalo opravdové zvíře. Líbilo se mi, jak ti po tvé druhé bradě stékal pot… prostě mě to vzrušuje.",
	"JonathanBillyName": "Jonathan Billy",
	"JonathanBillyAccount": "Jonathan Billy < jonathan.billy@arque.local >",
	"JonathanBillyLine1": "jsi v patek v praci",
	"JonathanBillyLine2": "moje dcera ma soutez v plavani a zena me tam nuti jit. muzes to vzit za me",
	"JonathanBillyLine3": "diky",
	"JonathanBillyLine4": "jono",
	"DavidGravenName": "David Graven",
	"DavidGravenAccount": "David Graven < david.graven@arque.local >",
	"DavidGravenTitle1": "RE: patek",
	"DavidGravenTitle2": "Bedny",
	"DavidGravenSummary1": "Samozřejmě, užijte si to :)",
	"DavidGravenSummary2": "Nemohli bychom přesunout nějaké bedny",
	"DavidGravenEmail1": "Ahoj Jono,",
	"DavidGravenEmail2": "Nemohli bychom přesunout nějaké bedny do východního skladu Arque? Tvrdí, že mají dorazit další, ale sem už se nevejde ani moc těch malých – a co teprve ty velké dodávkové. Promluvím si o tom s Jeffem... Některé z těch krabic by si prý měli odnést nahoru.",
	"DavidGravenSig": "Dave",
	"JonathanBillyTitle": "patek",
	"JeffHerbandTitle": "Další bedny...",
	"JeffHerbandSummary": "Posíláme vám další bedny",
	"JeffHerbandAccount": "Jeff Herband < jeff.herband@arque.local >",
	"JeffHerbandName": "Jeff Herband",
	"JeffHerbandSig": "Arque západ – správce skladu",
	"JeffHerbandLine1": "Posíláme vám další bedny. Hlavně je nezapomeňte pořádně zabezpečit, za žádnou cenu se nesmí rozbít.",
	"WentworthHeraldTitle": "Wentworthské listy",
	"WentworthHeraldTagline": "Nejnovější drby, informace ze sportu, showbyznysu, financí a křížovky. Vaše noviny, Váš život.",
	"MoreOnPage7": "Více na straně 7",
	"MoreOnPage10": "Více na straně 10",
	"LighthouseDecomissionedTitle": "Maják vyřazen z provozu",
	"LighthouseDecomissionedParagraph1": "Místní starosta, John Menn, rozhodl na základě vyšetřování pobřežní hlídky o vyřazení majáku na Redtonském výběžku z provozu.",
	"LighthouseDecomissionedParagraph2": "„Jsme si jisti, že toto opatření nebude mít žádný dopad na námořní dopravu,“ říká Bill Hayak z vyšetřovacího týmu oddělení námořní dopravy. „Dopravní cesty z pevniny byly změněny, takže se k našemu pobřeží nebude přibližovat tolik nákladních lodí, jako tomu bylo doposud,“ dodává.",
	"LighthouseDecomissionedParagraph3": "Starosta odmítl celou záležitost komentovat, dokud nebude vydáno oficiální prohlášení o vyřazení majáku z provozu.",
	"LighthouseDecomissionedParagraph4": "Místním občanům se tato změna nelíbí a obávají se o malá obchodní plavidla, která na ostrově stále kotví. Většina z nich se také domnívá, že jde o poslední hřebíček do rakve již tak dost neprosperujícího doku. „Zastaví to mnoho našich obchodních aktivit,“ tvrdí jeden z nespokojených občanů.",
	"LighthouseDecomissionedParagraph5": "Maják může být jedinou věcí, která umožňuje malým plavidlům připlout na náš ostrov a obchodovat zde s místními živnostníky. A to je právě to, čeho se všichni nejvíc obáváme – ztráta veškerých obchodních příležitostí.",
	"LighthouseDecomissionedQuote": "Pobřežní hlídka: „Příliš málo“ lodí na to, aby se mohlo něco stát",
	"LostTitle": "Hledá se",
	"LostParagraph1": "Už jsou to dva týdny, co se ztratila černá kočka „Štístko“ zaměstnance společnosti Arque, Christiana Plitha. Ten prosí každého, kdo kočku spatří, aby ho okamžitě kontaktoval.",
	"ScarecrowCompetitionTitle": "Soutěž ve strašácích do zelí v plném proudu",
	"ScarecrowCompetitionParagraph1": "Jedna z nejpopulárnějších soutěží, které se na Redtonu pořádají, je opět tady.",
	"ScarecrowCompetitionParagraph2": "Obyvatelé ze všech koutů ostrova se každý rok pokoušejí vytvořit co nejstrašidelnějšího a nejmorbidnějšího strašáka do zelí k odhánění ptactva. Minulý rok se vítězem stal místní osmiletý chlapec, Joshua Fenton, jehož výtvor „Babička“ zvítězil u porotců na plné čáře.",
	"ScarecrowCompetitionParagraph3": "Letošní vítěz obdrží jeden z dortů, které ve svém nově otevřeném cukrářství upekla starostova manželka, Julia Mennová.",
	"ScarecrowCompetitionParagraph4": "Soutěž ale není jen o strašácích do zelí, kteří budou před radnicí vystaveni ještě týden. Po celém městě se odehrávají i další doprovodné akce. Takže pokud jste tento rok ještě neviděli žádného strašáka do zelí, běžte se podívat na tuto tradiční událost a ochutnejte to nejlepší jídlo a pití, které může Redton nabídnout.",
	"ScarecrowCompetitionParagraph5": "Pokud se ovšem této události nemůžete z jakéhokoli důvodu zúčastnit, nezapomeňte si koupit naše příští vydání, ve kterém vám přineseme kompletní reportáž.",
	"OmnicorpTitle": "Společnost Arque získává Phillips Pharmaceuticals",
	"OmnicorpParagraph1": "V důsledku převzetí místní farmaceutické firmy Phillips Pharmaceuticals gigantem Arque byl minulý týden rozvázán pracovní poměr s třiceti jejími zaměstnanci. Tato obří akvizice se uskutečnila po prohlášení konkurzu na jejího předchozího vlastníka.",
});