ae.addLanguage("polish", {
	"GameTitle": "Estranged",
	"GameSubtitle": "Act I",
	"Language": "polish",
	"Close": "Zamknij",
	"CreditsWithThanksTo": "Z podziękowaniami dla",
	"CreditsTeam": "Zespół",
	"CreditsMainMenu": "Wróć do głównego menu",
	"CreditsCreator": "Autor",
	"CreditsVoices": "Głosy",
	"CreditsPreviousVoices": "Poprzednie dialogi",
	"CreditsTranslators": "Tłumacze",
	"CreditsTesters": "Testerzy",
	"CreditsMacOSBuild": "Wersja na Mac OS",
	"CreditsDanishTranslator": "Duński tłumacz",
	"CreditsMapCompiler": "Kompilator map",
	"CreditsTranslator": "Tłumacz",
	"CreditsTester": "Tester",
	"CreditsPhotographer": "Fotograf",
	"CreditsGuitarSamples": "Sample gitarowe",
	"CreditsProjectLead": "Kierownik projektu",
	"CreditsLevelDesigner": "Projektant poziomów",
	"CreditsProgrammer": "Programista",
	"CreditsStoryDesigner": "Projektant fabuły",
	"CreditsTextureArtist": "Autor tekstur",
	"CreditsModelArtist": "Grafik 3D",
	"CreditsVoiceOf": "Głos",
	"CreditsLeadMusician": "Główny muzyk",
	"CreditsShaderArtist": "Artysta shaderów",
	"CreditsOmnicorpThug": "Zbir Arque",
	"CreditsOmnicorpBroadcaster": "Spiker Arque",
	"CreditsMirrorHosting": "Hosting alternatywnych źródeł pobierania",
	"CreditsAudioDesigner": "Projektant dźwięku",
	"CreditsOculusRift": "Ofiarodawca Oculus Rift",
	"CreditsDonors": "Sponsorzy projektu",
	"CreditsSteamTranslation": "Steam Translation Server",
	"Workstation": "Stacja robocza",
	"EndSession": "Zakończyć sesję?",
	"OK": "OK",
	"Cancel": "Anuluj",
	"IconEmail": "E-mail",
	"IconLogOff": "Wyloguj się",
	"IconDoorUnlock": "Odblokuj drzwi",
	"OnlyPrintIfNecessary": "Chroń środowisko. Wydrukuj tę wiadomość tylko, jeśli musisz.",
	"Incorrect": "Przepraszamy, było to niepoprawne.",
	"SecretPetName": "alex",
	"DialogGenerator": "Konsola generatora",
	"DialogGeneratorOverHeat": "UWAGA: PRZEGRZANIE GENERATORA",
	"DialogGeneratorDisconnect": "WYLOGUJ SIĘ Z KONSOLI GENERATORA",
	"YantoWardName": "Yanto Ward",
	"YantoWardAccount": "Yanto Ward < yanto.ward@arque.local >",
	"Pets_R_Us_Update": "Aktualizacja Pets Are Us",
	"Pets_R_Us_UpdateSummary": "Panie Ward, Alex wyzdrowiał...",
	"Pets_R_Us_From": "Pets Are Us < judy@petsrus.com >",
	"Pets_R_Us_Line1": "Panie Ward,",
	"Pets_R_Us_Line2": "Pański pies, Alex, dochodzi do siebie i bardzo dobrze reaguje na podawane mu leki.",
	"Pets_R_Us_Line3": "Będzie Pan mógł odebrać Alexa w poniedziałek.",
	"Pets_R_Us_Line4": "Podziękowania,",
	"Pets_R_Us_Line5": "Judy Ferrand.",
	"WhatIsThatSmell": "CO TO ZA SMRÓD",
	"Srsly": "serio",
	"NigelHeathcoat": "Nigel Heathcoat < nigel@arque.local >",
	"HaveYouSeenMyLunch": "Widziałeś mój lunch?",
	"HaveYouSeenMyLunchSummary": "Hej, widziałeś mój...",
	"FrancisRobella": "Francis Robella < francis@arque.local >",
	"FrancisRobellaLine1": "Hej,",
	"FrancisRobellaLine2": "Widzialeś mój lunch? Zostawiłem go w lodówce i zniknął. Jeśli ona znowu go ukradła, to nie ręczę za siebie. Ona zawsze kradnie moje rzeczy!",
	"FrancisRobellaLine3": "Francis",
	"PleaseEnterSecretAnswer": "Podaj odpowiedź na tajne pytanie, aby kontynuować:",
	"NameOfPet": "Jak wabi się twój zwierzak?",
	"UnlockAllDoorsPrompt": "Użyj przycisku poniżej, aby otworzyć wszystkie drzwi na żółtym piętrze.",
	"UnlockAllDoors": "Otwórz wszystkie drzwi",
	"DoorsAreUnlocked": "Wszystkie drzwi na żółtym piętrze są obecnie otwarte.",
	"Image1": "IMG_0270_104942.JPEG",
	"Image2": "IMG_0430_104912.JPEG",
	"Image3": "IMG_0430_104944.JPEG",
	"Image4": "IMG_0470_104454.JPEG",
	"Image5": "IMG_0437_104954.JPEG",
	"Image6": "IMG_0440_104964.JPEG",
	"Image7": "IMG_0437_104964.JPEG",
	"Image8": "IMG_034324_432432.MP4",
	"ChristianPlitheName": "Christian Plithe",
	"ChristianPlitheAccount": "Christian Plithe < christian.plithe@arque.local >",
	"LunchRoomTitle": "Stołówka",
	"LunchRoomSummary": "Christian, nie mogę przestać...",
	"LunchRoomLine1": "Christian, nie mogę przestać o tobie myśleć. Od pierwszej chwili, w której cię zobaczyłam na stołówce wiedziałam, że jesteś tym jedynym. Od śliskich skrzydełek kurczaka powoli ocierających twoje wargi ---------- jesteś bardzo wpływowym mężczyzną. Mam nadzieję zobaczyć cię tam jutro o tej samej porze. Będę się przyglądać...",
	"AdmirerName": "Twoja wielbicielka",
	"AdmirerAccount": "Wielbicielka < anonymous@arque.local >",
	"WilliamShortAccount": "William Short < william.short@arque.local >",
	"WilliamShortSig": "William Short, bezpośredni przełożony.",
	"WilliamShortTitle": "ODP: Nękanie",
	"WilliamShortSummary": "Christian, zgłosiłem sprawę do działu kadr...",
	"WilliamShortLine1": "Cześć, Christian",
	"WilliamShortLine2": "Zgłosiłem to do kadr i obsługi. Spróbują znaleźć tę „wielbicielkę”.",
	"WilliamShortLine3": "Muszę przyznać, że cała ta sprawa jest zabawna...",
	"ChrisLine1": "Cześć, Will",
	"ChrisLine2": "Wciąż dostaję te bardzo dziwne e-maile od kogoś określającego się mianem mojej „wielbicielki”. Przychodzą z adresu anonymous@arque.local.",
	"ChrisLine3": "Oto fragment jednego z nich:",
	"ChrisLine5": "Christian",
	"MeetMeTitle": "Dlaczego się ze mną nie spotkałeś?",
	"MeetMeSummary": "Byłam sama na...",
	"MeetMeLine1": "Byłam sama na stołówce i chciałam zobaczyć jak się posilasz, ale ty nie przyszedłeś! Odstraszam cię?",
	"MeetMeLine2": "Obiecuję, że nie jestem z tych. Proszę, spróbujmy jutro. Będę czekała.",
	"HandledTheManagerTitle": "Widziałam, w jaki sposób poradziłeś sobie z menedżerem",
	"HandledTheManagerSummary": "Spodobał mi się...",
	"HandledTheManagerLine1": "Naprawdę podobało mi się, jak poradziłeś sobie dzisiaj z tym managerem. Jesteś niesamowity, gdy się złościsz. Podobało mi się, jak pot spływał po twoim podwójnym podbródku... coś w tym po prostu jest.",
	"JonathanBillyName": "Jonathan Billy",
	"JonathanBillyAccount": "Jonathan Billy < jonathan.billy@arque.local >",
	"JonathanBillyLine1": "czy pracujesz w piatek",
	"JonathanBillyLine2": "moja curka ma zawody plywackie i zona mowi, ze musze na nie isc. mozesz wziac moja zmiane",
	"JonathanBillyLine3": "podziekowania",
	"JonathanBillyLine4": "od jono",
	"DavidGravenName": "David Graven",
	"DavidGravenAccount": "David Graven < david.graven@arque.local >",
	"DavidGravenTitle1": "RE: piatek",
	"DavidGravenTitle2": "Paczki",
	"DavidGravenSummary1": "W porządku, baw się dobrze :)",
	"DavidGravenSummary2": "Czy możemy przenieść trochę paczek",
	"DavidGravenEmail1": "Jono,",
	"DavidGravenEmail2": "Możemy przenieść część skrzyń do magazynu Arque East? Słyszałem, że ma ich przyjść jeszcze więcej, a tu ich nie pomieścimy, zwłaszcza że mamy też te duże skrzynie z zaopatrzeniem. Porozmawiam o tym z Jeffem... część z nich mają zabrać na górę.",
	"DavidGravenSig": "Dave",
	"JonathanBillyTitle": "piatek",
	"JeffHerbandTitle": "Dostawa...",
	"JeffHerbandSummary": "Spodziewamy się kolejnych paczek",
	"JeffHerbandAccount": "Jeff Herband < jeff.herband@arque.local >",
	"JeffHerbandName": "Jeff Herband",
	"JeffHerbandSig": "Arque West, kierownik magazynu",
	"JeffHerbandLine1": "Wysłali więcej skrzyń. Pamiętaj, żeby je zabezpieczyć. Nie chcemy, żeby coś się uszkodziło.",
	"WentworthHeraldTitle": "Wentworth Herald",
	"MoreOnPage7": "Więcej na stronie 7",
	"MoreOnPage10": "Więcej na stronie 10",
	"LighthouseDecomissionedTitle": "Latarnia morska zamknięta",
	"LostTitle": "Zguba",
});