ae.addLanguage("danish", {
	"GameTitle": "Estranged",
	"GameSubtitle": "Act I",
	"Language": "danish",
	"Close": "Luk",
	"CreditsWithThanksTo": "Med tak til",
	"CreditsTeam": "Hold",
	"CreditsMainMenu": "Gå til hovedmenuen",
	"CreditsCreator": "Skaber",
	"CreditsVoices": "Stemmer",
	"CreditsPreviousVoices": "Tidligere stemmer",
	"CreditsTranslators": "Oversættere",
	"CreditsTesters": "Testere",
	"CreditsMacOSBuild": "Mac OS-version",
	"CreditsDanishTranslator": "Dansk oversætter",
	"CreditsTranslator": "Oversætter",
	"CreditsPhotographer": "Fotograf",
	"CreditsLevelDesigner": "Banedesigner",
	"CreditsProgrammer": "Programmør",
	"CreditsModelArtist": "3D-modelartist",
	"CreditsOmnicorpBroadcaster": "Arque-oplæser",
	"CreditsAudioDesigner": "Lyddesigner",
	"Workstation": "Arbejdsstation",
	"OK": "OK",
	"Cancel": "Annuller",
	"IconEmail": "Email",
	"IconLogOff": "Log af",
	"Incorrect": "Beklager, det var forkert.",
	"SecretPetName": "alex",
	"YantoWardName": "Yanto Ward",
	"YantoWardAccount": "Yanto Ward < yanto.ward@arque.local >",
	"Pets_R_Us_From": "Pets Are Us < judy@petsrus.com >",
	"Pets_R_Us_Line1": "Hr. Ward,",
	"Pets_R_Us_Line5": "Judy Ferrand.",
	"WhatIsThatSmell": "HVAD ER DEN LUGT",
	"Srsly": "seriøst",
	"NigelHeathcoat": "Nigel Heathcoat < nigel@arque.local >",
	"FrancisRobella": "Francis Robella < francis@arque.local >",
	"FrancisRobellaLine1": "Hey,",
	"FrancisRobellaLine3": "Francis",
	"Image1": "IMG_0270_104942.JPEG",
	"Image2": "IMG_0430_104912.JPEG",
	"Image3": "IMG_0430_104944.JPEG",
	"Image4": "IMG_0470_104454.JPEG",
	"Image5": "IMG_0437_104954.JPEG",
	"Image6": "IMG_0440_104964.JPEG",
	"Image7": "IMG_0437_104964.JPEG",
	"Image8": "IMG_034324_432432.MP4",
	"ChristianPlitheName": "Christian Plithe",
	"ChristianPlitheAccount": "Christian Plithe < christian.plithe@arque.local >",
	"AdmirerName": "Din beundrer",
	"WilliamShortAccount": "William Short < william.short@arque.local >",
	"WilliamShortLine1": "Hej Christian,",
	"ChrisLine1": "Hej Will,",
	"ChrisLine2": "Jeg bliver ved med at modtage de her underlige emails fra en eller anden, der påstår at være min \"beundrer\", de kommer også fra anonymous@arque.local.",
	"ChrisLine3": "Her er et uddrag fra en af dem:",
	"ChrisLine4": "Jeg værdsætter, at vi har haft vores forskelligheder for nylig, men jeg skal bruge hjælp med det her... i starten var det mærkeligt, men nu er det decideret uhyggeligt. Kan det her tælle som en officiel klage?",
	"ChrisLine5": "Christian",
	"MeetMeTitle": "Hvorfor mødte du mig ikke?",
	"MeetMeSummary": "Jeg var helt alene i...",
	"MeetMeLine2": "Jeg lover dig, at jeg ikke er sådan. Hør her, vi prøver det igen i morgen. Jeg venter.",
	"HandledTheManagerLine1": "Jeg kunne virkelig godt lide måden, du håndterede lederen i dag, du er et bæst, når du er sur. Jeg elskede måden, sveden dryppede ned af din anden hage... der er bare et eller andet ved det.",
	"JonathanBillyName": "Jonathan Billy",
	"JonathanBillyAccount": "Jonathan Billy < jonathan.billy@arque.local >",
	"JonathanBillyLine1": "har du vagt på fredag",
	"JonathanBillyLine2": "min dater har en svømekonkurrence og kone sir at jeg ska med. kan du dække min vagt",
	"JonathanBillyLine3": "tak",
	"JonathanBillyLine4": "fra jono",
	"DavidGravenName": "David Graven",
	"DavidGravenAccount": "David Graven < david.graven@arque.local >",
	"DavidGravenTitle2": "Kasser",
	"DavidGravenSummary1": "Det er fint, nyd dagen :)",
	"DavidGravenSummary2": "Kan vi flytte nogle af kasserne",
	"DavidGravenSig": "Dave",
	"JonathanBillyTitle": "fredag",
	"JeffHerbandTitle": "På vej...",
	"JeffHerbandSummary": "Der er flere kasser på vej",
	"JeffHerbandAccount": "Jeff Herband < jeff.herband@arque.local >",
	"JeffHerbandName": "Jeff Herband",
	"JeffHerbandLine1": "Der er flere kasser på vej. Bare husk at holde dem sikre, vi vil ikke have, at der går noget i stykker.",
	"WentworthHeraldTitle": "Wentworth Herald",
	"MoreOnPage7": "Mere på side 7",
	"MoreOnPage10": "Mere på side 10",
	"LighthouseDecomissionedTitle": "Fyrtårn nedlukkes",
	"LighthouseDecomissionedParagraph1": "Fyrtårnet, beliggende på det udstående landstykke i Redton, skal nedlægges af den lokale borgmester, John Menn, som følge af en undersøgelse lavet af kystvagten.",
	"LighthouseDecomissionedParagraph3": "Da han blev udspurgt, nægtede borgmesteren at kommentere, indtil han havde udsendt en officiel udtalelse vedrørende lukningen af fyrtårnet.",
});