ae.addLanguage("hungarian", {
	"GameTitle": "Estranged",
	"GameSubtitle": "Act I",
	"Language": "hungarian",
	"Close": "Bezár",
	"CreditsWithThanksTo": "Köszönet",
	"CreditsTeam": "Csapat",
	"CreditsMainMenu": "Vissza a főmenübe",
	"CreditsCreator": "Készítő",
	"CreditsVoices": "Hangok",
	"CreditsPreviousVoices": "Előző hangok",
	"CreditsTranslators": "Fordítók",
	"CreditsTesters": "Tesztelők",
	"CreditsMacOSBuild": "Mac OS verzió",
	"CreditsDanishTranslator": "Dán fordító",
	"CreditsMapCompiler": "Pályaszerkesztő",
	"CreditsTranslator": "Fordító",
	"CreditsTester": "Tesztelő",
	"CreditsPhotographer": "Fényképész",
	"CreditsGuitarSamples": "Gitárminták",
	"CreditsProjectLead": "Projektvezető",
	"CreditsLevelDesigner": "Pályatervező",
	"CreditsProgrammer": "Programozó",
	"CreditsStoryDesigner": "Történettervező",
	"CreditsTextureArtist": "Textúrakészítő",
	"CreditsModelArtist": "3D-modell készítő",
	"CreditsVoiceOf": "Hangok",
	"CreditsLeadMusician": "Zenei vezető",
	"CreditsShaderArtist": "Shader-készítő",
	"CreditsOmnicorpThug": "Arque őr",
	"CreditsOmnicorpBroadcaster": "Arque bemondó",
	"CreditsMirrorHosting": "Letöltési tárhelyszolgáltató",
	"CreditsAudioDesigner": "Hangtervező",
	"CreditsOculusRift": "Oculus Rift adományozója",
	"CreditsDonors": "Projekt adományozók",
	"CreditsSteamTranslation": "A Steam Translation Server",
	"Workstation": "Munkaállomás",
	"EndSession": "Be akarja zárni a munkamenetet?",
	"OK": "OK",
	"Cancel": "Mégse",
	"IconEmail": "Email",
	"IconLogOff": "Kijelentkezés",
	"IconDoorUnlock": "Ajtó kinyitása",
	"OnlyPrintIfNecessary": "Kíméld a környezetet. Csak akkor nyomtasd ki ezt az emailt, ha muszáj.",
	"Incorrect": "Sajnálom, ez helytelen volt.",
	"SecretPetName": "alex",
	"DialogGenerator": "Generátorkonzol",
	"DialogGeneratorOverHeat": "FIGYELEM: GENERÁTOR-TÚLMELEGEDÉS",
	"DialogGeneratorDisconnect": "KIJELENTKEZÉS A GENERÁTORKONZOLBÓL",
	"YantoWardName": "Yanto Ward",
	"YantoWardAccount": "Yanto Ward < yanto.ward@arque.local >",
	"Pets_R_Us_Update": "Pets Are Us frissítés",
	"Pets_R_Us_UpdateSummary": "Mr. Ward, Alex felépült...",
	"Pets_R_Us_From": "Pets Are Us < judy@petsrus.com >",
	"Pets_R_Us_Line1": "Mr. Ward,",
	"Pets_R_Us_Line2": "A kutyája, Alex gyógyul és nagyon jól reagált az általunk adott gyógyszerekre.",
	"Pets_R_Us_Line3": "Hétfőn elviheti majd Alexet.",
	"Pets_R_Us_Line4": "Köszönettel,",
	"Pets_R_Us_Line5": "Judy Ferrand",
	"WhatIsThatSmell": "MI EZ A SZAG",
	"Srsly": "komolyan",
	"NigelHeathcoat": "Nigel Heathcoat < nigel@arque.local >",
	"HaveYouSeenMyLunch": "Láttad az ebédem?",
	"HaveYouSeenMyLunchSummary": "Üdv, Nem láttad az...",
	"FrancisRobella": "Francis Robella < francis@arque.local >",
	"FrancisRobellaLine1": "Üdv,",
	"FrancisRobellaLine2": "Nem láttad az ebédemet? A hűtőben hagytam, és eltűnt. Ha megint ő lopta el, bekattanok. Az a csaj folyton ellopja a dolgaimat!",
	"FrancisRobellaLine3": "Francis",
	"PleaseEnterSecretAnswer": "Kérjük, a folytatáshoz írja be a választ a titkos kérdésre:",
	"NameOfPet": "Mi a házi kedvence neve?",
	"UnlockAllDoorsPrompt": "Használd az alábbi gombot az összes ajtó kinyitására a sárga emeleten.",
	"UnlockAllDoors": "Minden ajtó kinyitása",
	"DoorsAreUnlocked": "A sárga emeleten jelenleg az összes ajtó nyitva van.",
	"Image1": "IMG_0270_104942.JPEG",
	"Image2": "IMG_0430_104912.JPEG",
	"Image3": "IMG_0430_104944.JPEG",
	"Image4": "IMG_0470_104454.JPEG",
	"Image5": "IMG_0437_104954.JPEG",
	"Image6": "IMG_0440_104964.JPEG",
	"Image7": "IMG_0437_104964.JPEG",
	"Image8": "IMG_034324_432432.MP4",
	"ChristianPlitheName": "Christian Plithe",
	"ChristianPlitheAccount": "Christian Plithe < christian.plithe@arque.local >",
	"LunchRoomTitle": "Étkező",
	"LunchRoomSummary": "Christian, Egyre csak te...",
	"LunchRoomLine1": "Christian, Egyre csak te jársz a fejemben. Attól a pillanattól, hogy először megláttalak az étkezőben, tudtam, hogy te vagy az igazi. Abból, ahogy a zsíros csirkeszárnyak lassan dörzsölték az ajkaidat ---------- nagyon erős férfi vagy. Remélem, hogy holnap ugyanebben az időben, ugyanott látlak. Figyelni foglak...",
	"AdmirerName": "A csodálód,",
	"AdmirerAccount": "Csodáló < anonymous@arque.local >",
	"WilliamShortAccount": "William Short < william.short@arque.local >",
	"WilliamShortSig": "William Short, gyártásmenedzser",
	"WilliamShortTitle": "RE: Zaklatás",
	"WilliamShortSummary": "Christian, Ezt jelentettem a HR-nek...",
	"WilliamShortLine1": "Szia Christian,",
	"WilliamShortLine2": "Ezt jelentettem a HR-nek és a belső támogatásnak, megpróbálják lenyomozni a „csodálót”.",
	"WilliamShortLine3": "El kell ismerd, ez az egész nevetséges...",
	"ChrisLine1": "Szia Will,",
	"ChrisLine2": "Folyamatosan kapom ezeket a nagyon furcsa emaileket valakitől, aki a „csodálómnak” vallja magát, ráadásul az anonymous@arque.local címről jönnek.",
	"ChrisLine3": "Itt egy részlet az egyikből:",
	"ChrisLine4": "Tiszteletben tartom, hogy nemrég voltak nézeteltéréseink, de ezzel segítségre van szükségem... eleinte furcsa volt, de most már egyenesen ijesztő. Számíthat ez hivatalos panasznak?",
	"ChrisLine5": "Christian",
	"MeetMeTitle": "Miért nem találkoztál velem?",
	"MeetMeSummary": "Teljesen egyedül voltam a...",
	"MeetMeLine1": "Teljesen egyedül voltam az étkezőben, szerettem volna nézni, ahogy eszel, de nem jöttél! Megijesztelek?",
	"MeetMeLine2": "Biztosíthatlak, én nem vagyok olyan... figyelj, holnap újra megpróbálhatjuk. Én várni fogok.",
	"HandledTheManagerTitle": "Láttam, ahogy az igazgatóval bántál",
	"HandledTheManagerSummary": "Nagyon tetszett...",
	"HandledTheManagerLine1": "Nagyon tetszett, ahogy ma az igazgatóval bántál, dühösen egy bestia vagy. Tetszett, ahogy az verejték legördült a tokádon... egyszerűen van benne valami.",
	"JonathanBillyName": "Jonathan Billy",
	"JonathanBillyAccount": "Jonathan Billy < jonathan.billy@arque.local >",
	"JonathanBillyLine1": "dolgozol pénteken",
	"JonathanBillyLine2": "lányomnak uszóversenye lesz és a asszony aszonta nekem kell lmenni. be tudod válalni a műszakom",
	"JonathanBillyLine3": "köszi",
	"JonathanBillyLine4": "jonótól",
	"DavidGravenName": "David Graven",
	"DavidGravenAccount": "David Graven < david.graven@arque.local >",
	"DavidGravenTitle1": "RE: péntek",
	"DavidGravenTitle2": "Dobozok",
	"DavidGravenSummary1": "Nem gond, szép napot :)",
	"DavidGravenSummary2": "Át tudunk szállítani néhány dobozt",
	"DavidGravenEmail1": "Jono,",
	"DavidGravenEmail2": "Át tudunk szállítani néhány dobozt az Arque Keletnél levő raktárba? Azt mondják még több fog érkezni, de ide már nem sokkal több fér - főleg a nagy ellátmányos ládákkal együtt. Beszélek Jeffel erről... Elvileg fel kéne vinniük néhányat valamikor az emeletre.",
	"DavidGravenSig": "Dave",
	"JonathanBillyTitle": "péntek",
	"JeffHerbandTitle": "Szállítás...",
	"JeffHerbandSummary": "Még több doboz érkezik",
	"JeffHerbandAccount": "Jeff Herband < jeff.herband@arque.local >",
	"JeffHerbandName": "Jeff Herband",
	"JeffHerbandSig": "Arque Nyugat, raktármenedzser",
	"JeffHerbandLine1": "Még több doboz érkezik. Csak ne feledjétek biztonságosan tárolni őket, nem akarjuk, hogy eltörjön a cucc.",
	"WentworthHeraldTitle": "Wentworth Hírnök",
	"WentworthHeraldTagline": "Mi vagyunk a legjobbak pletykákban, sportban, üzletben és keresztrejtvényben. Ez az újság egy életre szól.",
	"MoreOnPage7": "További információ a 7. oldalon",
	"MoreOnPage10": "További információ a 10. oldalon",
	"LighthouseDecomissionedTitle": "Bezár a világítótorony",
	"LighthouseDecomissionedParagraph1": "A helyi polgármester, John Menn bezárásra ítélte a Redtonban, a földnyelven található világítótornyot, a parti őrség által lefolytatott vizsgálatot követően.",
	"LighthouseDecomissionedParagraph2": "„Meggyőződésünk, hogy ennek nem lesz hatása az átmenő forgalomra.”, kommentálta az esetet Bill Hayak, a Tengeri Közlekedési Vizsgálati Részlegtől. „Míg egy időben lehetett teherhajókat látni Redton partjaitól nem messze, már nem ez a helyzet, a kontinentális szállítási útvonalak megváltozása miatt.” tette még hozzá.",
	"LighthouseDecomissionedParagraph3": "Rákérdezve a polgármester nem volt hajlandó nyilatkozni mindaddig, míg hivatalos nyilatkozatot nem adott ki a világítótorony bezárásáról.",
	"LighthouseDecomissionedParagraph4": "A helyi lakosok nem örülnek a változásnak, egyiküket aggasztja, milyen hatása lesz ennek a kis kereskedelmi hajókra, melyek továbbra is kikötnek a szigeten, azt mondva, ez volt az utolsó szög a sziget csendes kikötőjének koporsójában. „Ettől jó sok leáll a sziget üzletei közül.” mondta.",
	"LighthouseDecomissionedParagraph5": "Néha a világítótorony az egyetlen dolog, ami lehetővé teszi, hogy kisebb hajók jöjjenek be kereskedni a helyi üzletekkel, és ez olyasmi, ami miatt mind aggódunk; mi történik, ha nem marad itt import-kereskedelem?",
	"LighthouseDecomissionedQuote": "„Túl kevés” a hajó ahhoz, hogy biztonsági probléma legyen, mondja a parti őrség.",
	"LostTitle": "Elveszett",
	"LostParagraph1": "Két hét telt el az óta, hogy Christian Plithe, a helyi Arque alkalmazottja elvesztette \"Mázlis\" nevű fekete macskáját. Arra kér mindenkit, hogy azonnal vegye fel vele a kapcsolatot, ha látja a macskát.",
	"ScarecrowCompetitionTitle": "Zajlik a helyi madárijesztő-verseny",
	"ScarecrowCompetitionParagraph1": "A Redtonban tartott egyik legnépszerűbb verseny idén is visszatért.",
	"ScarecrowCompetitionParagraph2": "A közösség minden évben összegyűlik, hogy elkészítsék a legfélelmetesebb és legszörnyűségesebb madárijesztőket a madarak távol tartására. A tavalyi év győztese a nyolc éves helyi iskolásfiú, Joshua Fenton volt, kinek nagyanyjáról mintázott műve maga mellé állította a döntőbizottságot.",
	"ScarecrowCompetitionParagraph3": "A verseny győztese idén süteményválogatást kap majd a polgármester feleségétől, Julia Menntől, aki nemrég nyitott saját süteményboltot a szigeten.",
	"ScarecrowCompetitionParagraph4": "Az ünnepség nem csupán a madárijesztőkre korlátozódik, melyek egész héten ki lesznek állítva, hanem vásárok és egyéb rendezvények is lesznek szerte a városban. Ha még nem látta a madárijesztőket, vegye az irányt az évenként megrendezett esemény felé, hogy megtudja, mi is ez a nagy felhajtás, és kóstolja meg a Redton által kínált legfinomabb ételeket és italokat is.",
	"ScarecrowCompetitionParagraph5": "Ha nem tud lejönni megnézni a madárijesztőket, nézzen bele következő számunkba, melyben sorra vesszük majd az összes nevezést.",
	"OmnicorpTitle": "Az Arque Vállalat felvásárolja a Phillips Gyógyszergyárat",
	"OmnicorpParagraph1": "Harminc munkás kapott felmondólevelet az elmúlt hét elején, mikor a hatalmas Arque Vállalat befejezte a helyi gyógyszergyártó, a Phillips Gyógyszergyár felvásárlását. A felvásárlás a korábbi tulajdonos nagy nyilvánosság előtt bekövetkezett összeomlását követte, ami befektetők kereséséhez vezetett.",
});