ae.addLanguage("schinese", {
	"GameTitle": "Estranged",
	"GameSubtitle": "Act I",
	"Language": "schinese",
	"Close": "关闭",
	"CreditsWithThanksTo": "鸣谢：",
	"CreditsTeam": "团队",
	"CreditsMainMenu": "返回主菜单",
	"CreditsCreator": "创作人员",
	"CreditsVoices": "配音人员",
	"CreditsPreviousVoices": "早期配音",
	"CreditsTranslators": "翻译人员",
	"CreditsTesters": "测试人员",
	"CreditsMacOSBuild": "Mac OS 版本",
	"CreditsDanishTranslator": "丹麦语翻译人员",
	"CreditsMapCompiler": "地图编辑人员",
	"CreditsTranslator": "翻译人员",
	"CreditsTester": "测试人员",
	"CreditsPhotographer": "摄影人员",
	"CreditsGuitarSamples": "吉他采样",
	"CreditsProjectLead": "项目组长",
	"CreditsLevelDesigner": "关卡设计人员",
	"CreditsProgrammer": "程序设计人员",
	"CreditsStoryDesigner": "剧情设计人员",
	"CreditsTextureArtist": "材质艺术人员",
	"CreditsModelArtist": "3D 模型艺术人员",
	"CreditsVoiceOf": "配音",
	"CreditsLeadMusician": "首席音乐家",
	"CreditsShaderArtist": "着色艺术人员",
	"CreditsOmnicorpThug": "阿尔克暴徒",
	"CreditsOmnicorpBroadcaster": "阿尔克广播员",
	"CreditsMirrorHosting": "下载镜像托管",
	"CreditsAudioDesigner": "音效设计人员",
	"CreditsOculusRift": "捐赠了 Oculus Rift",
	"CreditsDonors": "项目捐助人员",
	"CreditsSteamTranslation": "Steam 翻译服务器",
	"Workstation": "工作站",
	"EndSession": "您想要结束会话吗？",
	"OK": "确定",
	"Cancel": "取消",
	"IconEmail": "电子邮件",
	"IconLogOff": "注销",
	"IconDoorUnlock": "开锁",
	"OnlyPrintIfNecessary": "保护环境。若非必要，请勿打印此邮件。",
	"Incorrect": "很抱歉，这不正确。",
	"SecretPetName": "亚历克斯",
	"DialogGenerator": "发电机控制台",
	"DialogGeneratorOverHeat": "警告：发电机过热",
	"DialogGeneratorDisconnect": "从发电机控制台注销",
	"YantoWardName": "彦图.华德",
	"YantoWardAccount": "彦图.华德 < yanto.ward@arque.local >",
	"Pets_R_Us_Update": "来自善待宠物医院的新消息",
	"Pets_R_Us_UpdateSummary": "华德先生，亚历克斯已经痊愈……",
	"Pets_R_Us_From": "善待宠物医院 < judy@petsrus.com >",
	"Pets_R_Us_Line1": "华德先生，",
	"Pets_R_Us_Line2": "您的狗亚历克斯吃了我们的药，效果非常好，它正在恢复健康。",
	"Pets_R_Us_Line3": "您可以在周一把亚历克斯接走。",
	"Pets_R_Us_Line4": "谢谢，",
	"Pets_R_Us_Line5": "朱迪.费兰德。",
	"WhatIsThatSmell": "这是什么味道",
	"Srsly": "不是吧",
	"NigelHeathcoat": "奈杰尔.希思科特 < nigel@arque.local >",
	"HaveYouSeenMyLunch": "你看到我的午餐了吗？",
	"HaveYouSeenMyLunchSummary": "嘿，你看到我的……",
	"FrancisRobella": "弗朗西斯.罗比尔拉 < francis@arque.local >",
	"FrancisRobellaLine1": "嘿，",
	"FrancisRobellaLine2": "你看到我的午餐了吗？我把它放在冰箱里，它就不见了。如果是她偷的我就要翻脸了。她总是偷我的东西！",
	"FrancisRobellaLine3": "弗朗西斯",
	"PleaseEnterSecretAnswer": "请输入秘密问题的答案以继续：",
	"NameOfPet": "您的宠物叫什么名字？",
	"UnlockAllDoorsPrompt": "使用下面的按钮解锁所有黄色楼层上的门。",
	"UnlockAllDoors": "解锁所有门",
	"DoorsAreUnlocked": "黄色楼层上的所有门现在都已解锁。",
	"Image1": "IMG_0270_104942.JPEG",
	"Image2": "IMG_0430_104912.JPEG",
	"Image3": "IMG_0430_104944.JPEG",
	"Image4": "IMG_0470_104454.JPEG",
	"Image5": "IMG_0437_104954.JPEG",
	"Image6": "IMG_0440_104964.JPEG",
	"Image7": "IMG_0437_104964.JPEG",
	"Image8": "IMG_034324_432432.MP4",
	"ChristianPlitheName": "克里斯蒂安.皮莱斯",
	"ChristianPlitheAccount": "克里斯蒂安.皮莱斯 < christian.plithe@arque.local >",
	"LunchRoomTitle": "餐厅",
	"LunchRoomSummary": "克里斯蒂安，我满脑子都是……",
	"LunchRoomLine1": "克里斯蒂安，我满脑子都是你。从我在餐厅看到你的第一眼的那一刻，我就认准你了。看着油亮的鸡翅缓慢擦过你的双唇 ---------- 你是个很霸气的男人。我想在明天同一时间再次见到你。我等你……",
	"AdmirerName": "你的仰慕者",
	"AdmirerAccount": "仰慕者 < anonymous@arque.local >",
	"WilliamShortAccount": "威廉.肖特 < william.short@arque.local >",
	"WilliamShortSig": "生产经理，威廉.肖特。",
	"WilliamShortTitle": "回复：骚扰",
	"WilliamShortSummary": "克里斯蒂安，我已经将此事报告给人力资源……",
	"WilliamShortLine1": "嗨，克里斯蒂安，",
	"WilliamShortLine2": "我已经将此事报告给人力资源和内部支持部门，他们将试着找出这个“仰慕者”。",
	"WilliamShortLine3": "你必须承认这事太逗了……",
	"ChrisLine1": "嗨，威尔，",
	"ChrisLine2": "我总是从一个自称是我的“仰慕者”的人那收到奇怪的电子邮件，它们同样来自 anonymous@arque.local。",
	"ChrisLine3": "这是其中一封的节选：",
	"ChrisLine4": "我知道我们最近意见不合，但这次我真的需要你帮我一把……一开始这只是有点奇怪，但现在这事已经变得很恐怖了。这可以作为正式投诉吗？",
	"ChrisLine5": "克里斯蒂安",
	"MeetMeTitle": "你为什么不见我？",
	"MeetMeSummary": "我孤伶伶地在……",
	"MeetMeLine1": "我孤伶伶地在餐厅想要看你吃东西，但是你没来！我是吓到你了吗？",
	"MeetMeLine2": "我保证我不是你想的那样，要不，明天我们再来一次吧。我等你。",
	"HandledTheManagerTitle": "我看见你对付经理了",
	"HandledTheManagerSummary": "我特别喜欢……",
	"HandledTheManagerLine1": "我特别喜欢你今天对付经理的那种方式，你生气的时候真是条汉子。我就喜欢汗水流过你的双下巴的样子...很带感的。",
	"JonathanBillyName": "乔纳森.比利",
	"JonathanBillyAccount": "约翰森.比利 < jonathan.billy@arque.local >",
	"JonathanBillyLine1": "尼周五值班吗",
	"JonathanBillyLine2": "莪女儿有个游泳闭塞我老婆说我币虚去。咱们能倒个班么",
	"JonathanBillyLine3": "谢了啊",
	"JonathanBillyLine4": "发信人：约翰",
	"DavidGravenName": "大卫.格雷文",
	"DavidGravenAccount": "大卫.格雷文 < david.graven@arque.local >",
	"DavidGravenTitle1": "回复：周五",
	"DavidGravenTitle2": "盒子",
	"DavidGravenSummary1": "没问题，玩得开心：）",
	"DavidGravenSummary2": "咱能把盒子也倒腾一下吗",
	"DavidGravenEmail1": "乔诺，",
	"DavidGravenEmail2": "咱能把那些盒子倒腾到阿尔克东区的库房去吗？他们说还有更多盒子要送来，但是我们这已经装不下了——还有那些巨大的补给箱。我会跟杰夫谈谈这件事的……它们早晚都要被搬上去的。",
	"DavidGravenSig": "大卫",
	"JonathanBillyTitle": "周五",
	"JeffHerbandTitle": "来了……",
	"JeffHerbandSummary": "有更多的盒子要被送过来",
	"JeffHerbandAccount": "杰夫.赫班德 < jeff.herband@arque.local >",
	"JeffHerbandName": "杰夫.赫班德",
	"JeffHerbandSig": "阿尔克西区，库房经理",
	"JeffHerbandLine1": "有更多的盒子要送来。记住把它们摆稳当，我们可不想弄坏东西。",
	"WentworthHeraldTitle": "文特沃斯先锋报",
	"WentworthHeraldTagline": "新闻、八卦、体育、演艺圈动态、商业信息以及填字游戏的首选。这是属于你的报纸，也是你生活的一部分。",
	"MoreOnPage7": "详见第七版",
	"MoreOnPage10": "详见第十版",
	"LighthouseDecomissionedTitle": "灯塔退役",
	"LighthouseDecomissionedParagraph1": "在经过海岸警卫队调查后，本市市长约翰.梅恩决定让坐落在雷德顿附近陆地突出部分的灯塔退役。",
	"LighthouseDecomissionedParagraph2": "“我们确信这不会影响过往的交通，”海运交通调查部门的比尔.哈耶克如是说。“曾经在雷德顿海岸附近就能看到货船，然而由于来自大陆的航线更改，现在已经再也看不到了。”他补充道。",
	"LighthouseDecomissionedParagraph3": "当被记者提问时，市长表示在就关闭灯塔一事发表官方声明前拒绝就此发表评论。",
	"LighthouseDecomissionedParagraph4": "当地居民对这个变化感到不满，一名本地居民担心这会影响到仍旧在本岛停靠的小型船只，并表示这将是对该岛无人问津的港口最后的致命一击。“它会阻止许多岛上的生意。”他说道。",
	"LighthouseDecomissionedParagraph5": "有时候灯塔是来与本地生意进行交易的小型船只的唯一依靠，这是大家都担心的问题——所有进口贸易都消亡会带来怎样的后果？",
	"LighthouseDecomissionedQuote": "海岸警卫队表示受此影响的船只太少，不构成安全“问题”",
	"LostTitle": "寻宠启事",
	"LostParagraph1": "距离本地阿尔克员工克里斯蒂安.皮莱斯的黑猫“幸运”走失已经过去了两周。他迫切希望见到那只猫的人立刻联系他。",
	"ScarecrowCompetitionTitle": "本地稻草人大赛正在进行",
	"ScarecrowCompetitionParagraph1": "一年一度的在雷德顿举行的最具影响力的比赛又回来啦。",
	"ScarecrowCompetitionParagraph2": "每年整个社区都要聚在一起创作最阴森恐怖的稻草人来驱赶鸟类。去年的获奖者是八岁大的本地学生约书亚.芬顿他的作品对他祖母形象的“完美”呈现赢得了评审小组的一致好评。",
	"ScarecrowCompetitionParagraph3": "市长的妻子茱莉亚.梅恩最近刚在岛上开起了自己的蛋糕店。今年的获奖者将获得一组由她制作的经过精心挑选的蛋糕。",
	"ScarecrowCompetitionParagraph4": "整个庆祝活动可不光是欣赏稻草人——稻草人将持续展出整整一周，还有在全镇各处进行的其它活动。如果您还没参观过那些稻草人就赶快去活动现场开开眼界并品尝雷德顿最美味的食物和饮料吧。",
	"ScarecrowCompetitionParagraph5": "如果您不能亲自参观那些稻草人的话就请关注下期，届时我们将完整向您介绍所有参赛作品。",
	"OmnicorpTitle": "阿尔克集团收购菲利普斯制药",
	"OmnicorpParagraph1": "上周早些时候阿尔克集团完成了对本地制药企业菲利普斯制药的收购，三十名工人被解雇。就在前不久，该企业前拥有者的一次公开崩溃导致该企业开始寻找新的投资人。",
});