ae.addLanguage("spanish", {
	"GameTitle": "Estranged",
	"GameSubtitle": "Act I",
	"Language": "spanish",
	"Close": "Cerrar",
	"CreditsWithThanksTo": "Nuestro agradecimiento a",
	"CreditsTeam": "Equipo",
	"CreditsMainMenu": "Ir al menú principal",
	"CreditsCreator": "Creador",
	"CreditsVoices": "Voces",
	"CreditsPreviousVoices": "Voces anteriores",
	"CreditsTranslators": "Traductores",
	"CreditsTesters": "Testers",
	"CreditsMacOSBuild": "Versión para Mac OS",
	"CreditsDanishTranslator": "Traductor al danés",
	"CreditsMapCompiler": "Compilador de mapas",
	"CreditsTranslator": "Traductor",
	"CreditsTester": "Tester",
	"CreditsPhotographer": "Fotógrafo",
	"CreditsGuitarSamples": "Guitarrista",
	"CreditsProjectLead": "Jefe de proyecto",
	"CreditsLevelDesigner": "Diseñador de niveles",
	"CreditsProgrammer": "Programador",
	"CreditsStoryDesigner": "Creador de la historia",
	"CreditsTextureArtist": "Artista de texturas",
	"CreditsModelArtist": "Artista de modelado 3D",
	"CreditsVoiceOf": "Voz de",
	"CreditsLeadMusician": "Músico principal",
	"CreditsShaderArtist": "Artista de shader",
	"CreditsOmnicorpThug": "Matón de Arque",
	"CreditsOmnicorpBroadcaster": "Locutor de Arque",
	"CreditsMirrorHosting": "Alojamiento del mirror de descarga",
	"CreditsAudioDesigner": "Diseñador de audio",
	"CreditsOculusRift": "Donante de un Oculus Rift",
	"CreditsDonors": "Donantes del proyecto",
	"CreditsSteamTranslation": "El Steam Translation Server",
	"Workstation": "Estación de trabajo",
	"EndSession": "¿Deseas cerrar la sesión?",
	"OK": "Aceptar",
	"Cancel": "Cancelar",
	"IconEmail": "Email",
	"IconLogOff": "Cerrar sesión",
	"IconDoorUnlock": "Desbloquear puertas",
	"OnlyPrintIfNecessary": "Proteja el medio ambiente: imprima este email solo si es necesario.",
	"Incorrect": "Lo siento, no es correcto.",
	"SecretPetName": "alex",
	"DialogGenerator": "Consola del generador",
	"DialogGeneratorOverHeat": "ALERTA: SOBRECALENTAMIENTO DEL GENERADOR",
	"DialogGeneratorDisconnect": "SALIR DE LA CONSOLA DEL GENERADOR",
	"YantoWardName": "Yanto Ward",
	"YantoWardAccount": "Yanto Ward < yanto.ward@arque.local >",
	"Pets_R_Us_Update": "Información de Pets Are Us",
	"Pets_R_Us_UpdateSummary": "Sr. Ward, Álex se ha recuperado...",
	"Pets_R_Us_From": "Pets Are Us < judy@petsrus.com >",
	"Pets_R_Us_Line1": "Sr. Ward:",
	"Pets_R_Us_Line2": "Su perro Álex se está recuperando y ha respondido muy bien a los fármacos que le hemos estado administrando.",
	"Pets_R_Us_Line3": "Podrá recoger a Álex el lunes.",
	"Pets_R_Us_Line4": "Gracias,",
	"Pets_R_Us_Line5": "Judy Ferrand.",
	"WhatIsThatSmell": "QUÉ ES ESE OLOR",
	"Srsly": "en serio",
	"NigelHeathcoat": "Nigel Heathcoat < nigel@arque.local >",
	"HaveYouSeenMyLunch": "Has visto mi almuerzo?",
	"HaveYouSeenMyLunchSummary": "Eh, Has visto mi...",
	"FrancisRobella": "Francis Robella < francis@arque.local >",
	"FrancisRobellaLine1": "Eh,",
	"FrancisRobellaLine2": "Has visto mi almuerzo? Lo dejé en el frigorífico y ya no está. Si es ella que me lo ha vuelto a robar voy a cabrearme de verdad. Siempre me está quitando las cosas!",
	"FrancisRobellaLine3": "Francis",
	"PleaseEnterSecretAnswer": "Por favor, introduce la respuesta a la pregunta secreta para continuar:",
	"NameOfPet": "¿Cómo se llama tu mascota?",
	"UnlockAllDoorsPrompt": "Usa el botón de abajo para desbloquear todas las puertas de la planta amarilla.",
	"UnlockAllDoors": "Desbloquear todas las puertas",
	"DoorsAreUnlocked": "Todas las puertas de la planta amarilla están actualmente desbloqueadas.",
	"Image1": "IMG_0270_104942.JPEG",
	"Image2": "IMG_0430_104912.JPEG",
	"Image3": "IMG_0430_104944.JPEG",
	"Image4": "IMG_0470_104454.JPEG",
	"Image5": "IMG_0437_104954.JPEG",
	"Image6": "IMG_0440_104964.JPEG",
	"Image7": "IMG_0437_104964.JPEG",
	"Image8": "IMG_034324_432432.MP4",
	"ChristianPlitheName": "Christian Plithe",
	"ChristianPlitheAccount": "Christian Plithe < christian.plithe@arque.local >",
	"LunchRoomTitle": "Comedor",
	"LunchRoomSummary": "Christian, no puedo dejar...",
	"LunchRoomLine1": "Christian, no puedo dejar de pensar en ti. Desde el momento en que te vi por primera vez en el comedor supe que tú eras él. Cómo olvidar la imagen de esas grasientas alitas de pollo frotándose lentamente contra tus labios ---------- eres un hombre muy fuerte. Espero verte allí mañana a la misma hora. Te estaré observando...",
	"AdmirerName": "Tu admiradora",
	"AdmirerAccount": "Admiradora < anonymous@arque.local >",
	"WilliamShortAccount": "William Short < william.short@arque.local >",
	"WilliamShortSig": "William Short, director de línea.",
	"WilliamShortTitle": "RE: Acoso",
	"WilliamShortSummary": "Christian, he informado de esto a recursos humanos...",
	"WilliamShortLine1": "Hola Christian,",
	"WilliamShortLine2": "He informado de esto a recursos humanos y a soporte interno. Van a tratar de localizar a tu \"admiradora\".",
	"WilliamShortLine3": "Tienes que reconocer que todo esto es para partirse...",
	"ChrisLine1": "Hola Will,",
	"ChrisLine2": "Sigo recibiendo estos mails tan extraños de alguien que dice ser mi \"admiradora\". También están llegando desde anonymous@arque.local.",
	"ChrisLine3": "Aquí tienes un fragmento de uno de ellos:",
	"ChrisLine4": "Soy consciente de que últimamente hemos tenido nuestras diferencias, pero necesito que me eches una mano con esto... Al principio era raro, pero ahora da miedo realmente. ¿Puedes tomar esto como una queja formal?",
	"ChrisLine5": "Christian",
	"MeetMeTitle": "Por qué no viniste?",
	"MeetMeSummary": "Estaba sola en el...",
	"MeetMeLine1": "Estaba sola en el comedor, quería verte comer pero no viniste! Te estoy asustando?",
	"MeetMeLine2": "Te prometo que no soy así, mira, podemos intentarlo de nuevo mañana. Estaré esperando.",
	"HandledTheManagerTitle": "Vi cómo manejaste al gerente",
	"HandledTheManagerSummary": "Me gustó mucho la...",
	"HandledTheManagerLine1": "Me gustó mucho la forma en que manejaste al gerente hoy, eres una fiera cuanto te enfadas. Adoré el modo en que el sudor resbalaba por tu papada... es algo muy difícil de explicar.",
	"JonathanBillyName": "Jonathan Billy",
	"JonathanBillyAccount": "Jonathan Billy < jonathan.billy@arque.local >",
	"JonathanBillyLine1": "andas de turno el viernes",
	"JonathanBillyLine2": "mi hija tiene un campenato d natacion y mi señora dice q tengo q ir. puedes cubrir mi turno",
	"JonathanBillyLine3": "gracias",
	"JonathanBillyLine4": "jono",
	"DavidGravenName": "David Graven",
	"DavidGravenAccount": "David Graven < david.graven@arque.local >",
	"DavidGravenTitle1": "RE: viernes",
	"DavidGravenTitle2": "Cajas",
	"DavidGravenSummary1": "De acuerdo, pásalo bien :)",
	"DavidGravenSummary2": "Podemos trasladar algunas cajas",
	"DavidGravenEmail1": "Jono,",
	"DavidGravenEmail2": "Podemos trasladar algunas cajas al almacén de Arque East? Dicen que llegan más pero aquí ya no queda mucho sitio, y más teniendo en cuenta las cajas grandes de suministros. Hablaré de ello con Jeff... Se supone que algún momento deberían llevarse algunas de ellas arriba.",
	"DavidGravenSig": "Dave",
	"JonathanBillyTitle": "viernes",
	"JeffHerbandTitle": "Llegan más...",
	"JeffHerbandSummary": "Llegan más cajas",
	"JeffHerbandAccount": "Jeff Herband < jeff.herband@arque.local >",
	"JeffHerbandName": "Jeff Herband",
	"JeffHerbandSig": "Arque West, jefe de almacén",
	"JeffHerbandLine1": "Llegan más cajas. Acordaos de mantenerlas bien aseguradas, no queremos que las cosas se rompan.",
	"WentworthHeraldTitle": "Wentworth Herald",
	"WentworthHeraldTagline": "Tu primera fuente de noticias, chismes, deportes, espectáculos, negocios y crucigramas. Es tu diario, tu vida.",
	"MoreOnPage7": "Más en la pág. 7",
	"MoreOnPage10": "Más en la pág. 10",
	"LighthouseDecomissionedTitle": "Faro desmantelado",
	"LighthouseDecomissionedParagraph1": "El faro ubicado en la punta cercana a Redton será desmantelado por orden del alcalde de la localidad, John Menn, a raíz de un estudio llevado a cabo por la guardia costera.",
	"LighthouseDecomissionedParagraph2": "\"Estamos seguros de que esto no afectará al tráfico que pasa por la zona\", comentó Bill Hayak, del Departmento de Investigación del Tráfico Marítimo. \"Hubo un tiempo en que se podían ver buques de carga frente a las costas de Redton, pero ya no es el caso ahora que se han modificado las rutas de navegación que parten del continente\", añadió.",
	"LighthouseDecomissionedParagraph3": "Al ser interrogado, el alcalde rehusó hacer comentario alguno hasta que hubo publicado una declaración oficial acerca de la clausura del faro.",
	"LighthouseDecomissionedParagraph4": "Los vecinos no están contentos con el cambio. Un lugareño mostró su preocupación por el efecto sobre las pequeñas embarcaciones comerciales que aún recalan en la isla, afirmando que esto es el último clavo en el ataúd del ya de por sí tranquilo muelle. \"Acabará con muchos de los negocios de la isla\", señaló.",
	"LighthouseDecomissionedParagraph5": "A veces el faro es lo único que permite que embarcaciones más pequeñas vengan y comercien con los negocios locales. Es algo que nos preocupa a todos: ¿qué pasará cuando ya no queden empresas de importación aquí?",
	"LighthouseDecomissionedQuote": "\"Demasiados pocos\" barcos como para constituir un problema de seguridad, afirma la guardia costera.",
	"LostTitle": "Extraviado",
	"LostParagraph1": "Dos semanas han pasado desde que el empleado local de Arque Christian Plithe perdiera a su gato negro 'Lucky'. Se insta a cualquiera que vea al animal a que se ponga en contacto con él inmediatamente.",
	"ScarecrowCompetitionTitle": "El campeonato local de espantapájaros está en marcha",
	"ScarecrowCompetitionParagraph1": "Una de las competiciones más populares de cuantas se celebran en Redton regresa en su edición anual.",
	"ScarecrowCompetitionParagraph2": "La comunidad se reúne anualmente para crear los más aterradores y macabros espantapájaros con el fin de ahuyentar a las aves. El vencedor del año pasado fue Joshua Fenton, un escolar de ocho años cuya representación de su Abuela se ganó al jurado.",
	"ScarecrowCompetitionParagraph3": "Este año el ganador de la competición se llevará una exquisita selección de pasteles elaborados por Julia Menn, esposa del alcalde, quien recientemente ha inaugurado su propia pastelería en la isla.",
	"ScarecrowCompetitionParagraph4": "Los festejos no terminan con los espantapájaros —que permanecerán expuestos toda la semana—, ya que habrá casetas y otras actividades repartidas por toda la villa. Si aún no conoces los espantapájaros ven al concurso anual para ver a qué tanto revuelo y degustar algunas de las más exquisitas comidas y bebidas que Redton tiene para ofrecer.",
	"ScarecrowCompetitionParagraph5": "Si no puedes acercarte a ver los espantapájaros echa un vistazo al siguiente número, donde haremos un repaso completo de todos los participantes.",
	"OmnicorpTitle": "Arque Corporation adquiere Phillips Pharmaceuticals",
	"OmnicorpParagraph1": "Treinta trabajadores recibieron notificación a principios de la semana pasada de que el gigante Arque Corporation había completado la adquisición del fabricante local de productos farmacéuticos Phillips Pharmaceuticals. La compra llega después del colapso público del anterior propietario, resultante en la búsqueda de inversores.",
});