ae.addLanguage("koreana", {
	"GameTitle": "Estranged",
	"GameSubtitle": "Act I",
	"Language": "korean",
	"Close": "닫기",
	"CreditsTeam": "팀",
	"CreditsMainMenu": "주 메뉴로 돌아가기",
	"CreditsCreator": "제작자",
	"CreditsVoices": "성우",
	"CreditsPreviousVoices": "전 성우",
	"CreditsTranslators": "번역가",
	"CreditsTesters": "테스터",
	"CreditsMacOSBuild": "Mac OS용 개발자",
	"CreditsDanishTranslator": "덴마크어 번역가",
	"CreditsMapCompiler": "맵 컴파일러",
	"CreditsTranslator": "번역가",
	"CreditsTester": "테스터",
	"CreditsPhotographer": "사진가",
	"CreditsProjectLead": "프로젝트 기획자",
	"CreditsLevelDesigner": "레벨 디자이너",
	"CreditsProgrammer": "프로그래머",
	"CreditsStoryDesigner": "스토리 디자이너",
	"CreditsTextureArtist": "텍스쳐 아티스트",
	"CreditsModelArtist": "3D 모델 아티스트",
	"CreditsVoiceOf": "목소리 출연",
	"CreditsLeadMusician": "리드 뮤지션",
	"CreditsShaderArtist": "쉐이더 아티스트",
	"CreditsOmnicorpThug": "아르크 경비대 성우",
	"CreditsOmnicorpBroadcaster": "방해 신호 성우",
	"CreditsAudioDesigner": "오디오 디자이너",
	"CreditsOculusRift": "Oculus Rift를 기부해주셨습니다",
	"CreditsDonors": "도움을 주신 분들",
	"CreditsSteamTranslation": "The Steam Translation Server",
	"Workstation": "작업대",
	"EndSession": "세션을 종료할까요?",
	"OK": "확인",
	"Cancel": "취소",
	"IconEmail": "이메일",
	"IconLogOff": "로그오프",
	"IconDoorUnlock": "잠금 해제",
	"OnlyPrintIfNecessary": "환경을 보호합시다. 필요할 때만 이 이메일을 인쇄하세요.",
	"Incorrect": "죄송하지만 틀렸습니다.",
	"SecretPetName": "알렉스",
	"DialogGenerator": "발전기 콘솔",
	"DialogGeneratorOverHeat": "주의: 발전기가 과열 중입니다",
	"DialogGeneratorDisconnect": "발전기 콘솔에서 로그아웃",
	"YantoWardName": "얀토 와드",
	"YantoWardAccount": "얀토 와드 < yanto.ward@arque.local >",
	"Pets_R_Us_Update": "Pets Are Us 알림",
	"Pets_R_Us_UpdateSummary": "와드 씨, 알렉스가 조금씩...",
	"Pets_R_Us_From": "Pets Are Us < judy@petsrus.com >",
	"Pets_R_Us_Line1": "와드 씨,",
	"Pets_R_Us_Line2": "알렉스가 점점 회복되고 있으며 치료제에 대하여 별다른 거부 증상이 없습니다.",
	"Pets_R_Us_Line3": "알렉스를 월요일쯤에 데리러 오실 수 있을 것 같아요.",
	"Pets_R_Us_Line4": "감사합니다,",
	"Pets_R_Us_Line5": "주디 페란드가.",
	"WhatIsThatSmell": "이게 뭔 냄새야",
	"Srsly": "정말",
	"NigelHeathcoat": "나이젤 히스코트 < nigel@arque.local >",
	"HaveYouSeenMyLunch": "내 점심 본 적 있어?",
	"HaveYouSeenMyLunchSummary": "저기, 내...",
	"FrancisRobella": "프란시스 로벨라 < francis@arque.local >",
	"FrancisRobellaLine1": "안녕,",
	"FrancisRobellaLine2": "내 점심 본 적 있어? 냉장고에 뒀더니 없어졌더라. 그 사람이 훔친 거면 이번에는 가만두지 않겠어. 맨날 내 물건을 훔쳐간다고!",
	"FrancisRobellaLine3": "프란시스",
	"PleaseEnterSecretAnswer": "계속하려면 비밀 질문의 답을 입력해 주십시오:",
	"NameOfPet": "내 애완동물의 이름은?",
	"UnlockAllDoorsPrompt": "아래 버튼으로 노란색 층에 있는 모든 문의 잠금을 해제할 수 있습니다.",
	"UnlockAllDoors": "모든 문 잠금 해제",
	"DoorsAreUnlocked": "노란색 층의 모든 문이 현재 잠겨 있지 않습니다.",
	"Image1": "IMG_0270_104942.JPEG",
	"Image2": "IMG_0430_104912.JPEG",
	"Image3": "IMG_0430_104944.JPEG",
	"Image4": "IMG_0470_104454.JPEG",
	"Image5": "IMG_0437_104954.JPEG",
	"Image6": "IMG_0440_104964.JPEG",
	"Image7": "IMG_0437_104964.JPEG",
	"Image8": "IMG_034324_432432.MP4",
	"ChristianPlitheName": "크리스티안 플라이스",
	"ChristianPlitheAccount": "크리스티안 플라이스 < christian.plithe@arque.local >",
	"LunchRoomTitle": "식사실",
	"LunchRoomSummary": "크리스티안, 난...",
	"LunchRoomLine1": "크리스티안, 난 당신을 지켜보는 걸 멈출 수 없어요. 당신을 식사실에서 봤을 때 당신이 바로 그 사람이라는 것을 알았죠. 기름진 닭날개 튀김이 당신의 입술을 따라 미끄러지는 그 때 ---------- 당신은 역시 끌리는 남자에요. 내일도 같은 곳에서 같은 때에 당신을 보길 바래요. 지켜보고 있을게요...",
	"AdmirerName": "당신의 추종자",
	"AdmirerAccount": "추종자 < anonymous@arque.local >",
	"WilliamShortAccount": "윌리엄 쇼트 < william.short@arque.local >",
	"WilliamShortSig": "윌리엄 쇼트, 생산 라인 관리자.",
	"WilliamShortTitle": "RE: 괴롭힘",
	"WilliamShortSummary": "크리스티안, 이 사건을 관리실에 통보...",
	"WilliamShortLine1": "친애하는 크리스티안에게,",
	"WilliamShortLine2": "내가 이 사건을 관리실과 내부 지원팀에 통보했는데 그들이 이 '추종자'를 추적할 거래.",
	"WilliamShortLine3": "그래도 이거 참 웃긴데...",
	"ChrisLine1": "윌리엄에게,",
	"ChrisLine2": "전이랑 같은 주소인 anonymous@arque.local에서 이 '추종자'라는 사람이 계속 요상한 이메일을 보내고 있어요.",
	"ChrisLine3": "여기 예를 하나 보여드리죠:",
	"ChrisLine4": "저번에도 그런 저런 사건이 있었지만, 전 도움이 필요해요... 처음에는 이상했는데 이젠 무섭기까지 하다고요. 이게 공식적인 의견으로 받아들여질까요?",
	"ChrisLine5": "크리스티안",
	"MeetMeTitle": "왜 날 만나지 않은 거야?",
	"MeetMeSummary": "난 혼자서...",
	"MeetMeLine1": "난 혼자서 식사실에 있었어. 네가 먹는 걸 지켜보고 싶었지만 오지 않았잖아! 내가 너한테는 무섭니?",
	"MeetMeLine2": "난 그렇게 못생기진 않았는데 말야. 내일은 올 거지? 기다릴게.",
	"HandledTheManagerTitle": "네가 그 관리자를 대하는 걸 봤어",
	"HandledTheManagerSummary": "난 그...",
	"HandledTheManagerLine1": "네가 그 관리자를 대하는 걸 오늘 봤어. 넌 화날 때는 완전히 야수가 되던데. 이중 턱에서 땀이 흘러내린 그 때... 뭔가 기분이 좀 그렇더라.",
	"JonathanBillyName": "조나단 빌리",
	"JonathanBillyAccount": "조나단 빌리 < jonathan.billy@arque.local >",
	"JonathanBillyLine1": "금요일에 근무함?",
	"JonathanBillyLine2": "아내가 딸 수영대회만은 꼭 가야된다고 함. 근무 좀 대신 서줘",
	"JonathanBillyLine3": "고마워",
	"JonathanBillyLine4": "조나단",
	"DavidGravenName": "데이비드 그레이븐",
	"DavidGravenAccount": "데이비드 그레이븐 < david.graven@arque.local >",
	"DavidGravenTitle1": "RE: 금요일",
	"DavidGravenTitle2": "상자",
	"DavidGravenSummary1": "그러지 뭐, 즐기다 와 :)",
	"DavidGravenSummary2": "상자를 보낼 수 있을까",
	"DavidGravenEmail1": "조나단,",
	"DavidGravenEmail2": "아르크 동부 창고로 상자를 보내면 안될까? 상자가 더 온다는데 여기엔 더 이상 자리가 없어 - 특히 그 큰 보급 상자 때문에. 제프에게 물어봐야겠어... 이 상자들을 언젠간 위층으로 옮겨야 될 거야.",
	"DavidGravenSig": "데이비드",
	"JonathanBillyTitle": "금요일",
	"JeffHerbandTitle": "상자 전송",
	"JeffHerbandSummary": "상자가 곧 도착할것임",
	"JeffHerbandAccount": "제프 허밴드 < jeff.herband@arque.local >",
	"JeffHerbandName": "제프 허밴드",
	"JeffHerbandSig": "아르크 서부, 창고 관리자",
	"JeffHerbandLine1": "상자가 곧 도착할거야. 조심하게 다루는 거 잊지 마, 아무도 문제가 생기는 걸 바라지는 않겠지.",
	"WentworthHeraldTitle": "웬트워스 일간지",
	"WentworthHeraldTagline": "소식통, 스포츠, 유명 인사, 사업 그리고 단어 퍼즐까지.",
	"MoreOnPage7": "7페이지에서 계속",
	"MoreOnPage10": "10페이지에서 계속",
	"LighthouseDecomissionedTitle": "버려진 등대",
	"LighthouseDecomissionedParagraph1": "레드턴의 돌출형 지형에 위치한 등대가 해안 경비대의 조사 이후 마을 시장 존 멘이 이를 폐쇄할 것을 밝혔습니다.",
	"LighthouseDecomissionedParagraph2": "\"우리는 이번 사건이 교통에 방해가 되지 않을 거라고 확신합니다.\"라고 해양교통조사단의 빌 하야크씨께서 의견을 표명했습니다. \"레드턴 주변에서 가끔씩 보던 화물선도 항로가 바뀌었기 때문에 걱정할 필요가 없습니다.\"라고 더했습니다.",
	"LighthouseDecomissionedParagraph3": "마을 시장은 등대의 폐쇄에 대해 공식 발표를 하기 전에는 의견을 표명하지 않을 것을 밝혔습니다.",
	"LighthouseDecomissionedParagraph4": "한편 주민들은 이 변화에 대해 부정적입니다. 한 주민은 '이 섬의 많은 사업들을 멈추는 일이오.'라고 말하며 섬에 정박하는 작은 거래용 배들에 끼칠 영항이 우려되고 섬의 조용한 항구에 못을 박는 일이라고 밝혔습니다.",
	"LighthouseDecomissionedParagraph5": "가끔씩 작은 배들이 마을의 사업체와 거래하기 위해 정박하는 것을 등대에 의지할 때가 있는데, 이게 불가능하게 되면 이 섬은 어떻게 되는 걸까요?",
	"LighthouseDecomissionedQuote": "안전 문제라고 하기에는 '너무 적은' 배들이라고 해안 경비대가 밝힘",
	"LostTitle": "주인을 찾습니다",
	"LostParagraph1": "마을의 아르크 주식회사 사원 크리스티안 플리스가 그의 검은 고양이 '럭키'를 잃어버린 지 2주가 지났습니다. 그의 고양이를 본 사람은 곧바로 그에게 연락할 것을 간곡히 청했습니다.",
	"ScarecrowCompetitionTitle": "허수아비 만들기 대회 진행 중",
	"ScarecrowCompetitionParagraph1": "레드턴의 가장 유명한 대회의 때가 돌아왔습니다.",
	"ScarecrowCompetitionParagraph2": "마을 주민 전체가 가장 공포스럽고 귀신같은 허수아비를 만들어 서로 경쟁하는 이 대회의 작년 우승자는 8살의 학생 조슈아 펜튼으로 그의 할머니를 본따 만든 허수아비가 심사위원단 평가 만장일치로 승리했습니다.",
	"ScarecrowCompetitionParagraph3": "올해의 대회에서 승리한 사람은 시장의 아내이자 섬에 새로이 케이크 가게를 열은 줄리아 멘의 케이크를 받게 될 것입니다.",
	"ScarecrowCompetitionParagraph4": "일주일 내내 전시될 허수아비가 싫다면 각종 판매대나 행사를 경험해 보실 수도 있습니다. 아직 허수아비를 보지 않으셨다면 개최 장소로 찾아가서 레드턴의 최고의 음식과 음료를 맛보십시오.",
	"ScarecrowCompetitionParagraph5": "허수아비를 볼 시간이 없으시다면 다음 장에서 대회 참가 작품들을 볼 수 있습니다.",
	"OmnicorpTitle": "아르크 주식회사, 필립스 제약회사 인수",
	"OmnicorpParagraph1": "거대 기업 아르크 주식회사가 마을의 제약회사 필립스 제약을 인수하며 30명의 직원들이 통보를 받았습니다. 필립스 제약의 소유자는 이로 인해 파산하여 현재 투자자를 모집하고 있습니다.",
});