ae.addLanguage("thai", {
	"GameTitle": "Estranged",
	"GameSubtitle": "Act I",
	"Language": "thai",
	"Close": "ปิด",
	"CreditsWithThanksTo": "ขอขอบคุณ",
	"CreditsTeam": "ทีม",
	"CreditsMainMenu": "ไปที่เมนูหลัก",
	"CreditsCreator": "ผู้สร้าง",
	"CreditsVoices": "นักพากย์",
	"CreditsPreviousVoices": "นักพากย์ก่อนหน้า",
	"CreditsTranslators": "นักแปล",
	"CreditsTesters": "นักทดสอบ",
	"CreditsMacOSBuild": "เวอร์ชั่น Mac OS",
	"CreditsDanishTranslator": "นักแปลภาษาเดนมาร์ก",
	"CreditsMapCompiler": "Map Compiler",
	"CreditsTranslator": "นักแปล",
	"CreditsTester": "นักทดสอบ",
	"CreditsPhotographer": "ช่างภาพ",
	"CreditsGuitarSamples": "เสียงกีตาร์",
	"CreditsProjectLead": "ผู้นำโครงการ",
	"CreditsLevelDesigner": "นักออกแบบด่าน",
	"CreditsProgrammer": "โปรแกรมเมอร์",
	"CreditsStoryDesigner": "นักออกแบบเนื้อเรื่อง",
	"CreditsTextureArtist": "นักออกแบบเท็กซ์เจอร์",
	"CreditsModelArtist": "นักออกแบบโมเดล 3D",
	"CreditsVoiceOf": "เสียงพูดของ",
	"CreditsLeadMusician": "ผู้นำนักดนตรี",
	"CreditsShaderArtist": "นักออกแบบแสงเงา",
	"CreditsOmnicorpThug": "ลูกสมุน Arque",
	"CreditsOmnicorpBroadcaster": "คนประกาศวิทยุ Arque",
	"CreditsMirrorHosting": "ผู้โฮสติ้งเว็บดาวน์โหลด",
	"CreditsAudioDesigner": "นักออกแบบเสียง",
	"CreditsOculusRift": "บริจาค Oculus Rift",
	"CreditsDonors": "ผู้บริจาคโครงการ",
	"CreditsSteamTranslation": "The Steam Translation Server",
	"Workstation": "Workstation",
	"EndSession": "คุณต้องการที่จะจบเซสชั่นของคุณหรือไม่?",
	"OK": "ตกลง",
	"Cancel": "ยกเลิก",
	"IconEmail": "อีเมล",
	"IconLogOff": "ออกจากระบบ",
	"IconDoorUnlock": "ปลดล็อคประตู",
	"OnlyPrintIfNecessary": "รักษาสิ่งแวดล้อม พิมพ์อีเมลนี้ถ้าคุณต้องการ",
	"Incorrect": "ขอโทษ นั่นไม่ถูกต้อง",
	"SecretPetName": "alex",
	"DialogGenerator": "เครื่องควบคุมเครื่องกำเนิดไฟฟ้า",
	"DialogGeneratorOverHeat": "คำเตือน: เครื่องกำเนิดไฟฟ้าความร้อนสูงเกินไป",
	"DialogGeneratorDisconnect": "ออกจากระบบของเครื่องควบคุมเครื่องกำเนิดไฟฟ้า",
	"YantoWardName": "ยันโต วอร์ด",
	"YantoWardAccount": "Yanto Ward < yanto.ward@arque.local >",
	"Pets_R_Us_Update": "Pets Are Us ความคืบหน้า",
	"Pets_R_Us_UpdateSummary": "ท่านวอร์ด อเล็กซ์ (Alex) ฟื้นตัวแล้ว...",
	"Pets_R_Us_From": "Pets Are Us < judy@petsrus.com >",
	"Pets_R_Us_Line1": "ท่าน วอร์ด",
	"Pets_R_Us_Line2": "สุนัขของคุณ อเล็กซ์ (Alex) กำลังฟื้นตัว และ ให้การตอบสนองได้ดีต่อยาที่เราได้ให้กับมัน",
	"Pets_R_Us_Line3": "คุณจะมารับ อเล็กซ์ (Alex) ได้ตอนวันจันทร์",
	"Pets_R_Us_Line4": "ขอบคุณ",
	"Pets_R_Us_Line5": "จูดี้ เฟอร์แรนด์",
	"WhatIsThatSmell": "นั่นกลิ่นอะไรน่ะ",
	"Srsly": "เอาจริงดิ",
	"NigelHeathcoat": "Nigel Heathcoat < nigel@arque.local >",
	"HaveYouSeenMyLunch": "คุณเห็นข้าวเที่ยงของฉันไหม?",
	"HaveYouSeenMyLunchSummary": "เฮ้ คุณเห็น...",
	"FrancisRobella": "Francis Robella < francis@arque.local >",
	"FrancisRobellaLine1": "เฮ้",
	"FrancisRobellaLine2": "คุณเห็นข้าวเที่ยงของฉันไหม? ฉันแช่มันไว้ในตู้เย็นและมันก็หายไป ถ้าเธอขโมยมันอีกครั้งฉันจะตะคอกใส่ เธอชอบมาขโมยของๆฉันประจำ!",
	"FrancisRobellaLine3": "แฟรนซิส",
	"PleaseEnterSecretAnswer": "กรุณาป้อนคำตอบใส่คำถามลับเพื่อไปต่อ:",
	"NameOfPet": "สัตว์เลี้ยงของคุณชื่ออะไร?",
	"UnlockAllDoorsPrompt": "ใช้ปุ่มข้างล่างเพื่อปลดล็อคประตูทั้งหมดบนชั้นสีเหลือง",
	"UnlockAllDoors": "ปลดล็อคประตูทั้งหมด",
	"DoorsAreUnlocked": "ขณะนี้ประตูบนชั้นสีเหลืองทั้งหมดได้ปลดล็อคแล้ว",
	"Image1": "IMG_0270_104942.JPEG",
	"Image2": "IMG_0430_104912.JPEG",
	"Image3": "IMG_0430_104944.JPEG",
	"Image4": "IMG_0470_104454.JPEG",
	"Image5": "IMG_0437_104954.JPEG",
	"Image6": "IMG_0440_104964.JPEG",
	"Image7": "IMG_0437_104964.JPEG",
	"Image8": "IMG_034324_432432.MP4",
	"ChristianPlitheName": "คริสเตียน พลิทท์",
	"ChristianPlitheAccount": "Christian Plithe < christian.plithe@arque.local >",
	"LunchRoomTitle": "โรงอาหาร",
	"LunchRoomSummary": "คริสเตียน ฉันหยุดไม่ได้...",
	"LunchRoomLine1": "คริสเตียน ฉันหยุดไม่ได้ที่จะคิดเกี่ยวกับคุณ เพียงแวบแรกที่ฉันเห็นคุณในโรงอาหาร ฉันรู้ คุณเป็นหนึ่งในนั้น จากปีกไก่ทอดที่ค่อยๆถูริมฝีปากของคุณ ---------- คุณนี่เป็นชายที่ทรงพลังมากจริงๆ ฉันหวังว่าจะได้เห็นคุณที่นั่นอีกพรุ่งนี้เวลาเดิม ฉันคอยดูอยู่นะ...",
	"AdmirerName": "ผู้ชื่นชอบของคุณ",
	"AdmirerAccount": "Admirer < anonymous@arque.local >",
	"WilliamShortAccount": "William Short < william.short@arque.local >",
	"WilliamShortSig": "วิลเลียม ชอร์ต ผู้จัดการสาย",
	"WilliamShortTitle": "RE: ก่อกวน",
	"WilliamShortSummary": "คริสเตียน ฉันได้รายงานสิ่งนี้ไปยัง HR...",
	"WilliamShortLine1": "สวัสดี คริสเตียน",
	"WilliamShortLine2": "ฉันได้รายงานสิ่งนี้ไปยัง HR และ ฝ่ายสนับสนุนภายใน พวกเขากำลังพยายามตามหา \"ผู้ชื่นชอบ\"",
	"WilliamShortLine3": "คุณต้องยอมรับนะว่าทั้งหมดนี้มันตลกสิ้นดี...",
	"ChrisLine1": "สวัสดี วิล",
	"ChrisLine2": "ฉันได้รับอีเมลที่แปลกมากๆนี้มาจากใครบางคนที่อ้างตัวว่าเป็น \"ผู้ชื่นชอบ\" ฉัน มันมาจาก anonymous@arque.local เหมือนกัน",
	"ChrisLine3": "นี่เป็นข้อความส่วนหนึ่งที่ตัดตอนมา:",
	"ChrisLine4": "ฉันยอมรับนะว่าไม่นานนี้เรามีความเห็นที่ต่างกัน แต่ตอนนี้ฉันต้องการให้ช่วย... ตอนแรกมันน่าขนลุก แต่ตอนนี้มันน่ากลัวทีเดียว นี่นับว่าเป็นการร้องเรียนอย่างเป็นทางการหรือเปล่า?",
	"ChrisLine5": "คริสเตียน",
	"MeetMeTitle": "ทำไมคุณไม่มาพบฉัน?",
	"MeetMeSummary": "ฉันอยู่ตัวคนเดียวใน...",
	"MeetMeLine1": "ฉันอยู่ตัวคนเดียวในโรงอาหาร ฉันแค่ต้องการจะดูคุณ แต่คุณไม่ยอมมา! ฉันทำให้คุณกลัวหรือไง?",
	"MeetMeLine2": "ฉันสัญญา ฉันไม่ใช่คนอย่างนั้น ดู เรามาทำมันใหม่ในวันพรุ่งนี้ก็ได้ ฉันจะรอนะ",
	"HandledTheManagerTitle": "ฉันเห็นวิธีที่คุณรับมือกับผู้จัดการแล้ว",
	"HandledTheManagerSummary": "ฉันชอบจริงๆวิธี...",
	"HandledTheManagerLine1": "ฉันชอบจริงๆวิธีที่คุณรับมือกับผู้จัดการวันนี้ คุณเป็นเหมือนสัตว์ป่าเมื่อคุณโกรธ ฉันชอบเวลาที่หยดเหงื่อไหลลงมายังคางของคุณ... มันเป็นอะไรแบบนั้นล่ะนะ",
	"JonathanBillyName": "โจนาธาน บิลลี่",
	"JonathanBillyAccount": "Jonathan Billy < jonathan.billy@arque.local >",
	"JonathanBillyLine1": "คุณทำงานเข้ากะตอนวันศุกร์ใช่ไหม",
	"JonathanBillyLine2": "ลูกสาวฉันมีการแข่งขันว่ายน้ำและภรรยาฉันก็บอกให้ฉันไป คุณช่วยทำงานเข้ากะแทนฉันได้ไหม",
	"JonathanBillyLine3": "ขอบคุณ",
	"JonathanBillyLine4": "จาก โจโน",
	"DavidGravenName": "เดวิด เกรเวน",
	"DavidGravenAccount": "David Graven < david.graven@arque.local >",
	"DavidGravenTitle1": "RE: วันศุกร์",
	"DavidGravenTitle2": "กล่อง",
	"DavidGravenSummary1": "ไม่เป็นไร ขอให้สนุก :)",
	"DavidGravenSummary2": "พวกเราย้ายกล่องพวกนี้",
	"DavidGravenEmail1": "โยโน",
	"DavidGravenEmail2": "พวกเราย้ายกล่องพวกนี้ไปยังโกดัง ที่ Arque ตะวันออกได้ไหม? พวกเขาบอกว่ายังมีอีกเยอะที่กำลังจะมาแต่พวกเราเก็บเอาไว้มากกว่านี้ไม่ได้แล้ว - แล้วไหนจะลังสินค้าใหญ่ๆพวกนี้อีก ฉันจะไปคุณกับเจฟถึงเรื่องนี้... ท้ายที่สุดแล้วพวกเขาก็ต้องนำมันขึ้นไปชั้นบน",
	"DavidGravenSig": "เดฟ",
	"JonathanBillyTitle": "วันศุกร์",
	"JeffHerbandTitle": "กำลังมา...",
	"JeffHerbandSummary": "กล่องอีกมากกำลังมา",
	"JeffHerbandAccount": "Jeff Herband < jeff.herband@arque.local >",
	"JeffHerbandName": "เจฟ เฮอร์แบนด์",
	"JeffHerbandSig": "Arque ตะวันตก ผู้จัดการโกดัง",
	"JeffHerbandLine1": "กล่องอีกมากกำลังมา โปรดจำเอาไว้เก็บมันให้ปลอดภัย เราไม่ต้องการให้ของพวกนี้เสียหาย",
	"WentworthHeraldTitle": "Wentworth Herald",
	"WentworthHeraldTagline": "แหล่งแรกของคุณสำหรับข่าว เรื่องซุบซิบ กีฬา แวดวง ธุรกิจ และปริศนาอักษรไขว้ มันคือหนังสือพิมพ์ของคุณ ชีวิตของคุณ",
	"MoreOnPage7": "อ่านต่อหน้า 7",
	"MoreOnPage10": "อ่านต่อหน้า 10",
	"LighthouseDecomissionedTitle": "เลิกใช้งานประภาคาร",
	"LighthouseDecomissionedParagraph1": "ประภาคารที่ตั้งติดอยู่บนพื้นที่ใน Redton มันถูกกำหนดให้เลิกใช้งาน โดย จอห์น เมนน์ นายกเทศมนตรีท้องถิ่นตามด้วยการตรวจสอบดำเนินการโดยยามชายฝั่ง",
	"LighthouseDecomissionedParagraph2": "\"เรามั่นใจว่านี่จะไม่ส่งผลกระทบต่อการจราจรใดๆ\" บิล ฮาแย็ค แห่งกรมการสอบสวนคดีจราจรทางน้ำ ให้ความเห็น \"ใช่ช่วงหนึ่งคุณจะได้เห็นเรือบรรทุกสินค้าออกจากชายฝั่งของ Redton ตอนนี้มันก็หมดปัญหาในกรณี ที่เส้นทางการขนส่งจากแผ่นดินใหญ่ที่ได้ถูกเปลี่ยนแปลงไป\" เขากล่าวเสริม",
	"LighthouseDecomissionedParagraph3": "เมื่อตั้งคำถามนายกเทศมนตรีได้ปฏิเสธที่จะออกความเห็นจนกว่าเขาจะได้ออกแถลงการณ์อย่างเป็นทางการเกี่ยวกับการสั่งปิดประภาคาร",
	"LighthouseDecomissionedParagraph4": "ประชาชนในเขตท้องถิ่นไม่พอใจกับการเปลี่ยนแปลง คนในท้องถิ่นเป็นกังวลเกี่ยวกับผลกระทบของมันต่อเรือทางการค้าขนาดเล็กที่ยังคงเทียบท่าอยู่ที่เกาะ ได้กล่าวว่ามันจะมุ่งหน้าไปสู่ความล้มเหลวสำหรับท่าเรือที่เงียบสงัดของเกาะนี้ \"มันจะทำให้ธุรกิจของเกาะแห่งนี้หยุดลง\" เขาได้กล่าวไว้",
	"LighthouseDecomissionedParagraph5": "บางครั้งประภาคารก็เป็นสิ่งเดียวที่จะช่วยให้เรือขนาดเล็กเข้ามาและทำการค้ากับธุรกิจในท้องถิ่น มันเป็นอะไรที่พวกเราทุกคนเป็นกังวลอยู่ - จะเกิดอะไรขึ้นถ้าไม่มีธุรกิจการนำเข้าเหลืออยู่?",
	"LighthouseDecomissionedQuote": "เรือ \"น้อยเกินไป\" ที่จะเป็นปัญหาด้านความปลอดภัย ยามชายฝั่งกล่าว",
	"LostTitle": "หลงทาง",
	"LostParagraph1": "สองสัปดาห์ผ่านไปแล้วตั้งแต่พนักงานของ Arque ท้องถิ่น คริสเตียน พลิทท์ ได้ทำแมวดำ 'ลัคกี้' หายไป เขาได้เรียกร้องให้ใครก็ตามที่พบเห็นแมวให้มาติดต่อกับเขาทันที",
	"ScarecrowCompetitionTitle": "กำลังดำเนินงานการประกวดหุ่นไล่กาท้องถิ่น",
	"ScarecrowCompetitionParagraph1": "หนึ่งในการแข่งขันที่ได้รับความนิยมมากที่สุด Redton กลับมาอีกครั้งสำหรับกิจกรรมประจำปีนี้",
	"ScarecrowCompetitionParagraph2": "คนในชุมชนได้มารวมตัวกันทุกปีเพื่อสร้างหุ่นไล่กาที่น่าหวาดกลัวและสยองที่สุดเพื่อขับไล่นกออกไป ผู้ชนะในปีที่แล้วคือเด็กนักเรียนอายุแปดขวบ โจชัว เฟนตัน ผู้ที่เป็นตัวแทนของคุณยายของเขา ชนะบนการให้คะแนนของกรรมการ",
	"ScarecrowCompetitionParagraph3": "ผู้ชนะของการประกวดปีนี้ได้รับเค้กที่ได้รับการคัดเลือกเป็นอย่างดี จาก จูเลีย เม็น ภรรยาของนายกเทศมนตรีผู้ที่เพิ่งเปิดร้านเค้กบนเกาะ",
	"ScarecrowCompetitionParagraph4": "เทศกาลจะไม่หยุดอยู่แค่หุ่นไล่กา - ที่แสดงอยู่ตลอดสัปดาห์ นอกจากนี้ยังมีแผงลอยและกิจกรรมอื่นๆจัดอยู่ทั่วเมือง ถ้าคุณยังไม่เห็นหุ่นไล่กามุ่งหน้าไปยังงานประจำปีเพื่อดูถึงสิ่งที่เกิดขึ้น และ ตัวอย่างของอาหารและเครื่องดื่มรสเลิศที่ Redton มีมานำเสนอ",
	"ScarecrowCompetitionParagraph5": "ถ้าคุณไม่สามารถไปดูหุ่นไล่กาได้ติดตามต่อในฉบับหน้า ที่เราจะกล่าวถึงข้อมูลทั้งหมด",
	"OmnicorpTitle": "บริษัท Arque เข้าซื้อกิจการ Phillips Pharmaceuticals",
	"OmnicorpParagraph1": "พนักงานสามสิบคนได้รับแจ้งเมื่อต้นสัปดาห์ที่แล้วว่าบริษัทยักษ์ใหญ่อย่าง Arque ประสบความสำเร็จในการเข้าซื้อกิจการเภสัชภัณฑ์ในท้องถิ่น Phillips Pharmaceuticals การซื้อขายหุ้นของบริษัททำให้เจ้าของก่อนหน้าได้รับผลกระทบทางจิตใจเป็นอย่างมาก ซึ่งส่งผลให้ต้องค้นหาผู้ลงทุนใหม่",
});