ae.addLanguage("swedish", {
	"GameTitle": "Estranged",
	"GameSubtitle": "Act I",
	"Language": "swedish",
	"Close": "Stäng",
	"CreditsWithThanksTo": "Med tack till",
	"CreditsTeam": "Arbetslag",
	"CreditsMainMenu": "Gå till huvudmeny",
	"CreditsCreator": "Skapare",
	"CreditsVoices": "Röster",
	"CreditsPreviousVoices": "Tidigare röster",
	"CreditsTranslators": "Översättare",
	"CreditsTesters": "Testare",
	"CreditsMacOSBuild": "Mac OS-version",
	"CreditsDanishTranslator": "Dansk översättare",
	"CreditsMapCompiler": "Kartsammanställare",
	"CreditsTranslator": "Översättare",
	"CreditsTester": "Testare",
	"CreditsPhotographer": "Fotograf",
	"CreditsGuitarSamples": "Gitarrstycken",
	"CreditsProjectLead": "Projektledare",
	"CreditsLevelDesigner": "Bankonstruktör",
	"CreditsProgrammer": "Programmerare",
	"CreditsStoryDesigner": "Berättelsekonstruktör",
	"CreditsTextureArtist": "Texturgrafiker",
	"CreditsModelArtist": "3D-modellerare",
	"CreditsVoiceOf": "Rösten till",
	"CreditsLeadMusician": "Huvudmusiker",
	"CreditsOmnicorpThug": "Arque-skurk",
	"CreditsOmnicorpBroadcaster": "Arque-utsändare",
	"CreditsMirrorHosting": "Värd för nedladdningsspeglar",
	"CreditsAudioDesigner": "Ljuddesigner",
	"CreditsOculusRift": "Donerade Oculus Rift",
	"CreditsDonors": "Projektdonatorer",
	"CreditsSteamTranslation": "Steam Translation Server",
	"Workstation": "Arbetsplats",
	"EndSession": "Vill du avsluta din session?",
	"OK": "OK",
	"Cancel": "Avbryt",
	"IconEmail": "E-post",
	"IconLogOff": "Logga ut",
	"IconDoorUnlock": "Lås upp dörr",
	"OnlyPrintIfNecessary": "Värna om miljön. Skriv bara ut det här mejlet om du måste.",
	"Incorrect": "Tyvärr, det var inkorrekt.",
	"SecretPetName": "alex",
	"DialogGenerator": "Generatorkontrollpanel",
	"DialogGeneratorOverHeat": "VARNING: GENERATORN ÖVERHETTAS",
	"DialogGeneratorDisconnect": "LOGGA UT FRÅN GENERATORNS KONTROLLPANEL",
	"YantoWardName": "Yanto Ward",
	"YantoWardAccount": "Yanto Ward < yanto.ward@arque.local >",
	"Pets_R_Us_Update": "Uppdatering från Pets Are Us",
	"Pets_R_Us_UpdateSummary": "Herr Ward, Alex har återhämtat sig...",
	"Pets_R_Us_From": "Pets Are Us < judy@petsrus.com >",
	"Pets_R_Us_Line1": "Herr Ward,",
	"Pets_R_Us_Line2": "Din hund Alex återhämtar sig och har svarat mycket bra på de läkemedel vi gett honom.",
	"Pets_R_Us_Line3": "Du kommer kunna hämta upp Alex på måndag.",
	"Pets_R_Us_Line4": "Tack,",
	"Pets_R_Us_Line5": "Judy Ferrand.",
	"WhatIsThatSmell": "VAD ÄR DET SOM LUKTAR",
	"Srsly": "seriöst",
	"NigelHeathcoat": "Nigel Heathcoat < nigel@arque.local >",
	"HaveYouSeenMyLunch": "Har du sett min lunch?",
	"HaveYouSeenMyLunchSummary": "Hej, har du sett min...",
	"FrancisRobella": "Francis Robella < francis@arque.local >",
	"FrancisRobellaLine1": "Hej,",
	"FrancisRobellaLine2": "Har du sett min lunch? Jag lämnade den i kylen och nu är den borta. Om hon har tagit den igen kommer jag få en knäpp. Hon snor alltid mina saker!",
	"FrancisRobellaLine3": "Francis",
	"PleaseEnterSecretAnswer": "Var god svara på den hemliga frågan för att fortsätta:",
	"NameOfPet": "Vad heter ditt husdjur?",
	"UnlockAllDoorsPrompt": "Använd knappen nedan för att låsa upp alla dörrar på våning Gul.",
	"UnlockAllDoors": "Lås upp alla dörrar",
	"DoorsAreUnlocked": "Alla dörrar på våning Gul är nu upplåsta.",
	"Image1": "IMG_0270_104942.JPEG",
	"Image2": "IMG_0430_104912.JPEG",
	"Image3": "IMG_0430_104944.JPEG",
	"Image4": "IMG_0470_104454.JPEG",
	"Image5": "IMG_0437_104954.JPEG",
	"Image6": "IMG_0440_104964.JPEG",
	"Image7": "IMG_0437_104964.JPEG",
	"Image8": "IMG_034324_432432.MP4",
	"ChristianPlitheName": "Christian Plithe",
	"ChristianPlitheAccount": "Christian Plithe < christian.plithe@arque.local >",
	"LunchRoomTitle": "Lunchrummet",
	"LunchRoomSummary": "Christian, jag kan inte sluta...",
	"LunchRoomLine1": "Christian, jag kan inte sluta tänka på dig. Ögonblicket jag såg dig för första gången i lunchrummet visste jag att du var den rätte. Från de flottiga kycklingvingarna som långsamt knådade dina läppar ---------- du är en mycket kraftfull man. Jag hoppas att du är där samma tid imorgon. Jag kommer se på...",
	"AdmirerName": "Din beundrare",
	"AdmirerAccount": "Beundrare < anonym@arque.local >",
	"WilliamShortAccount": "William Short < william.short@arque.local >",
	"WilliamShortSig": "William Short, linjechef.",
	"WilliamShortTitle": "SV: Trakasserier",
	"WilliamShortSummary": "Christian, jag har rapporterat det här till den personalansvarige...",
	"WilliamShortLine1": "Hej Christian,",
	"WilliamShortLine2": "Jag har rapporterat det här till den personalansvarige och den interna supporten säger att de ska försöka leta rätt på \"beundraren\".",
	"WilliamShortLine3": "Du måste erkänna att hela den här grejen är ganska lustig...",
	"ChrisLine1": "Hej Will,",
	"ChrisLine2": "Jag får en massa märkliga mejl från någon som utger sig för att vara min \"beundrare\", de kommer från anonym@arque.local dessutom.",
	"ChrisLine3": "Här är ett utdrag ur ett:",
	"ChrisLine4": "Jag inser att vi har haft våra meningsskiljaktigheter på senare tid men jag behöver verkligen hjälp med det här... först var det konstigt men nu är det bara läskigt. Kan det här räknas som ett officiellt klagomål?",
	"ChrisLine5": "Christian",
	"MeetMeTitle": "Varför mötte du mig inte?",
	"MeetMeSummary": "Jag var helt ensam i...",
	"MeetMeLine1": "Jag var helt ensam i lunchrummet, jag ville se dig äta men du kom aldrig! Skrämmer jag dig?",
	"MeetMeLine2": "Jag lovar att jag inte är sån, kom igen, vi kan prova igen imorgon. Jag kommer vänta.",
	"HandledTheManagerTitle": "Jag såg hur du hanterade chefen",
	"HandledTheManagerSummary": "Jag gillade verkligen...",
	"HandledTheManagerLine1": "Jag gillade verkligen hur du hanterade chefen idag, du är som ett odjur när du blir arg. Jag gillade sättet svetten rann över din dubbelhaka... Det bara är någonting över det.",
	"JonathanBillyName": "Jonathan Billy",
	"JonathanBillyAccount": "Jonathan Billy < jonathan.billy@arque.local >",
	"JonathanBillyLine1": "har d skift på fredag",
	"JonathanBillyLine2": "min doter har simmtälving och min fru sa ja måste gå. kan d ta mitt skift",
	"JonathanBillyLine3": "tack",
	"JonathanBillyLine4": "från jono",
	"DavidGravenName": "David Graven",
	"DavidGravenAccount": "David Graven < david.graven@arque.local >",
	"DavidGravenTitle1": "RE: fredag",
	"DavidGravenTitle2": "Lådor",
	"DavidGravenSummary1": "Det är okej, ha en bra dag :)",
	"DavidGravenSummary2": "Kan vi flytta på några lådor",
	"DavidGravenEmail1": "Jono,",
	"DavidGravenEmail2": "Kan vi flytta på några lådor till magasinet på Östra Arque? De säger att det kommer komma fler men vi har inte plats för fler - speciellt inte med de stora förvaringslådorna. Jag ska prata med Jeff om det... de ska ta några till övervåningen någon gång.",
	"DavidGravenSig": "Dave",
	"JonathanBillyTitle": "fredag",
	"JeffHerbandTitle": "På väg...",
	"JeffHerbandSummary": "Det är fler lådor på väg",
	"JeffHerbandAccount": "Jeff Herband < jeff.herband@arque.local >",
	"JeffHerbandName": "Jeff Herband",
	"JeffHerbandSig": "Västra Arques Magasinschef",
	"JeffHerbandLine1": "Det är fler lådor på väg. Kom ihåg att hålla dem säkra, vi vill inte att saker ska gå sönder.",
	"WentworthHeraldTitle": "Wentworth-posten",
	"WentworthHeraldTagline": "Förstahandsvalet för nyheter, skvaller, sport, showbiz, affärer och korsord. Det är din tidning, ditt liv.",
	"MoreOnPage7": "Mer på sida 7",
	"MoreOnPage10": "Mer på sida 10",
	"LighthouseDecomissionedTitle": "Fyren tas ur bruk",
	"LighthouseDecomissionedParagraph1": "Fyren belägen i Redton på landutstickaren kommer att tas ur bruk på order av den lokala borgmästaren John Menn på grund av en undersökning av kustbevakningen.",
	"LighthouseDecomissionedParagraph2": "\"Vi är säkra på att detta inte drabbar förbipasserande trafik\", kommenterade Bill Hayak vid Sjötrafikverket. \"Även om man en gång i tiden kunde se godsfartyg utanför Redtons kust är det inte längre fallet, då de dragit om rutterna från fastlandet\", lade han till.",
	"LighthouseDecomissionedParagraph3": "När han tillfrågades avböjde borgmästaren att kommentera tills han förberett ett officiellt uttalande angående fyrens stängning.",
	"LighthouseDecomissionedParagraph4": "Lokala ortsbor är inte nöjda med förändringen. En invånare uttryckte oro över hur beslutet påverkar små handelsskepp som fortfarande lägger till vid ön, och säger att detta var den sista spiken i kistan för öns lugna hamn. \"Det stoppar en stor del av öns affärer\", sade han.",
	"LighthouseDecomissionedParagraph5": "Ibland är fyren det enda som låter mindre skepp komma och handla med lokala affärsverksamheter, det är något som oroar oss alla - vad händer när vi inte längre har någon import?",
	"LighthouseDecomissionedQuote": "\"För få\" skepp för att det ska bli ett säkerhetsproblem enligt kustbevakningen",
	"LostTitle": "Bortsprungen",
	"LostParagraph1": "Två verckor har gått sedan den lokala Arque-anställde Christian Plithes svarta katt \"Lucky\" sprang bort. Han ber den som ser katten kontakta honom omedelbart.",
	"ScarecrowCompetitionTitle": "Lokal fågelskrämmetävling på gång",
	"ScarecrowCompetitionParagraph1": "En av de populäraste tävlingarna som hålls i Redton är tillbaka för sin årliga tradition.",
	"ScarecrowCompetitionParagraph2": "Gemenskapen samlas varje år för att skapa de otäckaste och mest demoniska fågelskrämmorna för att hålla fåglarna borta. Förra årets vinnare var åttaåriga skolpojken Joshua Fento, vars kopia av sin mormor fångade en enad domarpanels tycke.",
	"ScarecrowCompetitionParagraph3": "Detta år får tävlingens vinnare ett fint utbud av tårtor från Julia Menn, borgmästarens fru, som nyligen öppnade sin egen tårtaffär på ön.",
	"ScarecrowCompetitionParagraph4": "Festligheterna slutar inte där - hela veckan finns stånd och andra aktiviteter över hela ön. Har du inte sett fågelskrämmorna ännu, häng med ned till den årliga händelsen och se vad allt väsen är och prova något av den bästa maten och drycken Redton har att erbjuda.",
	"ScarecrowCompetitionParagraph5": "Om du inte förmår komma och se fågelskrämmorna, läs igenom nästa utgåva där vi kommer att ha fulla redogörelser för varje bidrag.",
	"OmnicorpTitle": "Arque Corporation köper upp Phillips Pharmaceuticals",
	"OmnicorpParagraph1": "30 anställda blev varslade tidigt förra veckan i samband med att jätteföretaget Arque genomförde köpet av läkemedelstillverkaren Phillips Pharmaceuticals. Uppköpet är en följd av den tidigare ägarens publika sammanbrott som resulterade i en jakt på nya investerare.",
});