ae.addLanguage("dutch", {
	"GameTitle": "Estranged",
	"GameSubtitle": "Act I",
	"Language": "dutch",
	"Close": "Sluiten",
	"CreditsWithThanksTo": "Met dank aan",
	"CreditsTeam": "Team",
	"CreditsMainMenu": "Naar het hoofdmenu",
	"CreditsCreator": "Maker",
	"CreditsVoices": "Stemmen",
	"CreditsPreviousVoices": "Eerdere stemmen",
	"CreditsTranslators": "Vertalers",
	"CreditsTesters": "Testers",
	"CreditsMacOSBuild": "Mac OS-versie",
	"CreditsDanishTranslator": "Deense vertaler",
	"CreditsMapCompiler": "Mapcompiler",
	"CreditsTranslator": "Vertaler",
	"CreditsTester": "Tester",
	"CreditsPhotographer": "Fotograaf",
	"CreditsGuitarSamples": "Gitaarsamples",
	"CreditsProjectLead": "Projectleider",
	"CreditsLevelDesigner": "Levelontwerper",
	"CreditsProgrammer": "Programmeur",
	"CreditsStoryDesigner": "Verhaalschrijver",
	"CreditsTextureArtist": "Textuurartiest",
	"CreditsModelArtist": "3D-modelartiest",
	"CreditsVoiceOf": "Stem van",
	"CreditsLeadMusician": "Hoofdmuzikant",
	"CreditsShaderArtist": "Shaderartiest",
	"CreditsOmnicorpThug": "Arque-misdadiger",
	"CreditsOmnicorpBroadcaster": "Arque-omroeper",
	"CreditsMirrorHosting": "Downloadmirrorhosting",
	"CreditsAudioDesigner": "Geluidsontwerper",
	"CreditsOculusRift": "Oculus Rift-donateur",
	"CreditsDonors": "Projectdonateurs",
	"CreditsSteamTranslation": "Steam Translation Server",
	"Workstation": "Werkstation",
	"EndSession": "Wil je deze sessie beëindigen?",
	"OK": "OK",
	"Cancel": "Annuleren",
	"IconEmail": "E-mail",
	"IconLogOff": "Uitloggen",
	"IconDoorUnlock": "Deur openen",
	"OnlyPrintIfNecessary": "Spaar het milieu. Print deze e-mail alleen uit als het moet.",
	"Incorrect": "Sorry, dat is onjuist.",
	"SecretPetName": "alex",
	"DialogGenerator": "Generatorbedieningspaneel",
	"DialogGeneratorOverHeat": "WAARSCHUWING: GENERATOR OVERVERHIT",
	"DialogGeneratorDisconnect": "UITLOGGEN UIT GENERATORCONSOLE",
	"YantoWardName": "Yanto Ward",
	"YantoWardAccount": "Yanto Ward < yanto.ward@arque.local >",
	"Pets_R_Us_Update": "Update over Pets Are Us",
	"Pets_R_Us_UpdateSummary": "Mr. Ward, Alex is genezen...",
	"Pets_R_Us_From": "Pets Are Us < judy@petsrus.com >",
	"Pets_R_Us_Line1": "Mr. Ward,",
	"Pets_R_Us_Line2": "Je hond Alex is beter aan het worden en reageert erg positief op de medicijnen die we hem tot nu toe hebben gegeven.",
	"Pets_R_Us_Line3": "Je kunt Alex maandag ophalen.",
	"Pets_R_Us_Line4": "Bedankt,",
	"Pets_R_Us_Line5": "Judy Ferrand",
	"WhatIsThatSmell": "WAT IS DIE STANK",
	"Srsly": "serieus",
	"NigelHeathcoat": "Nigel Heathcoat < nigel@arque.local >",
	"HaveYouSeenMyLunch": "Weet iemand waar mijn lunch is?",
	"HaveYouSeenMyLunchSummary": "Hé, weet jij waar mijn...",
	"FrancisRobella": "Francis Robella < francis@arque.local >",
	"FrancisRobellaLine1": "Hé,",
	"FrancisRobellaLine2": "Heb jij mijn lunch gezien? Ik heb hem in de koelkast achtergelaten en nu is het weg. Als zij hem weer heeft gestolen dan barst ik. Ze steelt mijn spullen altijd!",
	"FrancisRobellaLine3": "Francis",
	"PleaseEnterSecretAnswer": "Vul het antwoord op de geheime vraag in om verder te gaan:",
	"NameOfPet": "Hoe heet uw huisdier?",
	"UnlockAllDoorsPrompt": "Gebruik de knop hieronder om alle deuren op de gele verdieping te ontgrendelen.",
	"UnlockAllDoors": "Alle deuren ontgrendelen",
	"DoorsAreUnlocked": "Alle deuren op de gele verdieping zijn momenteel ontgrendeld.",
	"Image1": "IMG_0270_104942.JPEG",
	"Image2": "IMG_0430_104912.JPEG",
	"Image3": "IMG_0430_104944.JPEG",
	"Image4": "IMG_0470_104454.JPEG",
	"Image5": "IMG_0437_104954.JPEG",
	"Image6": "IMG_0440_104964.JPEG",
	"Image7": "IMG_0437_104964.JPEG",
	"Image8": "IMG_034324_432432.MP4",
	"ChristianPlitheName": "Christian Plithe",
	"ChristianPlitheAccount": "Christian Plithe < christian.plithe@arque.local >",
	"LunchRoomTitle": "Lunchzaal",
	"LunchRoomSummary": "Christian, ik kan niet ophouden...",
	"LunchRoomLine1": "Christian, ik kan niet ophouden met aan jou te denken. Vanaf het moment dat ik je voor het eerst in de lunchzaal zag, wist ik dat jij de ware was. Vanaf het moment dat de vettige kippenvleugels traag over je lippen wreven ---------- je bent een erg machtig man. Ik hoop je daar morgen weer te zien. Ik kijk toe...",
	"AdmirerName": "Je aanbidster",
	"AdmirerAccount": "Aanbidster < anoniem@arque.local >",
	"WilliamShortAccount": "William Short < william.short@arque.local >",
	"WilliamShortSig": "William Short, lijnmanager.",
	"WilliamShortTitle": "RE: Intimidatie",
	"WilliamShortSummary": "Christian, ik heb dit gemeld aan PZ...",
	"WilliamShortLine1": "Hallo Christian,",
	"WilliamShortLine2": "Ik heb dit gemeld aan PZ en Interne Ondersteuning en ze zullen proberen de \"aanbidster\" zo snel mogelijk op te sporen.",
	"WilliamShortLine3": "Geef toe... deze hele zaak is hilarisch.",
	"ChrisLine1": "Hallo Will,",
	"ChrisLine2": "Ik krijg steeds vreemde e-mails van iemand die beweert dat zij mijn \"aanbidster\" is. Ze komen van anoniem@arque.local.",
	"ChrisLine3": "Dit is een fragment van een van die e-mails:",
	"ChrisLine4": "Ik waardeer dat we recent onze onenigheden hadden, maar ik heb hier hulp bij nodig... eerst was het vreemd, nu is het gewoonweg eng. Kan dit tellen als officiële klacht?",
	"ChrisLine5": "Christian",
	"MeetMeTitle": "Waarom heb je me niet ontmoet?",
	"MeetMeSummary": "Ik was helemaal alleen in de...",
	"MeetMeLine1": "Ik was helemaal alleen in de lunchzaal. Ik wilde je zien eten maar je kwam niet! Maak ik je bang?",
	"MeetMeLine2": "Ik beloof dat ik niet zo ben. Luister, we kunnen het morgen opnieuw proberen. Ik zal op je wachten.",
	"HandledTheManagerTitle": "Ik zag de manier waarop je met de manager omging",
	"HandledTheManagerSummary": "Ik vond de manier...",
	"HandledTheManagerLine1": "Ik vond de manier waarop je vandaag met de manager omging echt geweldig. Je bent een beest wanneer je kwaad bent. Ik vond de manier waarop het zweet van je dubbele kin droop geweldig... er is gewoon iets mee.",
	"JonathanBillyName": "Jonathan Billy",
	"JonathanBillyAccount": "Jonathan Billy < jonathan.billy@arque.local >",
	"JonathanBillyLine1": "werk je op vrijdag",
	"JonathanBillyLine2": "mn dogter heef een zwemwedstreid en vrouw zegt datk moet gaan. kan je mn dienst overnemen",
	"JonathanBillyLine3": "bedankt",
	"JonathanBillyLine4": "van jono",
	"DavidGravenName": "David Graven",
	"DavidGravenAccount": "David Graven < david.graven@arque.local >",
	"DavidGravenTitle1": "RE: vrijdag",
	"DavidGravenTitle2": "Dozen",
	"DavidGravenSummary1": "Oké, geniet van je dag :)",
	"DavidGravenSummary2": "Kunnen we een paar van de dozen verplaatsen",
	"DavidGravenEmail1": "Jono,",
	"DavidGravenEmail2": "Kunnen we een paar van de dozen verplaatsen naar het pakhuis bij Arque East? Ze zeggen dat er nog meer bijkomen maar er passen er hier geen meer bij - hetzelfde trouwens met de grote voorraadkisten. Ik zal het er eens over hebben met Jeff... ze waren van plan er uiteindelijk een paar naar boven te halen.",
	"DavidGravenSig": "Dave",
	"JonathanBillyTitle": "vrijdag",
	"JeffHerbandTitle": "Inkomend...",
	"JeffHerbandSummary": "Er komen meer dozen binnen",
	"JeffHerbandAccount": "Jeff Herband < jeff.herband@arque.local >",
	"JeffHerbandName": "Jeff Herband",
	"JeffHerbandSig": "Arque West, magazijnmanager",
	"JeffHerbandLine1": "Er komen meer dozen binnen. Vergeet ze niet veilig op te slaan, we willen niet dat er dingen breken.",
	"WentworthHeraldTitle": "Wentworths Dagblad",
	"WentworthHeraldTagline": "De eerste als het op nieuws, roddels, sport, showbiz, zaken en kruiswoordpuzzels aankomt.",
	"MoreOnPage7": "Meer op pagina 7",
	"MoreOnPage10": "Meer op pagina 10",
	"LighthouseDecomissionedTitle": "Vuurtoren buiten gebruik gesteld",
	"LighthouseDecomissionedParagraph1": "De vuurtoren op de landtong in Redton zal door de plaatselijke burgemeester John Menn buiten gebruik gesteld worden na een onderzoek van de kustwacht.",
	"LighthouseDecomissionedParagraph2": "\"We vertrouwen erop dat dit geen invloed zal hebben op het doorkomende verkeer\", zei Bill Hayak van het Ministerie van Maritiem Verkeersonderzoek. \"Waar vroeger vrachtschepen te zien waren langs de kust van Redton, is dat nu niet langer het geval en worden scheepvaartroutes vanaf het vasteland gewijzigd\", voegde hij toe.",
	"LighthouseDecomissionedParagraph3": "Bij vraagstelling weigerde de burgemeester commentaar te geven totdat hij een officiële verklaring afgelegd had over de sluiting van de vuurtoren.",
	"LighthouseDecomissionedParagraph4": "De plaatselijke bevolking is niet te spreken over de verandering. Eén inwoner was bezorgd over de effecten op kleine handelsvaartuigen die nog aanleggen aan de eilanden en zei dat het de laatste nagel aan de doodskist was voor het rustige dok op het eiland. \"Het stopt veel van de handel van het eiland\", zei hij.",
	"LighthouseDecomissionedParagraph5": "Op bepaalde momenten is de vuurtoren het enige dat ervoor zorgt dat kleinere schepen hierheen komen en handel drijven met de lokale winkels. Het is iets waar we allemaal bezorgd om zijn. Wat zal er gebeuren als er hier geen importhandel meer is?",
	"LighthouseDecomissionedQuote": "\"Te weinig\" schepen om veiligheidsprobleem te vormen, zegt kustwacht",
	"LostTitle": "Zoek",
	"LostParagraph1": "Twee weken zijn voorbijgegaan sinds lokale Arque-medewerker Christian Plithe zijn zwarte kat 'Lucky' verloor. Hij heeft iedereen die de kat ziet aangespoord om onmiddellijk contact met hem op te nemen.",
	"ScarecrowCompetitionTitle": "Lokale vogelverschrikkercompetitie aan de gang",
	"ScarecrowCompetitionParagraph1": "Eén van de populairste competities van Redton is terug voor zijn jaarlijkse evenement.",
	"ScarecrowCompetitionParagraph2": "De gemeenschap organiseert elk jaar een bijeenkomst om de meest angstaanjagende en demonische vogelverschrikkers te maken en zo de vogels weg te jagen. De achtjarige winnaar van vorig jaar, de schooljongen Joshua Fenton, had met zijn weergave van zijn grootmoeder de jury overtuigd.",
	"ScarecrowCompetitionParagraph3": "Dit jaar krijgt de winnaar van de wedstrijd een fijne selectie van cakejes van Julia Menn, de echtgenote van de burgemeester die recent een eigen cakejeswinkel opende op het eiland.",
	"ScarecrowCompetitionParagraph4": "De feestelijkheden stoppen niet bij de vogelverschrikkers die de hele week tentoongesteld staan: er zijn ook standjes en andere activiteiten verspreid over het hele dorp. Als je de vogelverschrikkers nog niet hebt gezien, ga dan naar het jaarlijks evenement om te zien waar al het gedoe om gaat en proef er enkele van de beste dranken en gerechten die Redton te bieden heeft.",
	"ScarecrowCompetitionParagraph5": "Als je de vogelverschrikkers niet kunt bekijken, moet je maar eens kijken in onze volgende uitgave waar we een leuk overzicht geven van de inzendingen.",
	"OmnicorpTitle": "Arque Corporation neemt Phillips Pharmaceuticals over",
	"OmnicorpParagraph1": "Dertig werknemers kregen begin vorige week een melding dat de gigantische Arque Corpopration de overname van het lokale farmaceutisch bedrijf Phillips Pharmaceuticals had voltooid. De buy-out volgt op een zeer publieke zenuwinzinking van de vorige eigenaar en de daaropvolgende zoektocht naar investeerders.",
});