ae.addLanguage("portuguese", {
	"GameTitle": "Estranged",
	"GameSubtitle": "Act I",
	"Language": "portuguese",
	"Close": "para fechar",
	"CreditsWithThanksTo": "Agradecimentos a",
	"CreditsTeam": "Equipa de Desenvolvimento",
	"CreditsMainMenu": "Voltar ao menu principal",
	"CreditsCreator": "Criador",
	"CreditsVoices": "Vozes",
	"CreditsPreviousVoices": "Vozes Anteriores",
	"CreditsTranslators": "Tradutores",
	"CreditsTesters": "Testadores",
	"CreditsMacOSBuild": "Versão Mac OS",
	"CreditsDanishTranslator": "Tradutor de Dinamarquês",
	"CreditsMapCompiler": "Compilador de Mapas",
	"CreditsTranslator": "Tradutor(a)",
	"CreditsTester": "Testador",
	"CreditsPhotographer": "Fotógrafo",
	"CreditsGuitarSamples": "Guitarrista",
	"CreditsProjectLead": "Líder de Projeto",
	"CreditsLevelDesigner": "Designer de Níveis",
	"CreditsProgrammer": "Programador",
	"CreditsStoryDesigner": "Argumentista",
	"CreditsTextureArtist": "Artista de Texturas",
	"CreditsModelArtist": "Artista de Modelos 3D",
	"CreditsVoiceOf": "Voz de",
	"CreditsLeadMusician": "Músico Principal",
	"CreditsShaderArtist": "Artista de Shaders",
	"CreditsOmnicorpThug": "Guarda da Arque",
	"CreditsOmnicorpBroadcaster": "Locutora da Arque",
	"CreditsMirrorHosting": "Hospedagem de Servidores",
	"CreditsAudioDesigner": "Designer de Áudio",
	"CreditsOculusRift": "Contribuição do Oculus Rift",
	"CreditsDonors": "Doações ao Projeto",
	"CreditsSteamTranslation": "Steam Translation Server",
	"Workstation": "Terminal nº",
	"EndSession": "Deseja terminar a sua sessão?",
	"OK": "OK",
	"Cancel": "Cancelar",
	"IconEmail": "E-Mail",
	"IconLogOff": "Terminar Sessão",
	"IconDoorUnlock": "Abertura de Portas",
	"OnlyPrintIfNecessary": "Proteja o ambiente. Imprima este e-mail só se for mesmo necessário.",
	"Incorrect": "Lamentamos, mas a resposta está incorreta.",
	"SecretPetName": "alex",
	"DialogGenerator": "Painel de Controlo de Gerador",
	"DialogGeneratorOverHeat": "AVISO: GERADOR A SOBREAQUECER",
	"DialogGeneratorDisconnect": "DESCONECTAR PAINEL DE CONTROLO DE GERADOR",
	"YantoWardName": "Yanto Ward",
	"YantoWardAccount": "Yanto Ward < yanto.ward@arque.local >",
	"Pets_R_Us_Update": "Notícias da Pets Are Us",
	"Pets_R_Us_UpdateSummary": "Sr. Ward, o Alex recuperou...",
	"Pets_R_Us_From": "Pets Are Us < judy@petsrus.com >",
	"Pets_R_Us_Line1": "Sr. Ward,",
	"Pets_R_Us_Line2": "O seu cão Alex está a recuperar e reagiu muito bem aos medicamentos que lhe temos dado.",
	"Pets_R_Us_Line3": "Poderá buscar o Alex na segunda-feira.",
	"Pets_R_Us_Line4": "Obrigada,",
	"Pets_R_Us_Line5": "Judy Ferrand",
	"WhatIsThatSmell": "QUE CHEIRO É ESTE",
	"Srsly": "sinceramente...",
	"NigelHeathcoat": "Nigel Heathcoat < nigel@arque.local >",
	"HaveYouSeenMyLunch": "Viste o meu almoço?",
	"HaveYouSeenMyLunchSummary": "Oi, viste o meu...",
	"FrancisRobella": "Francis Robella < francis@arque.local >",
	"FrancisRobellaLine1": "Oi,",
	"FrancisRobellaLine2": "Viste o meu almoço? Deixei-o no frigorífico e desapareceu. Se descobrir que ela mo tirou de novo vou ficar irritado. Ela está sempre a roubar as minhas coisas!",
	"FrancisRobellaLine3": "Francis",
	"PleaseEnterSecretAnswer": "Por favor, introduza a resposta correta à pergunta secreta para prosseguir:",
	"NameOfPet": "Qual é o nome do seu animal de estimação?",
	"UnlockAllDoorsPrompt": "Clique no botão abaixo para desbloquear todas as portas no piso amarelo.",
	"UnlockAllDoors": "Desbloquear Todas as Portas",
	"DoorsAreUnlocked": "Todas as portas no piso amarelo estão agora desbloqueadas.",
	"Image1": "IMG_0270_104942.JPEG",
	"Image2": "IMG_0430_104912.JPEG",
	"Image3": "IMG_0430_104944.JPEG",
	"Image4": "IMG_0470_104454.JPEG",
	"Image5": "IMG_0437_104954.JPEG",
	"Image6": "IMG_0440_104964.JPEG",
	"Image7": "IMG_0437_104964.JPEG",
	"Image8": "MOV_034324_432432.MP4",
	"ChristianPlitheName": "Christian Plithe",
	"ChristianPlitheAccount": "Christian Plithe < christian.plithe@arque.local >",
	"LunchRoomTitle": "Refeitório",
	"LunchRoomSummary": "Christian, não consigo parar...",
	"LunchRoomLine1": "Christian, não consigo parar de pensar em ti. Desde o momento que te vi pela primeira vez no refeitório, eu sabia que eras o tal. Ainda me lembro daquelas asas de frango gordurosas a tocarem suavemente nos teus lábios... ---------- és um homem muito poderoso. Espero ver-te lá à mesma hora amanhã. Eu estarei a ver...",
	"AdmirerName": "A tua admiradora",
	"AdmirerAccount": "Admiradora < anonymous@arque.local >",
	"WilliamShortAccount": "William Short < william.short@arque.local >",
	"WilliamShortSig": "William Short, Gerente de Produção.",
	"WilliamShortTitle": "RE: Assédio",
	"WilliamShortSummary": "Christian, comuniquei isto aos RH...",
	"WilliamShortLine1": "Olá Christian,",
	"WilliamShortLine2": "Comuniquei isto aos Recursos Humanos e ao Suporte Interno, eles vão tentar localizar a tal \"admiradora\".",
	"WilliamShortLine3": "Tens de admitir que esta situação toda é hilariante...",
	"ChrisLine1": "Olá Will,",
	"ChrisLine2": "Tenho andado a receber estes e-mails muito estranhos de alguém que afirma ser a minha \"admiradora\", e também estão a vir do endereço 'anonymous@arque.local'.",
	"ChrisLine3": "Aqui está um excerto de um deles:",
	"ChrisLine4": "Estou consciente que tivemos as nossas divergências recentemente, mas preciso mesmo de ajuda com isto... de início era estranho, mas agora é completamente assustador. Isto pode contar como uma queixa oficial?",
	"ChrisLine5": "Christian",
	"MeetMeTitle": "Porque é que não foste ter comigo?",
	"MeetMeSummary": "Estava sozinha no...",
	"MeetMeLine1": "Estava sozinha no refeitório, eu queria ver-te a comer, mas não vieste! Estou a assustar-te?",
	"MeetMeLine2": "Juro que não sou assim... mas olha, podemos tentar de novo amanhã. Eu estarei à espera.",
	"HandledTheManagerTitle": "Vi a maneira como lidaste com o gerente",
	"HandledTheManagerSummary": "Gostei mesmo da...",
	"HandledTheManagerLine1": "Gostei mesmo da maneira como lidaste com o gerente hoje, ficas uma fera quando te zangas. Também gostei da maneira como o suor corria pelas banhas do teu pescoço... há algo nisso que me cativa.",
	"JonathanBillyName": "Jonathan Billy",
	"JonathanBillyAccount": "Jonathan Billy < jonathan.billy@arque.local >",
	"JonathanBillyLine1": "tas no turnu na sexta?",
	"JonathanBillyLine2": "a minha flha tem uma competissao de nataçao e a mnha mulher diz k tenho d ir. podes me subestituires no turnu?",
	"JonathanBillyLine3": "bigado",
	"JonathanBillyLine4": "do jono",
	"DavidGravenName": "David Graven",
	"DavidGravenAccount": "David Graven < david.graven@arque.local >",
	"DavidGravenTitle1": "RE: sexta",
	"DavidGravenTitle2": "Caixas",
	"DavidGravenSummary1": "Está bem, aproveita o dia :)",
	"DavidGravenSummary2": "Podemos transferir algumas das caixas?",
	"DavidGravenEmail1": "Jono,",
	"DavidGravenEmail2": "Podemos transferir algumas das caixas para o armazém na Arque Este? Eles dizem que há mais a caminho mas não conseguimos guardar mais aqui dentro - ainda por cima com os contentores aqui. Hei de falar com o Jeff acerca disso... eles devem levar algumas delas cá para cima eventualmente.",
	"DavidGravenSig": "Dave",
	"JonathanBillyTitle": "sexta",
	"JeffHerbandTitle": "A caminho...",
	"JeffHerbandSummary": "Há mais caixas a caminho",
	"JeffHerbandAccount": "Jeff Herband < jeff.herband@arque.local >",
	"JeffHerbandName": "Jeff Herband",
	"JeffHerbandSig": "Arque Oeste, Gerente de Armazém",
	"JeffHerbandLine1": "Há mais caixas a caminho. Lembrem-se de mantê-las bem arrumadas, não queremos que nada se parta.",
	"WentworthHeraldTitle": "Wentworth Herald",
	"WentworthHeraldTagline": "O nº 1 em notícias, sociedade, desporto, celebridades, negócios e palavras-cruzadas. O seu jornal, a sua vida.",
	"MoreOnPage7": "Mais na página 7",
	"MoreOnPage10": "Mais na página 10",
	"LighthouseDecomissionedTitle": "Farol Desativado",
	"LighthouseDecomissionedParagraph1": "O farol situado na costa de Redton está agendado para ser desativado em breve pelo presidente da localidade, John Menn, após uma investigação levada a cabo pelo guarda costeiro local.",
	"LighthouseDecomissionedParagraph2": "\"Estamos confiantes que isto não irá afetar qualquer tráfego que passa na zona\" comentou Bill Hayak, do Departamento de Investigação de Tráfego Marítimo, \"enquanto que há algum tempo era possível ver cargueiros perto da costa de Redton, agora já não é possível devido a rotas comerciais vindas do continente terem sido alteradas\", acrescentou.",
	"LighthouseDecomissionedParagraph3": "Quando interrogado, o presidente recusou-se a comentar sobre o assunto até que uma declaração oficial acerca do encerramento do farol fosse publicada.",
	"LighthouseDecomissionedParagraph4": "Os residentes locais não estão contentes com a notícia, um residente local mostrou-se preocupado com os seus efeitos em navios pequenos que ainda descarregam mercadorias na ilha, afirmando que este foi o último prego no caixão para o sossegado porto da ilha. \"Impede muitas das transações que são efetuadas na ilha\", disse ele.",
	"LighthouseDecomissionedParagraph5": "Algumas vezes o farol é a única coisa que permite com que navios mais pequenos venham e negociem com comerciantes locais, é algo com que todos nós estamos preocupados - o que acontecerá quando não houverem mais negócios de importação aqui?",
	"LighthouseDecomissionedQuote": "\"Não há navios suficientes para que isto seja considerado um problema de segurança\", afirma o guarda costeiro",
	"LostTitle": "Perdido",
	"LostParagraph1": "Já passaram duas semanas desde que Christian Plithe, um empregado local da Arque perdeu o seu gato preto 'Lucky'. Christian encoraja àqueles que virem o gato para contactá-lo imediatamente.",
	"ScarecrowCompetitionTitle": "Competição Local de Espantalhos a Decorrer",
	"ScarecrowCompetitionParagraph1": "Uma das competições mais populares de Redton está de volta para a sua edição deste ano.",
	"ScarecrowCompetitionParagraph2": "A comunidade junta-se todos os anos para criar alguns dos espantalhos mais assustadores e mórbidos para afastar as aves. O vencedor do ano passado foi Joshua Fenton, um aluno de oito anos cuja representação visual da sua avó conquistou o júri.",
	"ScarecrowCompetitionParagraph3": "O vencedor da competição deste ano receberá uma bela variedade de bolos da Julia Menn, a esposa do presidente que abriu recentemente a sua pastelaria na ilha.",
	"ScarecrowCompetitionParagraph4": "Mas as festividades não acabam com os espantalhos - que estão em exposição durante a semana inteira; também há barracas de jogos e de comida, e outras atividades a decorrer em diversos locais na vila. Se ainda não viu os espantalhos, dirija-se ao evento para ver o porquê de tanto alarido e prove alguns dos melhores pratos e bebidas que Redton tem para oferecer.",
	"ScarecrowCompetitionParagraph5": "Se não puder vir até Redton para ver os espantalhos, pode verificar a próxima edição, onde vamos apresentar uma análise completa das criações dos participantes.",
	"OmnicorpTitle": "Arque Completa Aquisição da Phillips Pharmaceuticals",
	"OmnicorpParagraph1": "Trinta trabalhadores foram notificados no início da semana passada quando a empresa gigante 'Arque Corporation' completou a aquisição do fabricante farmacêutico local 'Phillips Pharmaceuticals'. A aquisição ocorreu após o dono anterior ter tido um colapso emocional em público, resultando num aumento de procura para investidores.",
});