ae.addLanguage("romanian", {
	"GameTitle": "Estranged",
	"GameSubtitle": "Act I",
	"Language": "romanian",
	"Close": "Închide",
	"CreditsWithThanksTo": "Mulțumiri lui",
	"CreditsTeam": "Echipa",
	"CreditsMainMenu": "Treci la meniul principal",
	"CreditsCreator": "Creator",
	"CreditsVoices": "Voci",
	"CreditsPreviousVoices": "Voci anterioare",
	"CreditsTranslators": "Traducători",
	"CreditsTesters": "Testeri",
	"CreditsMacOSBuild": "Versiune SO Mac",
	"CreditsDanishTranslator": "Traducător daneză",
	"CreditsMapCompiler": "Cimpilator de hartă",
	"CreditsTranslator": "Traducător",
	"CreditsTester": "Tester",
	"CreditsPhotographer": "Fotograf",
	"CreditsGuitarSamples": "Mostre de chitară",
	"CreditsProjectLead": "Conducătorii proiectului",
	"CreditsLevelDesigner": "Designer Nivel",
	"CreditsProgrammer": "Programator",
	"CreditsStoryDesigner": "Designer Poveste",
	"CreditsTextureArtist": "Artist texturi",
	"CreditsModelArtist": "Artist Modele 3D",
	"CreditsVoiceOf": "Vocile lui",
	"CreditsLeadMusician": "Muzician conducător",
	"CreditsShaderArtist": "Artist Shader",
	"CreditsOmnicorpThug": "Golan Arque",
	"CreditsOmnicorpBroadcaster": "Prezentator Arque",
	"CreditsMirrorHosting": "Găzduire Mirror pentru descărcare",
	"CreditsAudioDesigner": "Designer Audio",
	"CreditsOculusRift": "Oculus Rift donat",
	"CreditsDonors": "Donatori ai proiectului",
	"CreditsSteamTranslation": "Server-ul Steam Translation",
	"Workstation": "Stație de lucru",
	"EndSession": "Vrei să închei sesiunea?",
	"OK": "OK",
	"Cancel": "Anulează",
	"IconEmail": "Email",
	"IconLogOff": "Deconectare",
	"IconDoorUnlock": "Deschidere ușă",
	"OnlyPrintIfNecessary": "Ocrotește mediul. Tipărește acest email doar dacă este strict necesar.",
	"Incorrect": "Ne pare rău, a fost incorect.",
	"SecretPetName": "alex",
	"DialogGenerator": "Consolă Generator",
	"DialogGeneratorOverHeat": "ATENȚIE: GENERATORUL SE SUPRAÎNCĂLZEȘTE",
	"DialogGeneratorDisconnect": "DECONECTEAZĂ-TE DE LA CONSOLA GENERATORULUI",
	"YantoWardName": "Yanto Ward",
	"YantoWardAccount": "Yanto Ward < yanto.ward@arque.local >",
	"Pets_R_Us_Update": "Actualizarea Animalele este Noi",
	"Pets_R_Us_UpdateSummary": "Domnule Ward, Alex s-a recuperat...",
	"Pets_R_Us_From": "Animalele este Noi < judy@petsrus.com >",
	"Pets_R_Us_Line1": "Domnule Ward,",
	"Pets_R_Us_Line2": "Câinele tău, Alex, se recuperează și a răspuns foarte bine la medicamentele administrate.",
	"Pets_R_Us_Line3": "Îl vei putea prelua pe Alex luni.",
	"Pets_R_Us_Line4": "Mulțumesc,",
	"Pets_R_Us_Line5": "Judy Ferrand.",
	"WhatIsThatSmell": "CE E MIROSUL ĂSTA",
	"Srsly": "serios",
	"NigelHeathcoat": "Nigel Heathcoat < nigel@arque.local >",
	"HaveYouSeenMyLunch": "Mi-ai văzut prânzul?",
	"HaveYouSeenMyLunchSummary": "Hei, mi-ai vazut...",
	"FrancisRobella": "Francis Robella < francis@arque.local >",
	"FrancisRobellaLine1": "Hei,",
	"FrancisRobellaLine2": "Mi-ai văzut prânzul? L-am lăsat în frigider și a dispărut. Dacă l-a furat ea din nou, o să cedez nervos. Totdeauna îmi fură lucrurile!",
	"FrancisRobellaLine3": "Francis",
	"PleaseEnterSecretAnswer": "Te rugăm să introduci răspunsul la întrebarea secretă pentru a continua:",
	"NameOfPet": "Care este numele animalului tău de casă?",
	"UnlockAllDoorsPrompt": "Folosește butonul de mai jos pentru a deschide toate ușile de la etajul galben.",
	"UnlockAllDoors": "Descuie Toate Ușile",
	"DoorsAreUnlocked": "Toate ușile de la etajul galben sunt acum descuiate.",
	"Image1": "IMG_0270_104942.JPEG",
	"Image2": "IMG_0430_104912.JPEG",
	"Image3": "IMG_0430_104944.JPEG",
	"Image4": "IMG_0470_104454.JPEG",
	"Image5": "IMG_0437_104954.JPEG",
	"Image6": "IMG_0440_104964.JPEG",
	"Image7": "IMG_0437_104964.JPEG",
	"Image8": "IMG_034324_432432.MP4",
	"ChristianPlitheName": "Christian Plithe",
	"ChristianPlitheAccount": "Christian Plithe < christian.plithe@arque.local >",
	"LunchRoomTitle": "Sala de Mese",
	"LunchRoomSummary": "Christian, nu mă pot opri...",
	"LunchRoomLine1": "Christian, nu pot să mă opresc să mă gândesc la tine. Din momentul în care te-am văzut prima oară în sala de mese am știut că tu erai alesul. De la aripioarele grase de pui ce se freacă încet de buzele tale ---------- ești un om foarte puternic. Sper să te văd acolo mâine la aceeași oră. Voi urmări cu atenție...",
	"AdmirerName": "Admiratorul tău",
	"AdmirerAccount": "Admirator < anonymous@arque.local >",
	"WilliamShortAccount": "William Short < william.short@arque.local >",
	"WilliamShortSig": "William Short, manager de producție.",
	"WilliamShortTitle": "RE: Hărțuire",
	"WilliamShortSummary": "Christian, am raportat asta către RU...",
	"WilliamShortLine1": "Salut Christian,",
	"WilliamShortLine2": "Am raportat asta către RU și Suport Intern, vor încerca să dea de urma \"admiratorului\".",
	"WilliamShortLine3": "Trebuie să recunoști că toată chestia asta e amuzantă...",
	"ChrisLine1": "Salut Will,",
	"ChrisLine2": "Primesc încontinuu aceste email-uri foarte dubioase de la cineva care pretinde că este \"admiratorul\" meu, vin și de la anonymous@arque.local.",
	"ChrisLine3": "Iată un pasaj dintr-unul:",
	"ChrisLine4": "Apreciez faptul că am avut neînțelegerile noastre în ultima vreme, dar am nevoie de ajutor cu asta... la început era ciudat, acum e de-a dreptul înfricoșător. Asta se poate pune ca o plângere oficială?",
	"ChrisLine5": "Christian",
	"MeetMeTitle": "De ce nu te-ai întâlnit cu mine?",
	"MeetMeSummary": "Eram numai eu în...",
	"MeetMeLine1": "Eram numai eu în sala de mese, doream să te urmăresc cum mănânci dar tu nu ai venit! Te sperii?",
	"MeetMeLine2": "Îți promit că nu sunt așa, uite, putem încerca din nou mâine. Voi aștepta.",
	"HandledTheManagerTitle": "Am văzut cum te-ai descurcat cu managerul",
	"HandledTheManagerSummary": "Mi-a plăcut foarte mult...",
	"HandledTheManagerLine1": "Mi-a plăcut foarte mult cum te-ai descurcat cu managerul astăzi, ești o bestie când ești furios. Mi-a plăcut cum se scurgea sudoarea pe cea de-a doua barbă a ta... e ceva cu chestia aia.",
	"JonathanBillyName": "Jonathan Billy",
	"JonathanBillyAccount": "Jonathan Billy < jonathan.billy@arque.local >",
	"JonathanBillyLine1": "u ești în tură vineri",
	"JonathanBillyLine2": "ficamea are un concurs de inot și sotia zice  trebe sa merg. poti sami acoperi tu tura",
	"JonathanBillyLine3": "mulțumesc",
	"JonathanBillyLine4": "de la jono",
	"DavidGravenName": "David Graven",
	"DavidGravenAccount": "David Graven < david.graven@arque.local >",
	"DavidGravenTitle1": "RE: vineri",
	"DavidGravenTitle2": "Cutii",
	"DavidGravenSummary1": "E bine, să ai o zi bună :)",
	"DavidGravenSummary2": "Putem să mutăm niște cutii",
	"DavidGravenEmail1": "Jono,",
	"DavidGravenEmail2": "Putem să mutăm niște cutii în depozitul de la Arque East? Spuneau că mai vin și altele, dar nu mai avem loc de ele aici - de când cu cutiile de capacitate mare. O să discut cu Jeff despre asta... vor duce câteva sus odată și odată.",
	"DavidGravenSig": "Dave",
	"JonathanBillyTitle": "vineri",
	"JeffHerbandTitle": "Vine...",
	"JeffHerbandSummary": "Mai vin și alte cutii",
	"JeffHerbandAccount": "Jeff Herband < jeff.herband@arque.local >",
	"JeffHerbandName": "Jeff Herband",
	"JeffHerbandSig": "Arque West, Manager al depozitului",
	"JeffHerbandLine1": "Mai vin și alte cutii. Ai grijă să le depozitezi în siguranță, nu vrem să se spargă chestii.",
	"WentworthHeraldTitle": "Wentworth Herald",
	"WentworthHeraldTagline": "Primul la știri, bârfe, sport, showbiz, afaceri și integrame. E ziarul tău pentru o viață.",
	"MoreOnPage7": "Mai multe pe pagina 7",
	"MoreOnPage10": "Mai multe pe pagina 10",
	"LighthouseDecomissionedTitle": "Farul dezafectat",
	"LighthouseDecomissionedParagraph1": "Farul din Redton aflat pe peninsulă va fi dezafectat de către primarul local, John Menn, în urma unei investigații efectuate de către paza de coastă.",
	"LighthouseDecomissionedParagraph2": "\"Suntem convinși că nu va afecta traficul din zonă\" a declarat Bill Hayak de la Departamentul pentru Investigarea Traficului Maritim . \"Pe când mai demult puteai vedea vase de mărfuri chiar la coasta orașului Redton, acum nu mai este cazul dat fiind că rutele de transport de la continent sunt modificate\" a adăugat.",
	"LighthouseDecomissionedParagraph3": "Când i-au fost puse întrebări primarul a refuzat să facă vreun comentariu până când nu va elibera o declarație oficială cu privire la închiderea farului.",
	"LighthouseDecomissionedParagraph4": "Localnicii nu sunt mulțumiți cu schimbarea, un localnic era îngrijorat de efectele asupra vaselor comerciale mici care încă mai ancorează la insulă, spunând că e ultimul cui bătut în sicriul portului acestei insule liniștite. ”Pune capăt unei mari proporții din afacerile insulei” a spus acesta.",
	"LighthouseDecomissionedParagraph5": "Câteodată farul este singurul lucru care le permite vaselor mai mici să vină și să facă negoț cu comercianții locali, e ceva ce ne îngrijorează pe toți - ce se va întâmpla aici când nu va mai exista comerț de import?",
	"LighthouseDecomissionedQuote": "\"Prea puține\" vase pentru a fi o problemă de siguranță, spune paza de coastă",
	"LostTitle": "Pierdut",
	"LostParagraph1": "Au trecut două săptămâni de când angajatul local Arque, Christian Plithe, și-a pierdut pisica neagră 'Norocel'. A rugat să fie contactat de urgență de către oricine vede pisica.",
	"ScarecrowCompetitionTitle": "Competiția locală de sperietori este în desfășurare",
	"ScarecrowCompetitionParagraph1": "Una dintre cele mai populare competiții ținute în Redton a revenit pentru evenimentul anual.",
	"ScarecrowCompetitionParagraph2": "Comunitatea se reunește anual pentru a crea cele mai înfricoșătoare și macabre sperietori care să alunge păsările. Câștigătorul de anul trecut a fost un elev localnic de opt ani, Joshua Fenton, a cărui reprezentare a bunicii i-a adus favorurile juriului.",
	"ScarecrowCompetitionParagraph3": "Câștigătorul de anul acesta al competiției va primi o selecție fină de prăjituri de la Julia Menn, soția primarului, care și-a deschis recent o cofetărie pe insulă.",
	"ScarecrowCompetitionParagraph4": "Festivitățile nu se opresc cu sperietorile de ciori - ce sunt expuse toată săptămâna, sunt tarabe și alte activități ce se desfășoară în întreg orașul. Dacă încă nu ai văzut sperietorile de ciori îndreaptă-te spre evenimentul anual pentru a vedea ce e cu toată această agitație și degustă dintre cele mai bune mâncăruri și băuturi pe care le Redton le are de oferit.",
	"ScarecrowCompetitionParagraph5": "Dacă nu poți ajunge să vezi sperietorile, uită-te peste următoarea ediție, în care vom publica o listă completă cu înscrierile.",
	"OmnicorpTitle": "Arque Corporation achiziționează Phillips Pharmaceuticals",
	"OmnicorpParagraph1": "Trezeci de lucrători au primit înștiințări în urma finalizării procesului de achiziție a producătorului local de farmaceutice, Phillips Pharmaceuticals, de către gigantul Arque Corporation. Achiziția a fost o urmare a unei căderi nervoase în public a propietarului vechi, ceea ce a necesitat căutarea de noi investitori.",
});