ae.addLanguage("tchinese", {
	"GameTitle": "Estranged",
	"GameSubtitle": "Act I",
	"Language": "tchinese",
	"Close": "關閉",
	"CreditsWithThanksTo": "感謝",
	"CreditsTeam": "團隊",
	"CreditsMainMenu": "回到主選單",
	"CreditsCreator": "作者",
	"CreditsVoices": "配音",
	"CreditsTranslators": "翻譯人員",
	"CreditsTesters": "測試員",
	"CreditsMacOSBuild": "Mac OS 版本",
	"CreditsDanishTranslator": "丹麥文翻譯人員",
	"CreditsMapCompiler": "地圖整合",
	"CreditsTranslator": "翻譯人員",
	"CreditsTester": "測試人員",
	"CreditsGuitarSamples": "吉他採樣",
	"CreditsProjectLead": "計畫領導",
	"CreditsLevelDesigner": "關卡設計",
	"CreditsProgrammer": "程式設計",
	"CreditsStoryDesigner": "故事設計",
	"CreditsTextureArtist": "貼圖設計",
	"CreditsModelArtist": "3D 模型設計",
	"CreditsVoiceOf": "配音",
	"CreditsLeadMusician": "首席音樂家",
	"CreditsMirrorHosting": "下載鏡像託管",
	"CreditsAudioDesigner": "音效設計",
	"CreditsOculusRift": "捐贈 Oculus Rift",
	"CreditsDonors": "專案捐助者",
	"CreditsSteamTranslation": "The Steam Translation Server",
	"Workstation": "工作站",
	"EndSession": "您要結束程式嗎？",
	"OK": "確定",
	"Cancel": "取消",
	"IconEmail": "電子郵件",
	"IconLogOff": "登出",
	"IconDoorUnlock": "門已解鎖",
	"OnlyPrintIfNecessary": "為了保護環境，請您只在必要時列印這封電子郵件。",
	"Incorrect": "抱歉，輸入錯誤",
	"SecretPetName": "alex",
	"DialogGenerator": "發電機控制台",
	"DialogGeneratorOverHeat": "警告：發電機過熱中",
	"DialogGeneratorDisconnect": "登出發電機控制台",
	"YantoWardName": "洋特．沃德",
	"YantoWardAccount": "Yanto Ward < yanto.ward@arque.local >",
	"Pets_R_Us_UpdateSummary": "沃德先生您的狗 Alex 在使用...",
	"Pets_R_Us_From": "Pets Are Us < judy@petsrus.com >",
	"Pets_R_Us_Line1": "沃德先生",
	"Pets_R_Us_Line2": "您的狗 Alex 在使用了我們開出的藥劑之後恢復了活力。",
	"Pets_R_Us_Line3": "您可以在禮拜一將 Alex 帶回家。",
	"Pets_R_Us_Line4": "謝謝",
	"Pets_R_Us_Line5": "朱蒂．費爾倫",
	"WhatIsThatSmell": "什麼鬼味道呀",
	"Srsly": "我說真的",
	"NigelHeathcoat": "Nigel Heathcoat < nigel@arque.local >",
	"HaveYouSeenMyLunch": "你有看到我的午餐嗎？",
	"HaveYouSeenMyLunchSummary": "嘿你有看到我的午餐嗎？ 我...",
	"FrancisRobella": "Francis Robella < francis@arque.local >",
	"FrancisRobellaLine1": "嘿",
	"FrancisRobellaLine2": "你有看到我的午餐嗎？ 我把它放在冰箱裡然後就不見了。 如果又是她偷得我真的會發飆。 她每次都偷我東西！",
	"FrancisRobellaLine3": "法蘭西斯",
	"PleaseEnterSecretAnswer": "請輸入您設定的問題答案以繼續：",
	"NameOfPet": "您的寵物叫做什麼名字？",
	"UnlockAllDoorsPrompt": "點擊下面的按鈕以解開所有黃區的門鎖。",
	"UnlockAllDoors": "解開所有門的鎖",
	"DoorsAreUnlocked": "在黃區所有門的鎖已解開。",
	"Image1": "IMG_0270_104942.JPEG",
	"Image2": "IMG_0430_104912.JPEG",
	"Image3": "IMG_0430_104944.JPEG",
	"Image4": "IMG_0470_104454.JPEG",
	"Image5": "IMG_0437_104954.JPEG",
	"Image6": "IMG_0440_104964.JPEG",
	"Image7": "IMG_0437_104964.JPEG",
	"Image8": "IMG_034324_432432.MP4",
	"ChristianPlitheName": "克里斯汀．普賴",
	"ChristianPlitheAccount": "Christian Plithe < christian.plithe@arque.local >",
	"LunchRoomTitle": "餐廳",
	"LunchRoomSummary": "克里斯汀，我完全沒辦法不...",
	"LunchRoomLine1": "克里斯汀，我完全沒辦法不再繼續想著你。 從我在餐廳第一次見到你我就知道你就是個好男人。 從那油膩膩的雞翅膀緩緩的滑入你口中 ---------- 你是個非常有男人味的男人。 我希望我在明天同一個時間還能再見到你。 我會看著你...",
	"AdmirerName": "您的仰慕者",
	"AdmirerAccount": "Admirer < anonymous@arque.local >",
	"WilliamShortAccount": "William Short < william.short@arque.local >",
	"WilliamShortSig": "威爾森．薛特訊息管理員。",
	"WilliamShortTitle": "回覆：騷擾者",
	"WilliamShortSummary": "嗨克里斯汀我已經向人事部...",
	"WilliamShortLine1": "嗨克里斯汀",
	"WilliamShortLine2": "我已經向人事部和內層人員回報了那個情形，他們現在會想辦法查出那個「仰慕者」是誰。",
	"WilliamShortLine3": "你必須承認這整件事實在是有夠搞笑的...",
	"ChrisLine1": "嗨威爾",
	"ChrisLine2": "我一直不斷的收到從一個自稱自己是我的「仰慕者」寄來的信，還有信件全部都來自 anonymous@arque.local 這個信箱。",
	"ChrisLine3": "這是其中一封信的摘要：",
	"ChrisLine4": "我很明白最近我們之間有點小分歧但我需要一點幫助... 剛開始只是有點奇怪但現在變得好恐怖。 這算是一種正式的抱怨嗎？",
	"ChrisLine5": "克里斯汀",
	"MeetMeTitle": "怎麼都不來找我？",
	"MeetMeSummary": "我一直孤單地待在餐廳裡想...",
	"MeetMeLine1": "我一直孤單地待在餐廳裡想要看著你吃午餐，但是你一直沒有現身！ 難不成我嚇著你了？",
	"MeetMeLine2": "我發誓我不會在犯了，看看我們明天能不能再來一次。 等你喲。",
	"HandledTheManagerTitle": "我看到了你對付經理的方法",
	"HandledTheManagerSummary": "我真得很欣賞你今天...",
	"HandledTheManagerLine1": "我真得很欣賞你今天對付經理的方法，你生氣時像隻野獸。 我還很欣賞你汗流到你的雙下巴那樣... 這只是我順便想到的。",
	"JonathanBillyName": "喬納森．比利",
	"JonathanBillyAccount": "Jonathan Billy < jonathan.billy@arque.local >",
	"JonathanBillyLine1": "你周五還有班嗎",
	"JonathanBillyLine2": "我女兒游泳比賽我老婆還要我一定要去。 你可以代替我的班嗎",
	"JonathanBillyLine3": "謝囉",
	"JonathanBillyLine4": "喬諾留",
	"DavidGravenName": "大衛．葛雷芬",
	"DavidGravenAccount": "David Graven < david.graven@arque.local >",
	"DavidGravenTitle1": "回覆：周五",
	"DavidGravenTitle2": "箱子",
	"DavidGravenSummary1": "那天可要好好享受了 :)",
	"DavidGravenSummary2": "我們可以把一部分的箱子移走嗎",
	"DavidGravenEmail1": "喬諾",
	"DavidGravenEmail2": "我們可以把一部分的箱子送去 Arque 東區嗎？ 他們說還會在送來好幾箱 - 還包括幾箱大型補給箱，但我們這裡放不下了。 我會跟傑夫說... 他們得要搬好幾箱到樓上去。",
	"DavidGravenSig": "大衛",
	"JonathanBillyTitle": "周五",
	"JeffHerbandTitle": "要到了...",
	"JeffHerbandSummary": "又有更多的箱子要送來了",
	"JeffHerbandAccount": "Jeff Herband < jeff.herband@arque.local >",
	"JeffHerbandName": "傑夫．何班德",
	"JeffHerbandSig": "Arque 西區倉庫經理",
	"JeffHerbandLine1": "又有一堆箱子送來了。 記住要搬緊一點，我們不希望有東西損毀。",
	"WentworthHeraldTitle": "溫特沃斯報",
	"WentworthHeraldTagline": "新聞、八卦、體育、娛樂、商業以及填字遊戲首選。這是屬於您的報紙，屬於您的生活方式。",
	"MoreOnPage7": "詳情請翻閱第 7 頁",
	"MoreOnPage10": "詳情請翻閱第 10 頁",
	"LighthouseDecomissionedTitle": "燈塔關閉",
	"LighthouseDecomissionedParagraph1": "位於澳傑島的瑞德湯海邊的燈塔由當地市長約翰．梅恩聽從岸巡隊的調查報告提出即將關閉。",
	"LighthouseDecomissionedParagraph2": "「我們相信這並不會影響未來的交通往來」海洋交通調查局的比爾．哈耶克解釋，他另外補充：「本來是可以看到貨輪經過瑞德湯海岸，但在本島的航線改變之後這就不再是問題了」。",
	"LighthouseDecomissionedParagraph3": "當記者詢問市長時市長一直拒絕回應，一直到他提出關閉燈塔的正式聲明。",
	"LighthouseDecomissionedParagraph4": "當地居民不滿此作為，其中一位居民相當關注這對還會來到這停泊的小型商船的影響，認為這此舉對這個冷清的港口來說會是壓垮駱駝的最後一根稻草。「這中斷了這座島嶼的很多生意。」這位居民表示。",
	"LighthouseDecomissionedParagraph5": "有時候燈塔扮演著唯一能使小型商船前來當地貿易的重要角色，現在大家都在擔心的就是 - 不再有進口貿易後將來會有什麼發展？",
	"LighthouseDecomissionedQuote": "岸巡隊表示船隻數量「不足」釀成危險",
	"LostTitle": "尋寵啟示",
	"LostParagraph1": "本地 Arque 員工克里斯汀．普賴的寵物黑貓「Lucky」走失了兩個禮拜。飼主呼籲若有任何善心人士看見他的貓請立刻與他聯繫。",
	"ScarecrowCompetitionTitle": "稻草人大賽隆重舉行",
	"ScarecrowCompetitionParagraph1": "瑞德湯最熱門的年度競賽活動之一即將舉行。",
	"ScarecrowCompetitionParagraph2": "每年社區都會及結起來一同製做出最恐怖、最驚悚的稻草人來驅趕鳥群。去年的冠軍是一名八歲大就讀在地國小的喬許華．芬頓小朋友的作品「老阿嬤」贏得了評審們的注意。",
	"ScarecrowCompetitionParagraph3": "今年的冠軍將會獲得市長夫人朱莉亞．梅恩最在島上新開的蛋糕店精心挑選的精美蛋糕。",
	"ScarecrowCompetitionParagraph4": "慶祝活動和展示出來的稻草人會一直持續整個星期，此時整座城都會有擺攤還有各式各樣的活動舉辦著。假如你還沒見過那些稻草人，那就一定要親自走進這年度盛會中來看看那些稻草人同時來品嘗看看瑞德湯最有名的在地美食還有飲料。",
	"ScarecrowCompetitionParagraph5": "假使你沒辦法親自去看參賽的稻草人那麼就翻到下一頁，我們將在下一頁介紹所有參賽的稻草人。",
	"OmnicorpTitle": "Arque 公司併購菲利浦製藥",
});