ae.addLanguage("german", {
	"GameTitle": "Estranged",
	"GameSubtitle": "Act I",
	"Language": "german",
	"Close": "Schließen",
	"CreditsWithThanksTo": "Wir danken",
	"CreditsTeam": "Team",
	"CreditsMainMenu": "Zum Hauptmenü",
	"CreditsCreator": "Ersteller",
	"CreditsVoices": "Stimmen",
	"CreditsPreviousVoices": "Vorige Stimmen",
	"CreditsTranslators": "Übersetzer",
	"CreditsTesters": "Tester",
	"CreditsMacOSBuild": "Mac OS-Version",
	"CreditsDanishTranslator": "Dänischer Übersetzer",
	"CreditsMapCompiler": "Map-Compiler",
	"CreditsTranslator": "Übersetzer",
	"CreditsTester": "Tester",
	"CreditsPhotographer": "Fotograf",
	"CreditsGuitarSamples": "Gitarren-Samples",
	"CreditsProjectLead": "Projektleiter",
	"CreditsLevelDesigner": "Level-Designer",
	"CreditsProgrammer": "Programmierer",
	"CreditsStoryDesigner": "Story-Designer",
	"CreditsTextureArtist": "Textur-Ersteller",
	"CreditsModelArtist": "3D-Modell-Ersteller",
	"CreditsVoiceOf": "Stimme von",
	"CreditsLeadMusician": "Leitender Musiker",
	"CreditsShaderArtist": "Shader-Ersteller",
	"CreditsOmnicorpThug": "Arque-Schläger",
	"CreditsOmnicorpBroadcaster": "Arque-Sprecher",
	"CreditsMirrorHosting": "Download-Mirror-Hosting",
	"CreditsAudioDesigner": "Audiodesigner",
	"CreditsOculusRift": "Spendierte Oculus Rift",
	"CreditsDonors": "Projektspender",
	"CreditsSteamTranslation": "Steam Translation Server",
	"Workstation": "Computer",
	"EndSession": "Möchten Sie Ihre Sitzung beenden?",
	"OK": "OK",
	"Cancel": "Abbrechen",
	"IconEmail": "E-Mail",
	"IconLogOff": "Abmelden",
	"IconDoorUnlock": "Tür entriegeln",
	"OnlyPrintIfNecessary": "Denken Sie an die Umwelt. Drucken Sie diese E-Mail nur aus, wenn es sein muss.",
	"Incorrect": "Entschuldigung, das war falsch.",
	"SecretPetName": "alex",
	"DialogGenerator": "Generatorkonsole",
	"DialogGeneratorOverHeat": "WARNUNG: GENERATOR ÜBERHITZT",
	"DialogGeneratorDisconnect": "VON GENERATORKONSOLE ABMELDEN",
	"YantoWardName": "Yanto Ward",
	"YantoWardAccount": "Yanto Ward < yanto.ward@arque.local >",
	"Pets_R_Us_Update": "Pets Are Us - Update",
	"Pets_R_Us_UpdateSummary": "Mr Ward, Ihr Hund Alex erholt...",
	"Pets_R_Us_From": "Pets Are Us < judy@petsrus.com >",
	"Pets_R_Us_Line1": "Mr Ward,",
	"Pets_R_Us_Line2": "Ihr Hund Alex erholt sich und reagiert gut auf die Medikamente, die wir ihm verabreicht haben.",
	"Pets_R_Us_Line3": "Sie können Alex am Montag abholen.",
	"Pets_R_Us_Line4": "Danke,",
	"Pets_R_Us_Line5": "Judy Ferrand.",
	"WhatIsThatSmell": "WAS IST DAS FÜR EIN GESTANK",
	"Srsly": "ernsthaft",
	"NigelHeathcoat": "Nigel Heathcoat < nigel@arque.local >",
	"HaveYouSeenMyLunch": "Hast du mein Mittagessen gesehen?",
	"HaveYouSeenMyLunchSummary": "Hey, hast du mein Mittagessen...",
	"FrancisRobella": "Francis Robella < francis@arque.local >",
	"FrancisRobellaLine1": "Hey,",
	"FrancisRobellaLine2": "hast du mein Mittagessen gesehen? Ich habe es im Kühlschrank gelassen und jetzt ist es weg. Falls sie es schon wieder genommen hat, dreh ich durch. Sie nimmt immer meine Sachen!",
	"FrancisRobellaLine3": "Francis",
	"PleaseEnterSecretAnswer": "Bitte geben Sie die Antwort auf die Geheimfrage ein, um fortzufahren:",
	"NameOfPet": "Wie lautet der Name Ihres Haustiers?",
	"UnlockAllDoorsPrompt": "Benutzen Sie den Button unten, um alle Türen auf gelbem Boden zu entriegeln.",
	"UnlockAllDoors": "Alle Türen entriegeln",
	"DoorsAreUnlocked": "Alle Türen im gelben Geschoss sind zurzeit freigeschaltet.",
	"Image1": "IMG_0270_104942.JPEG",
	"Image2": "IMG_0430_104912.JPEG",
	"Image3": "IMG_0430_104944.JPEG",
	"Image4": "IMG_0470_104454.JPEG",
	"Image5": "IMG_0437_104954.JPEG",
	"Image6": "IMG_0440_104964.JPEG",
	"Image7": "IMG_0437_104964.JPEG",
	"Image8": "IMG_034324_432432.MP4",
	"ChristianPlitheName": "Christian Plithe",
	"ChristianPlitheAccount": "Christian Plithe < christian.plithe@arque.local >",
	"LunchRoomTitle": "Pausenraum",
	"LunchRoomSummary": "Christian, ich kann nicht aufhören...",
	"LunchRoomLine1": "Christian, ich kann nicht aufhören, an dich zu denken. Von dem Moment an, als ich dich das erste Mal im Pausenraum sah, wusste ich, dass du der Eine bist. Von den schmierigen Hähnchenflügeln, die langsam über deine Lippen rieben ---------- du bist ein sehr starker Mann. Ich hoffe, dass ich dich dort morgen um die selbe Zeit wiedersehe. Ich werde warten...",
	"AdmirerName": "Deine Verehrerin",
	"AdmirerAccount": "Verehrerin < anonymous@arque.local >",
	"WilliamShortAccount": "William Short < william.short@arque.local >",
	"WilliamShortSig": "William Short, Manager.",
	"WilliamShortTitle": "RE: Belästigung",
	"WilliamShortSummary": "Hi Christian, ich habe das dem Personalmanagement...",
	"WilliamShortLine1": "Hi Christian,",
	"WilliamShortLine2": "ich habe das dem Personalmanagement und dem internen Support gemeldet, die werden versuchen die \"Verehrerin\" aufzuspüren.",
	"WilliamShortLine3": "Du musst zugeben, dass die ganze Geschichte urkomisch ist...",
	"ChrisLine1": "Hi Will,",
	"ChrisLine2": "Ich kriege ständig diese seltsamen E-Mails von irgendwem, der behauptet meine \"Verehrerin\" zu sein, die kommen auch von anonymous@arque.local.",
	"ChrisLine3": "Hier ist ein Auszug aus einer:",
	"ChrisLine4": "Ich sehe ein, dass wir neulich einige Differenzen hatten, aber ich brauche hier Hilfe... zuerst war es komisch, jetzt ist es geradezu unheimlich. Kann dies als offizielle Beschwerde gelten?",
	"ChrisLine5": "Christian",
	"MeetMeTitle": "Warum hast du dich nicht mit mir getroffen?",
	"MeetMeSummary": "Ich war alleine im...",
	"MeetMeLine1": "Ich war alleine im Pausenraum. Ich wollte dir beim Essen zusehen, aber du bist nicht gekommen. Mache ich dir Angst?",
	"MeetMeLine2": "Ich verspreche, dass ich nicht so eine bin. Schau, wir können es morgen noch mal probieren. Ich werde warten.",
	"HandledTheManagerTitle": "Ich habe gesehen, wie du den Manager behandelt hast.",
	"HandledTheManagerSummary": "Ich mochte wirklich die...",
	"HandledTheManagerLine1": "Ich mochte wirklich die Art, wie du den Manager heute behandelt hast, du bist ein Tier, wenn du wütend bist. Ich mochte, wie der Schweiß von deinem Doppelkinn getropft ist... das hat was.",
	"JonathanBillyName": "Jonathan Billy",
	"JonathanBillyAccount": "Jonathan Billy < jonathan.billy@arque.local >",
	"JonathanBillyLine1": "hast du freitag dienst",
	"JonathanBillyLine2": "meine tochter hat nen schwimwettbewerb und meine frau sagt dass ich gehn muss. kannst du meine schicht übernemen",
	"JonathanBillyLine3": "danke",
	"JonathanBillyLine4": "von jono",
	"DavidGravenName": "David Graven",
	"DavidGravenAccount": "David Graven < david.graven@arque.local >",
	"DavidGravenTitle1": "RE: freitag",
	"DavidGravenTitle2": "Kisten",
	"DavidGravenSummary1": "Das ist gut, ich wünsche einen schönen Tag :)",
	"DavidGravenSummary2": "Können wir ein paar Kisten...",
	"DavidGravenEmail1": "Jono,",
	"DavidGravenEmail2": "Können wir ein paar Kisten ins Lager in Arque East bringen? Sie sagen, da kommen noch mehr, aber wir können hier keine mehr unterbringen – die großen Vorratskisten müssen auch weg. Ich werde mit Jeff darüber reden... Die sollen ein paar mit hoch nehmen.",
	"DavidGravenSig": "Dave",
	"JonathanBillyTitle": "freitag",
	"JeffHerbandTitle": "Lieferung...",
	"JeffHerbandSummary": "Es kommen noch mehr Kisten",
	"JeffHerbandAccount": "Jeff Herband < jeff.herband@arque.local >",
	"JeffHerbandName": "Jeff Herband",
	"JeffHerbandSig": "Arque West, Lager-Manager",
	"JeffHerbandLine1": "Es kommen noch mehr Kisten. Denken Sie daran, sie sicher aufzubewahren, wir wollen nicht, dass etwas kaputt geht.",
	"WentworthHeraldTitle": "Wentworth Herald",
	"WentworthHeraldTagline": "Die erste Wahl für Nachrichten, Klatsch, Sport, Showbiz, Wirtschaft und Kreuzworträtsel. Ihre Zeitung, Ihr Leben.",
	"MoreOnPage7": "Mehr auf Seite 7",
	"MoreOnPage10": "Mehr auf Seite 10",
	"LighthouseDecomissionedTitle": "Leuchtturm stillgelegt",
	"LighthouseDecomissionedParagraph1": "Der Leuchtturm auf der Landspitze in der Nähe von Redton wird auf Beschluss des Bürgermeisters John Menn nach einer von der Küstenwache durchgeführten Untersuchung stillgelegt.",
	"LighthouseDecomissionedParagraph2": "\"Wir sind zuversichtlich, dass dies keine Auswirkungen auf den Schiffsverkehr haben wird\", kommentierte Bill Hayak von der Abteilung für maritimen Verkehr. \"Zwar konnte man früher die Frachtschiffe an der Küste von Redton sehen, aber dies ist nicht mehr der Fall, seitdem die Schifffahrtslinien zum Festland geändert wurden\", fügte er hinzu.",
	"LighthouseDecomissionedParagraph3": "Weitere Fragen wollte der Bürgermeister bis zur Veröffentlichung einer offiziellen Erklärung zur Stilllegung des Leuchtturms nicht beantworten.",
	"LighthouseDecomissionedParagraph4": "Die Einwohner sind mit dieser Änderung nicht glücklich. Ein Bürger äußerte sich besorgt über die Auswirkungen auf kleine Handelsschiffe, die immer noch die Insel anlaufen. Er behauptete, dass dies der letzte Nagel im Sarg des Hafens sei. \"Viele Geschäfte auf der Insel fallen dadurch weg\", sagte er.",
	"LighthouseDecomissionedParagraph5": "Manchmal ist der Leuchtturm das einzige, das kleineren Schiffen den Einlauf in den Hafen und den Handel mit den Einwohnern ermöglicht. Darüber sind wir alle besorgt – was passiert, wenn es gar keine Importgeschäfte mehr geben wird?",
	"LighthouseDecomissionedQuote": "\"Zu wenig\" Schiffe, um ein Sicherheitsproblem darzustellen, sagt die Küstenwache",
	"LostTitle": "Gesucht",
	"LostParagraph1": "Bereits seit zwei Wochen vermisst der Arque-Mitarbeiter Christian Plithe seine schwarze Katze \"Lucky\". Er fordert jeden auf, der seine Katze gesehen haben könnte, sich sofort bei ihm zu melden.",
	"ScarecrowCompetitionTitle": "Lokaler Vogelscheuchen-Wettbewerb im Gange",
	"ScarecrowCompetitionParagraph1": "Einer der beliebtesten in Redton veranstalteten Wettbewerbe ist zurück.",
	"ScarecrowCompetitionParagraph2": "Die Gemeinde kommt jedes Jahr zusammen, um die furchterregendsten und schaurigsten Vogelscheuchen zu bauen. Der letztjährige Gewinner war der acht Jahre alte Schuljunge Joshua Fenton, der mit der Darstellung seiner Großmutter die Jury überzeugen konnte.",
	"ScarecrowCompetitionParagraph3": "Der diesjährige Gewinner des Wettbewerbs wird eine feine Auswahl an Kuchen von Julia Menn, der Frau des Bürgermeisters, die vor kurzem ihre eigene Konditorei auf der Insel eröffnet hat, erhalten.",
	"ScarecrowCompetitionParagraph4": "Die Feierlichkeiten hören nicht bei den Vogelscheuchen auf, die die ganze Woche ausgestellt sind. Es gibt in der ganzen Stadt Stände und andere Aktivitäten. Wenn Sie die Vogelscheuchen noch nicht gesehen haben, dann besuchen Sie die Veranstaltung, um zu sehen, was die ganze Aufregung soll, und probieren Sie das feinste Essen und die feinsten Getränke, die Redton zu bieten hat.",
	"ScarecrowCompetitionParagraph5": "Falls Sie verhindert sind, lesen Sie die nächste Ausgabe, in der wir alle Vogelscheuchen vorstellen werden.",
	"OmnicorpTitle": "Arque Corporation übernimmt Phillips Pharmaceuticals",
	"OmnicorpParagraph1": "Dreißig Arbeitern wurden Übernahmeangebote übergeben, als am Anfang der Woche Arque Corporation die Übernahme des Pharmaherstellers Phillips Pharmaceuticals abschloss. Die Übernahme folgte einem öffentlichen Zusammenbruch des vorherigen Besitzers, was zur Suche nach Investoren führte.",
});