ae.addLanguage("brazilian", {
	"GameTitle": "Estranged",
	"GameSubtitle": "Act I",
	"Language": "brazilian",
	"Close": "Fechar",
	"CreditsWithThanksTo": "Com agradecimentos a",
	"CreditsTeam": "Equipe",
	"CreditsMainMenu": "Voltar ao menu principal",
	"CreditsCreator": "Criador",
	"CreditsVoices": "Vozes",
	"CreditsPreviousVoices": "Vozes anteriores",
	"CreditsTranslators": "Tradutores",
	"CreditsTesters": "Testadores",
	"CreditsMacOSBuild": "Versão para Mac OS X",
	"CreditsDanishTranslator": "Tradutor para dinamarquês",
	"CreditsMapCompiler": "Compilador de mapas",
	"CreditsTranslator": "Tradutor",
	"CreditsTester": "Testador",
	"CreditsPhotographer": "Fotógrafo",
	"CreditsGuitarSamples": "Trechos de violão",
	"CreditsProjectLead": "Líder do projeto",
	"CreditsLevelDesigner": "Designer de níveis",
	"CreditsProgrammer": "Programador",
	"CreditsStoryDesigner": "Projetista da história",
	"CreditsTextureArtist": "Artista de texturas",
	"CreditsModelArtist": "Artista de modelagem 3D",
	"CreditsVoiceOf": "Voz de",
	"CreditsLeadMusician": "Músico-chefe",
	"CreditsShaderArtist": "Artista de shaders",
	"CreditsOmnicorpThug": "Bandido da Arque",
	"CreditsOmnicorpBroadcaster": "Locutor da Arque",
	"CreditsMirrorHosting": "Hospedagem de espelhos de download",
	"CreditsAudioDesigner": "Designer de áudio",
	"CreditsOculusRift": "Doou um Oculus Rift",
	"CreditsDonors": "Doadores do projeto",
	"CreditsSteamTranslation": "O Steam Translation Server",
	"Workstation": "Estação de trabalho",
	"EndSession": "Deseja finalizar esta sessão?",
	"OK": "OK",
	"Cancel": "Cancelar",
	"IconEmail": "E-mail",
	"IconLogOff": "Finalizar sessão",
	"IconDoorUnlock": "Destrancar porta",
	"OnlyPrintIfNecessary": "Proteja o meio ambiente. Só imprima este e-mail se for realmente necessário.",
	"Incorrect": "Desculpe, mas está incorreta.",
	"SecretPetName": "alex",
	"DialogGenerator": "Console do gerador",
	"DialogGeneratorOverHeat": "ALERTA: GERADOR SOBREAQUECENDO",
	"DialogGeneratorDisconnect": "FINALIZAR SESSÃO NO CONSOLE DO GERADOR",
	"YantoWardName": "Yanto Ward",
	"YantoWardAccount": "Yanto Ward < yanto.ward@arque.local >",
	"Pets_R_Us_UpdateSummary": "Sr. Ward, o Alex se recuperou...",
	"Pets_R_Us_Line1": "Sr. Ward,",
	"Pets_R_Us_Line2": "O seu cão Alex está se recuperando e reagiu muito bem aos medicamentos que estamos lhe administrando.",
	"Pets_R_Us_Line3": "Você poderá buscá-lo na próxima segunda.",
	"Pets_R_Us_Line4": "Obrigada,",
	"Pets_R_Us_Line5": "Judy Ferrand.",
	"WhatIsThatSmell": "QUE CHEIRO É ESSE",
	"Srsly": "sério",
	"HaveYouSeenMyLunch": "Você sabe onde tá o meu almoço?",
	"HaveYouSeenMyLunchSummary": "Ei, você viu o meu...",
	"FrancisRobella": "Francis Robella < francis@arque.local >",
	"FrancisRobellaLine1": "Ei,",
	"FrancisRobellaLine2": "Você viu o meu almoço? Deixei ele na geladeira e agora sumiu. Se foi ela de novo, ela vai ver só. Ela não para de roubar as minhas coisas!",
	"FrancisRobellaLine3": "Francis",
	"PleaseEnterSecretAnswer": "Por favor, insira a resposta da pergunta secreta para continuar:",
	"NameOfPet": "Qual o nome do seu animal de estimação?",
	"UnlockAllDoorsPrompt": "Use o botão abaixo para destrancar todas as portas no andar amarelo.",
	"UnlockAllDoors": "Destrancar todas as portas",
	"DoorsAreUnlocked": "Todas as portas no andar amarelo estão destrancadas.",
	"Image1": "IMG_0270_104942.JPEG",
	"Image2": "IMG_0430_104912.JPEG",
	"Image3": "IMG_0430_104944.JPEG",
	"Image4": "IMG_0470_104454.JPEG",
	"Image5": "IMG_0437_104954.JPEG",
	"Image6": "IMG_0440_104964.JPEG",
	"Image7": "IMG_0437_104964.JPEG",
	"Image8": "IMG_034324_432432.MP4",
	"ChristianPlitheName": "Christian Plithe",
	"LunchRoomTitle": "Refeitório",
	"LunchRoomSummary": "Christian, eu não consigo parar...",
	"LunchRoomLine1": "Christian, eu não consigo parar de pensar em você. Quando vi você no refeitório foi amor à primeira vista. Com as asas de galinha gordurosas tocando lentamente nos seus lábios ---------- você é um homem muito poderoso. Espero ver você lá amanhã na mesma hora. Ficarei de olho...",
	"AdmirerName": "Da sua admiradora,",
	"AdmirerAccount": "Admiradora < anonymous@arque.local >",
	"WilliamShortTitle": "RES: Perseguição",
	"WilliamShortSummary": "Christian, eu reportei isso ao RH...",
	"WilliamShortLine3": "Você tem que admitir que essa coisa toda é hilária...",
	"ChrisLine1": "Olá Will,",
	"MeetMeTitle": "Por que você não foi me encontrar?",
	"JonathanBillyAccount": "Jonathan Billy < jonathan.billy@arque.local >",
	"JonathanBillyLine1": "vc ta trabalhando na sexta",
	"JonathanBillyLine3": "obrigado",
	"JonathanBillyLine4": "do jono",
	"DavidGravenName": "David Graven",
	"DavidGravenTitle1": "RES: sexta-feira",
	"DavidGravenTitle2": "Caixas",
	"DavidGravenSummary2": "Nós podemos mandar algumas caixas",
	"DavidGravenSig": "Dave",
	"JeffHerbandAccount": "Jeff Herband < jeff.herband@arque.local >",
	"MoreOnPage7": "Mais na página 7",
	"MoreOnPage10": "Mais na página 10",
});