ae.addLanguage("greek", {
	"GameTitle": "Estranged",
	"GameSubtitle": "Act I",
	"Language": "greek",
	"Close": "Κλείσιμο",
	"CreditsWithThanksTo": "ΕΥΧΑΡΙΣΤΗΡΙΑ",
	"CreditsTeam": "ΟΜΑΔΑ",
	"CreditsMainMenu": "ΕΠΙΣΤΡΟΦΗ ΣΤΟ ΚΥΡΙΟ ΜΕΝΟΥ",
	"CreditsCreator": "Δημιουργός",
	"CreditsVoices": "ΦΩΝΕΣ",
	"CreditsPreviousVoices": "ΑΛΛΕΣ ΦΩΝΕΣ",
	"CreditsTranslators": "Μεταφραστές",
	"CreditsTesters": "ΔΟΚΙΜΑΣΤΕΣ",
	"CreditsMacOSBuild": "Έκδοση Mac OS",
	"CreditsDanishTranslator": "Δανός μεταφραστής",
	"CreditsMapCompiler": "Συνθέτης επιπέδων",
	"CreditsTranslator": "Μεταφραστής",
	"CreditsTester": "Δοκιμαστής",
	"CreditsPhotographer": "Φωτογράφος",
	"CreditsGuitarSamples": "Δείγματα κιθάρας",
	"CreditsProjectLead": "Αρχηγός έργου",
	"CreditsLevelDesigner": "Σχεδιαστής επιπέδων",
	"CreditsProgrammer": "Προγραμματιστής",
	"CreditsStoryDesigner": "Σεναριογράφος",
	"CreditsTextureArtist": "Δημιουργός υφών",
	"CreditsModelArtist": "Δημιουργός 3D μοντέλων",
	"CreditsVoiceOf": "Φωνή από",
	"CreditsLeadMusician": "Κύριος μουσικός",
	"CreditsShaderArtist": "Δημιουργός σκιών",
	"CreditsOmnicorpThug": "Κακοποιός Arque",
	"CreditsOmnicorpBroadcaster": "Μεταδότρια Arque",
	"CreditsMirrorHosting": "Φιλοξενία διαδικτυακής λήψης",
	"CreditsAudioDesigner": "Σχεδιαστής ήχου",
	"CreditsOculusRift": "Δωρεά Oculus Rift",
	"CreditsDonors": "Δωρητές έργου",
	"CreditsSteamTranslation": "Το Steam Translation Server",
	"Workstation": "Workstation",
	"EndSession": "Τερματισμός συνεδρίας;",
	"OK": "OK",
	"Cancel": "Άκυρο",
	"IconEmail": "Email",
	"IconLogOff": "Αποσύνδεση",
	"IconDoorUnlock": "Ξεκλείδωμα πόρτας",
	"OnlyPrintIfNecessary": "Σώστε το περιβάλλον. Εκτυπώστε αυτό το email μόνο αν πρέπει.",
	"Incorrect": "Συγγνώμη, αυτό δεν ήταν σωστό.",
	"SecretPetName": "alex",
	"DialogGenerator": "Κονσόλα γεννήτριας",
	"DialogGeneratorOverHeat": "ΠΡΟΣΟΧΗ: ΥΠΕΡΘΕΡΜΑΝΣΗ ΓΕΝΝΗΤΡΙΑΣ",
	"DialogGeneratorDisconnect": "ΑΠΟΣΥΝΔΕΣΗ ΑΠΟ ΚΟΝΣΟΛΑ ΓΕΝΝΗΤΡΙΑΣ",
	"YantoWardName": "Yanto Ward",
	"YantoWardAccount": "Yanto Ward < yanto.ward@arque.local >",
	"Pets_R_Us_Update": "Ενημέρωση από Pets Are Us",
	"Pets_R_Us_UpdateSummary": "Κύριε Ward, ο Alex ανάρρωσε...",
	"Pets_R_Us_From": "Pets Are Us < judy@petsrus.com >",
	"Pets_R_Us_Line1": "Mr Ward",
	"Pets_R_Us_Line2": "Ο σκύλος σας ο Alex αναρρώνει και ανταποκρίνεται θετικά στα φάρμακα που του δίνουμε.",
	"Pets_R_Us_Line3": "Θα μπορείτε να έρθετε να πάρετε τον Alex τη Δευτέρα.",
	"Pets_R_Us_Line4": "Ευχαριστώ",
	"Pets_R_Us_Line5": "Judy Ferrand.",
	"WhatIsThatSmell": "ΤΙ ΕΙΝΑΙ ΑΥΤΗ Η ΜΥΡΩΔΙΑ",
	"Srsly": "σοβαρά",
	"NigelHeathcoat": "Nigel Heathcoat < nigel@arque.local >",
	"HaveYouSeenMyLunch": "Είδες το κολατσιό μου;",
	"HaveYouSeenMyLunchSummary": "Μήπως είδες το...",
	"FrancisRobella": "Francis Robella < francis@arque.local >",
	"FrancisRobellaLine1": "Γεια",
	"FrancisRobellaLine2": "Είδες το κολατσιό μου; Το άφησα στο ψυγείο και εξαφανίστηκε. Αν μου το έκλεψε ξανά θα τρελαθώ. Πάντα μου κλέβει τα πράγματα!",
	"FrancisRobellaLine3": "Francis",
	"PleaseEnterSecretAnswer": "Εισάγετε την απάντηση στη μυστική ερώτηση για να συνεχίσετε:",
	"NameOfPet": "Πως λέγετε το κατοικίδιό σας;",
	"UnlockAllDoorsPrompt": "Χρησιμοποιήστε το παρακάτω κουμπί για να ξεκλειδώσετε όλες τις πόρτες στον κίτρινο όροφο.",
	"UnlockAllDoors": "Ξεκλείδωμα πορτών",
	"DoorsAreUnlocked": "Όλες οι πόρτες στον κίτρινο όροφο είναι ξεκλείδωτες.",
	"Image1": "IMG_0270_104942.JPEG",
	"Image2": "IMG_0430_104912.JPEG",
	"Image3": "IMG_0430_104944.JPEG",
	"Image4": "IMG_0470_104454.JPEG",
	"Image5": "IMG_0437_104954.JPEG",
	"Image6": "IMG_0440_104964.JPEG",
	"Image7": "IMG_0437_104964.JPEG",
	"Image8": "IMG_034324_432432.MP4",
	"ChristianPlitheName": "Christian Plithe",
	"ChristianPlitheAccount": "Christian Plithe < christian.plithe@arque.local >",
	"LunchRoomTitle": "Καφετέρια",
	"LunchRoomSummary": "Christian δεν μπορώ...",
	"LunchRoomLine1": "Christian δεν μπορώ να σταματήσω να σε σκέφτομαι. Από τη στιγμή που σε πρωτοείδα στην καφετέρια ήξερα πως είσαι το άτομο για μένα. Από τα λιγδιάρικα φτερά κοτόπουλου που αργά ακουμπούσαν τα χείλη σου ---------- είσαι πολύ δυνατός άνδρας. Ελπίζω να σε δω εκεί την ίδια ώρα αύριο. Θα παρακολουθώ...",
	"AdmirerName": "Η θαυμάστριά σου",
	"AdmirerAccount": "Θαυμάστρια < anonymous@arque.local >",
	"WilliamShortAccount": "William Short < william.short@arque.local >",
	"WilliamShortSig": "William Short Διαχειριστής.",
	"WilliamShortTitle": "RE: Παρενόχληση",
	"WilliamShortSummary": "Christian το ανέφερα στα...",
	"WilliamShortLine1": "Γεια Christian",
	"WilliamShortLine2": "Το ανέφερα στα κεντρικά και την τεχνική υποστήριξη και είπαν πως θα προσπαθήσουν να εντοπίσουν τη «θαυμάστρια».",
	"WilliamShortLine3": "Πρέπει να παραδεχθείς πως είναι ξεκαρδιστικό πάντως...",
	"ChrisLine1": "Γεια Will",
	"ChrisLine2": "Δέχομαι συνεχώς αυτά τα περίεργα email από κάποια που ισχυρίζεται πως είναι «θαυμάστριά» μου και έρχονται από το anonymous@arque.local.",
	"ChrisLine3": "Να ένα απόσπασμα από ένα email:",
	"ChrisLine4": "Είχαμε κάποιες διαφορές τελευταία αλλά χρειάζομαι τη βοήθειά σου με αυτό... στην αρχή ήταν περίεργο μα τώρα έγινε τρομακτικό. Μπορούμε να το καταχωρήσουμε ως επίσημη καταγγελία;",
	"ChrisLine5": "Christian",
	"MeetMeTitle": "Γιατί δεν με συνάντησες;",
	"MeetMeSummary": "Ήμουν μόνη στη...",
	"MeetMeLine1": "Ήμουν μόνη στην καφετέρια και ήθελα να σε δω να τρως αλλά δεν ήρθες! Σε σκαλώνω;",
	"MeetMeLine2": "Δεν είμαι και τόσο τρομακτική. Θα είμαι εκεί ξανά αύριο και θα περιμένω.",
	"HandledTheManagerTitle": "Είδα πως χειρίστηκες τον διαχειριστή",
	"HandledTheManagerSummary": "Μου άρεσε πάρα πολύ...",
	"HandledTheManagerLine1": "Μου άρεσε πάρα πολύ ο τρόπος που χειρίστηκες τον διαχειριστή σήμερα. Είσαι θηρίο όταν είσαι θυμωμένος. Μου άρεσε πως ο ιδρώτας κυλούσε στο δεύτερο πηγούνι σου... με κάνει και τρελαίνομαι.",
	"JonathanBillyName": "Jonathan Billy",
	"JonathanBillyAccount": "Jonathan Billy < jonathan.billy@arque.local >",
	"JonathanBillyLine1": "Έχεις βάρδια την Παρασκευή",
	"JonathanBillyLine2": "Η κόρη μου έχει διαγωνισμό κολύμβησης και η γυναίκα μου λέει πως πρέπει να πάω. Μπορείς να με καλύψεις;",
	"JonathanBillyLine3": "Ευχαριστώ",
	"JonathanBillyLine4": "από Jono",
	"DavidGravenName": "David Graven",
	"DavidGravenAccount": "David Graven < david.graven@arque.local >",
	"DavidGravenTitle1": "RE: Παρασκευή",
	"DavidGravenTitle2": "Κουτιά",
	"DavidGravenSummary1": "Δεν πειράζει. Απόλαυσε την ημέρα :)",
	"DavidGravenSummary2": "Μπορούμε να μετακινήσουμε κάποια κουτιά",
	"DavidGravenEmail1": "Jono",
	"DavidGravenEmail2": "Μπορούμε να μετακινήσουμε κάποια κουτιά στην αποθήκη στην ανατολική Arque; Λένε πως έχουν να φέρουν κι άλλα αλλά δεν μπορούμε να χωρέσουμε πολλά ακόμα εδώ πέρα, ακόμα και με τους μεγάλους γερανούς. Θα μιλήσω με τον Jeff για αυτό... έπρεπε να είχαν μετακινήσει μερικούς στον πάνω όροφο ήδη.",
	"DavidGravenSig": "Dave",
	"JonathanBillyTitle": "Παρασκευή",
	"JeffHerbandTitle": "Νέα κουτιά...",
	"JeffHerbandSummary": "Έρχονται περισσότερα κουτιά",
	"JeffHerbandAccount": "Jeff Herband < jeff.herband@arque.local >",
	"JeffHerbandName": "Jeff Herband",
	"JeffHerbandSig": "Διαχειριστής δυτικής αποθήκης Arque",
	"JeffHerbandLine1": "Έρχονται περισσότερα κουτιά. Απλά κράτα τα ασφαλή. Δε θέλουμε να σπάσει τίποτα.",
	"WentworthHeraldTitle": "TA NEA TOY Wentworth",
	"WentworthHeraldTagline": "ΝΟΥΜΕΡΟ ΕΝΑ ΓΙΑ ΝΕΑ, ΚΟΥΤΣΟΜΠΟΛΙΑ, ΑΘΛΗΤΙΚΑ, ΟΙΚΟΝΟΜΙΚΑ ΚΑΙ ΣΤΑΥΡΟΛΕΞΑ. Η ΕΦΗΜΕΡΙΔΑ ΤΗΣ ΖΩΗΣ ΣΑΣ.",
	"MoreOnPage7": "ΠΕΡΙΣΣΟΤΕΡΑ ΣΕΛ. 7",
	"MoreOnPage10": "ΠΕΡΙΣΣΟΤΕΡΑ ΣΕΛ. 10",
	"LighthouseDecomissionedTitle": "ΚΛΕΙΝΟΥΝ ΤΑ ΦΩΤΑ ΣΤΟ ΦΑΡΟ",
	"LighthouseDecomissionedParagraph1": "Ο φάρος στο Redton πρόκειται να σταματήσει να λειτουργεί από τον δήμαρχο John Menn έπειτα από έρευνα της ακτοφυλακής.",
	"LighthouseDecomissionedParagraph2": "«Είμαστε σίγουροι πως αυτό δε θα επηρεάσει τις ακτογραμμές» σχολίασε ο Bill Hayak του Υφυπουργείου ακτοπλοΐας και θαλάσσιων μεταφορών. «Ενώ κάποτε υπήρχαν πολλά μεταφορικά πλοία λίγο έξω από τις ακτές του Redton, τώρα πλέον δε συμβαίνει αυτό καθώς οι κύριες ακτοπλοϊκές γραμμές για την ηπειρωτική χώρα αλλάζουν» πρόσθεσε.",
	"LighthouseDecomissionedParagraph3": "Όταν ερωτήθηκε, ο δήμαρχος αρνήθηκε να σχολιάσει μέχρι να εκδοθεί επίσημη ανακοίνωση για το κλείσιμο του φάρου.",
	"LighthouseDecomissionedParagraph4": "Οι κάτοικοι δεν είναι ευχαριστημένοι με την αλλαγή και ένας τοπικός πολίτης ανησυχεί για τις επιδράσεις σε μικρότερα εμπορικά σκάφη που ακόμα προσαράζουν στο νησί λέγοντας πως είναι το τελευταίο καρφί στον τάφο του ήσυχου λιμανιού του νησιού. «Θα σταματήσει πολλή από τη ναυτική επιχειρηματικότητα του νησιού» σημείωσε.",
	"LighthouseDecomissionedParagraph5": "Καμιά φορά ο φάρος είναι το μόνο πράγμα που επιτρέπει σε μικρότερα σκάφη να έρθουν και να αγοραπωλήσουν σε τοπικές αγορές και αυτό μας ανησυχεί όλους. Τι θα συμβεί όταν δε θα υπάρχει πια δουλειά για εισαγωγές εδώ;",
	"LighthouseDecomissionedQuote": "«ΠΟΛΥ ΛΙΓΑ» ΠΛΟΙΑ ΓΙΑ ΝΑ ΘΕΩΡΗΘΕΙ ΘΕΜΑ ΑΣΦΑΛΕΙΑΣ ΛΕΕΙ Η ΑΚΤΟΦΥΛΑΚΗ",
	"LostTitle": "ΧΑΘΗΚΕ",
	"LostParagraph1": "Δύο εβδομάδες πέρασαν από τότε που ο τοπικός υπάλληλος της Arque, Christian Plithe, έχασε τη μαύρη γάτα του «Lucky». Καλεί όποιον δει τη γάτα να επικοινωνήσει μαζί του αμέσως.",
	"ScarecrowCompetitionTitle": "ΣΕ ΕΞΕΛΙΞΗ ΤΟΠΙΚΟΣ ΔΙΑΓΩΝΙΣΜΟΣ ΣΚΙΑΧΤΡΟΥ",
	"ScarecrowCompetitionParagraph1": "Ένας από τους δημοφιλέστερους διαγωνισμούς του Redton επέστρεψε και φέτος.",
	"ScarecrowCompetitionParagraph2": "Η κοινότητα μαζεύεται κάθε χρόνο για να δημιουργήσει τα πιο τρομερά και τρομακτικά σκιάχτρα για να κρατήσουν μακριά τα πουλιά. Ο περσινός νικητής ήταν ο οκτάχρονος Joshua Fenton, μαθητής στο τοπικό σχολείο, που κέρδισε τους κριτές με την αναπαράσταση της γιαγιάς του.",
	"ScarecrowCompetitionParagraph3": "Ο φετινός νικητής του διαγωνισμού θα κερδίσει μια υπέροχη ποικιλία από τούρτες της Julia Menn, της συζύγου του δημάρχου που πρόσφατα άνοιξε το δικό της ζαχαροπλαστείο στο νησί.",
	"ScarecrowCompetitionParagraph4": "Οι εκδηλώσεις δε σταματούν με τα σκιάχτρα, που θα προβάλλονται όλη την εβδομάδα. Υπάρχουν διάφοροι πάγκοι και δραστηριότητες σε όλη την πόλη. Αν δεν έχετε δει τα σκιάχτρα ακόμα πηγαίνετε στην ετήσια γιορτή και δείτε όλο το εορταστικό κλίμα και γευτείτε τα καλύτερα φαγητά και ποτά που έχει να προσφέρει το Redton.",
	"ScarecrowCompetitionParagraph5": "Αν δεν μπορείτε να δείτε τα σκιάχτρα, θα έχουμε πλήρες αφιέρωμα στους διαγωνιζόμενους στο επόμενο τεύχος.",
	"OmnicorpTitle": "Η Arque ΑΠΟΚΤΑ ΤΗ Phillips ΦΑΡΜΑΚΕΥΤΙΚΗ",
	"OmnicorpParagraph1": "Τριάντα εργάτες απολύθηκαν στην αρχή της προηγούμενης εβδομάδας η γιγαντιαία Arque Corporation ολοκλήρωσε την εξαγορά της τοπικής φαρμακευτικής εταιρίας Phillips. Την εξαγορά ακολούθησε μια αρκετά δημόσια κατάρρευση του προηγούμενου ιδιοκτήτη που είχε ως αποτέλεσμα την αναζήτηση νέων επενδυτών.",
});